<#  Audit: vanilla script references to production methods our tier-split relocated. #>
$ErrorActionPreference='Stop'
$repo = "C:\claude-code\victoria 3 PM and tech rehaul"
$game = "C:\Program Files (x86)\Steam\steamapps\common\Victoria 3\game"
$cfg  = Get-Content (Join-Path $repo 'config\mod_config.json') -Raw | ConvertFrom-Json
$split = @{}; foreach($i in $cfg.industries){ foreach($t in $i.tiers){ if($t.vanilla_pm){ $split[$t.vanilla_pm]=$i.id } } }

$files = @()
$files += Get-ChildItem (Join-Path $game 'events') -Filter *.txt -Recurse -EA SilentlyContinue
foreach($d in Get-ChildItem (Join-Path $game 'common') -Directory){
    if($d.Name -in @('production_methods','production_method_groups','buildings')){ continue }
    $files += Get-ChildItem $d.FullName -Filter *.txt -Recurse -EA SilentlyContinue
}

$rows = @()
foreach($f in $files){
    $lines = Get-Content -LiteralPath $f.FullName
    $block=$null; $curBld=$null
    for($k=0;$k -lt $lines.Count;$k++){
        $l=$lines[$k]
        if($l -match '^([A-Za-z_][A-Za-z0-9_.]*)\s*=\s*\{'){ $block=$Matches[1] }
        if($l -match 'building_type\s*=\s*(building_[A-Za-z0-9_]+)'){ $curBld=$Matches[1] }
        if($l -match 'production_method\s*=\s*(pm_[A-Za-z0-9_-]+)'){
            $pm=$Matches[1]
            if($split.ContainsKey($pm)){
                $rows += [pscustomobject]@{ pm=$pm; industry=$split[$pm]; building=$curBld; block=$block;
                    file=($f.FullName.Replace($game+'\','').Replace('\','/')); line=($k+1) }
            }
        }
    }
}
$dedup = $rows | Group-Object { "$($_.pm)|$($_.block)" } | ForEach-Object { $_.Group | Select-Object -First 1 }
"total raw refs: $($rows.Count); deduped: $($dedup.Count)"

$dash = [char]0x2014
$out = New-Object System.Collections.Generic.List[string]
$out.Add("# Vanilla script references to relocated production methods")
$out.Add("")
$out.Add("**Auto-generated by tools/audit_pm_refs.ps1** $dash a catalogue of vanilla **events / journal entries /")
$out.Add("scripted effects / triggers** that reference a *main* production method our tier split moved onto a")
$out.Add("separate tier building. When such a check runs against the base building, the PM is no longer valid there,")
$out.Add("so ``is_production_method_active`` (and similar) **errors and returns false** $dash the flavor/journal")
$out.Add("content won't detect our tiered buildings. **No crashes; missed content.** See BUGS_AND_FIXES.md (2026-07-18).")
$out.Add("Deduped by (PM, enclosing block): same PM in the same block across country/state copies = one row; the")
$out.Add("same PM in a different block = a separate row.")
$out.Add("")
$out.Add("**This is a living, deliberately-premature catalogue.** We will relocate *more* vanilla PMs as we add")
$out.Add("tiers, so **re-run ``tools/audit_pm_refs.ps1`` after any tiering change or game patch** to refresh it.")
$out.Add("**Convention:** when an in-game run surfaces a *new* log error of this class (a vanilla script referring")
$out.Add("to a PM we relocated/removed), **append it here** (or add its PM to the split set + re-run) rather than")
$out.Add("fixing it. Do NOT fix piecemeal $dash we batch one strategic pass later (lean: make our new tier")
$out.Add("buildings eligible where advanced enough).")
$out.Add("")
$out.Add("| PM (relocated) | Our industry | Checked on building | Enclosing block (event/JE/effect) | File:line |")
$out.Add("|---|---|---|---|---|")
foreach($r in ($dedup | Sort-Object industry, pm, block)){
    $b = if($r.building){'`'+$r.building+'`'}else{'-'}
    $out.Add("| ``$($r.pm)`` | $($r.industry) | $b | ``$($r.block)`` | $($r.file):$($r.line) |")
}
$out.Add("")
$nf = (($dedup | Select-Object -ExpandProperty file -Unique)).Count
$out.Add("_$($dedup.Count) distinct (PM, block) cases across $nf files._")
Set-Content (Join-Path $repo 'MISSING_PM_REFERENCES.md') ($out -join "`n") -Encoding UTF8 -NoNewline
"wrote MISSING_PM_REFERENCES.md ($($dedup.Count) rows)"
