<#
  PM & Tech Rehaul - mod builder.

  Reads config/mod_config.json and generates the whole mod:
    mod/common/buildings/zzz_pm_rehaul_01_industry.txt
    mod/common/production_methods/zzz_pm_rehaul_01_industry.txt
    mod/common/production_method_groups/zzz_pm_rehaul_01_industry.txt
    mod/localization/<lang>/zzz_pm_rehaul_l_<lang>.yml   (ALL configured languages)
    tools/ladder_tiers.txt                               (linter tier map, derived from config)

  Building logic: per tier the config carries ACTUAL volumes (output_qty + inputs, derived by
  solve_volumes.ps1). The builder emits them as-is, preserves employment/pollution, and labels each
  building with its actual FULL break-even (input goods + wages; wages = wage_pct fraction of TOTAL,
  default 0.33). See BALANCE_FRAMEWORK §1/§8.

  Usage:   powershell -ExecutionPolicy Bypass -File tools\build.ps1 [-NoLint] [-NoDeploy] [-Config <path>] [-DryRun] [-SaveTo <name>]

  -Config lets you build from a specific config file (the same mod_config.json the UI emits)
  instead of the default config/mod_config.json - handy for building an alternate balance set
  without the UI. The path is threaded through the start extractor + history converter too, so
  the whole build (including the 1836 start) uses that config. Default: config/mod_config.json.

  Output location (default is the canonical mod/ folder, which also deploys to the Paradox mod
  folder). Two ways to build WITHOUT touching mod/:
    -DryRun         Build a full, real mod into a throwaway folder (mod_dryrun_<pid>), run the
                    post-build checks on the finished mod, report, then DELETE the folder. Never
                    deploys. Use this to verify a build/config safely - it never rewrites mod/.
    -SaveTo <name>  Build into mod_<name>/ inside the repo and KEEP it (not deployed, not deleted).
                    For alternate balance sets you want to compare/keep. Clean up manually.
  -DryRun and -SaveTo are mutually exclusive. Both leave the canonical mod/ untouched.
#>
param([switch]$NoLint, [switch]$NoDeploy, [string]$Config, [switch]$DryRun, [string]$SaveTo, [switch]$IncludeAllBuildings)
$ErrorActionPreference = 'Stop'
$INV = [System.Globalization.CultureInfo]::InvariantCulture
function Fmt($v) { return ([double]$v).ToString($INV) }   # locale-safe number -> string
function RoundHalfUp($x) { return [int][math]::Floor([double]$x + 0.5) }

# clone_from_vanilla: build a tier building by copying the vanilla block and surgically swapping only
# the header key, unlocking_technologies, production_method_groups, and (optionally) required_construction.
# Everything else (port=yes, terrain_manipulator, ai_value, should_auto_expand, potential, ...) is kept
# verbatim so the special engine semantics of ports/railways/power survive. `^` matches string start, so
# the header swap hits only the first line (not e.g. building_railway references inside ai_value blocks).
function New-ClonedBuilding($vanLines, $tierKey, $baseKey, $tech, $pmgTokens, $reqCon) {
    $s = ($vanLines -join "`n")
    $s = [regex]::Replace($s, '^\s*' + [regex]::Escape($baseKey) + '\s*=\s*\{', "$tierKey = {")
    $utech = "unlocking_technologies = { $tech }"
    if ($s -match 'unlocking_technologies\s*=\s*\{[^{}]*\}') { $s = [regex]::Replace($s, 'unlocking_technologies\s*=\s*\{[^{}]*\}', $utech) }
    else { $s = [regex]::Replace($s, '^(' + [regex]::Escape($tierKey) + '\s*=\s*\{)', "`$1`n`t$utech") }
    $pmgBlock = "production_method_groups = {`n`t`t" + ($pmgTokens -join "`n`t`t") + "`n`t}"
    $s = [regex]::Replace($s, 'production_method_groups\s*=\s*\{[^{}]*\}', $pmgBlock)
    if ($null -ne $reqCon) { $s = [regex]::Replace($s, 'required_construction\s*=\s*\S+', "required_construction = $reqCon") }
    return $s
}

# Override the ai_value of a PRESERVED (verbatim-copied) building block in an owned file — e.g. trade
# center. Replaces a scalar `ai_value = N`, inserts one after the header if absent, and leaves a complex
# `ai_value = { … }` block untouched (with a note) so we never mangle conditional AI scripting.
function Set-BuildingAiValue($lines, $value) {
    $arr = @($lines)
    for ($k = 0; $k -lt $arr.Count; $k++) {
        if ($arr[$k] -match '^\s*ai_value\s*=\s*\{')      { Write-Output "note: $($arr[0].Trim()) has a complex ai_value block - not overriding"; return $arr }
        if ($arr[$k] -match '^\s*ai_value\s*=\s*-?\d+')   { $arr[$k] = "`tai_value = $([int]$value)"; return $arr }
    }
    $out = New-Object System.Collections.Generic.List[string]
    $out.Add($arr[0]); $out.Add("`tai_value = $([int]$value)")
    for ($k = 1; $k -lt $arr.Count; $k++) { $out.Add($arr[$k]) }
    return $out.ToArray()
}

$repo = Split-Path $PSScriptRoot -Parent
$genHeader = "# AUTO-GENERATED by tools/build.ps1 from config/mod_config.json - do not edit by hand.`n"

# --- load prices ---
$prices = @{}
foreach ($line in (Get-Content (Join-Path $repo 'tools\goods_prices.tsv'))) {
    if ($line -match '^\s*#' -or $line.Trim() -eq '') { continue }
    $c = $line -split "`t"
    if ($c.Count -ge 2) { $prices[$c[0].Trim()] = [double]$c[1].Trim() }
}

# --- load config (default, or a caller-supplied file via -Config) ---
$cfgPath = if ($Config) { (Resolve-Path -LiteralPath $Config).Path } else { Join-Path $repo 'config\mod_config.json' }
Write-Output "Config: $cfgPath"
$cfg = Get-Content -LiteralPath $cfgPath -Raw | ConvertFrom-Json
$Game = $(if ($env:VIC3_GAME) { $env:VIC3_GAME } else { "C:\Program Files (x86)\Steam\steamapps\common\Victoria 3\game" })

# include_all_buildings: EMISSION-scope switch for the untouched (non-tiered) vanilla buildings.
# It does NOT affect the UI (which always shows every building) - only whether those buildings are
# emitted into the built mod. Source is the config field; -IncludeAllBuildings forces it on. Default
# off = only our tiered industries reach the mod (today's behavior). See CLAUDE.md.
$includeAll = $IncludeAllBuildings.IsPresent -or [bool]$cfg.include_all_buildings
Write-Output ("include_all_buildings = {0} (emission scope for non-tiered buildings)" -f $includeAll)

# --- resolve output mod directory (relative name under repo) --------------------------------------
#   default 'mod' (canonical, deploys); -SaveTo X -> 'mod_X' (kept); -DryRun -> throwaway (deleted).
if ($DryRun -and $SaveTo) { throw "-DryRun and -SaveTo are mutually exclusive." }
$isAlt = $DryRun -or $SaveTo
if ($DryRun) {
    $modRel = "mod_dryrun_$PID"
} elseif ($SaveTo) {
    if ($SaveTo -notmatch '^[A-Za-z0-9._-]+$') { throw "-SaveTo name must be [A-Za-z0-9._-]+ (got '$SaveTo')." }
    $modRel = "mod_$SaveTo"
} else {
    $modRel = "mod"
}
$modAbs = Join-Path $repo $modRel
Write-Output "Output: $modRel$(if ($DryRun) { '  (dry run - will be deleted)' } elseif ($SaveTo) { '  (kept, not deployed)' })"

# For an alternate target, start from a clean folder but seed the one hand-maintained file
# (.metadata/metadata.json) from the canonical mod/ so the result is a complete, loadable mod.
if ($isAlt) {
    if (Test-Path $modAbs) { Remove-Item $modAbs -Recurse -Force }
    $srcMeta = Join-Path $repo 'mod\.metadata\metadata.json'
    $dstMeta = Join-Path $modAbs '.metadata\metadata.json'
    New-Item -ItemType Directory -Force -Path (Split-Path $dstMeta -Parent) | Out-Null
    Copy-Item -LiteralPath $srcMeta -Destination $dstMeta -Force
}

# --- post-build checks: run on the FINISHED mod folder (after generation + convert + lint).
#   This is the mandated-checks hook the dry run relies on; add future must-pass checks here.
#   Returns an array of problem strings (empty = healthy). Existence + non-empty of the files a
#   loadable build must have, one loc file per configured language. ------------------------------
function Invoke-ModChecks($modRoot, $config) {
    $problems = @()
    $required = @(
        'common\buildings\01_industry.txt',
        'common\production_methods\zzz_pm_rehaul_01_industry.txt',
        'common\production_method_groups\zzz_pm_rehaul_01_industry.txt',
        '.metadata\metadata.json'
    )
    foreach ($r in $required) {
        $p = Join-Path $modRoot $r
        if (-not (Test-Path $p)) { $problems += "missing: $r" }
        elseif ((Get-Item $p).Length -eq 0) { $problems += "empty: $r" }
    }
    foreach ($lang in $config.languages) {
        $p = Join-Path $modRoot "localization\$lang\replace\$($config.loc_basename)_l_$lang.yml"
        if (-not (Test-Path $p)) { $problems += "missing loc: $lang" }
        elseif ((Get-Item $p).Length -eq 0) { $problems += "empty loc: $lang" }
    }
    return $problems
}

# --- clean previously generated outputs (keep .metadata + history, which the converter rewrites) ---
foreach ($d in 'common\buildings', 'common\production_methods', 'common\production_method_groups') {
    $p = Join-Path $modAbs $d
    if (Test-Path $p) { Remove-Item (Join-Path $p '*') -Force -Recurse -ErrorAction SilentlyContinue }
}
$locRoot = Join-Path $modAbs 'localization'
if (Test-Path $locRoot) { Remove-Item $locRoot -Recurse -Force -ErrorAction SilentlyContinue }

$pmOut = @($genHeader); $pmgOut = @($genHeader)
$genByBase = @{}        # base building key -> generated text for that whole industry (base + tiers)
$genFileOf = @{}        # base building key -> which vanilla buildings file we emit it into (we whole-file-replace that file)
$locBody = @()          # localization entries (identical across languages)

# Owned vanilla building files: 01_industry.txt (default) plus any industry's source_file (06/11 for the
# new-economy chains). We whole-file-replace each. Parse their building blocks up front so clone_from_vanilla
# industries can copy the vanilla block.
$defaultSrc = 'common/buildings/01_industry.txt'
$ownedRels = @(@($cfg.industries | Where-Object { -not $_.disabled } | ForEach-Object { if ($_.source_file) { $_.source_file } else { $defaultSrc } }) | Select-Object -Unique)
$vanBld = @{}           # vanilla building key -> block lines (for cloning)
foreach ($rel in $ownedRels) {
    $vl = Get-Content -LiteralPath (Join-Path $Game ($rel -replace '/','\'))
    $j = 0
    while ($j -lt $vl.Count) {
        if ($vl[$j] -match '^(building_[A-Za-z0-9_]+)\s*=\s*\{') {
            $bk = $Matches[1]; $d = 0; $buf = New-Object System.Collections.Generic.List[string]
            do { $l = $vl[$j]; $d += ([regex]::Matches($l,'\{')).Count - ([regex]::Matches($l,'\}')).Count; $buf.Add($l); $j++ } while ($j -lt $vl.Count -and $d -gt 0)
            $vanBld[$bk] = $buf.ToArray()
        } else { $j++ }
    }
}
$tierMap = @('# MAIN production method  tier(1-based)  target_be  wage_pct. AUTO-GENERATED by build.ps1.')
$summary = @()
$D = [char]36           # literal '$' for loc interpolation

foreach ($ind in $cfg.industries) {
    if ($ind.disabled) { continue }   # leave vanilla (no split); config keeps the data for later
    $tierNo = 0
    $indBld = @()
    foreach ($t in $ind.tiers) {
        $tierNo++

        # inputs/output_qty are actual volumes; the builder emits them directly.
        $outGood = if ($t.output_good) { $t.output_good } else { $ind.output_good }
        $Oval = [double]$t.output_qty * $prices[$outGood]
        $wage = if ($null -ne $t.wage_pct) { [double]$t.wage_pct } else { 0.25 }   # wages as fraction of TOTAL cost (input goods + wages); default 0.25 (BALANCE_FRAMEWORK §1)

        # ---- PM ----
        $pm = @("$($t.pm_key) = {", "`ttexture = `"$($t.texture)`"")
        # state modifiers (workforce-scaled): pollution + infrastructure (ports/railways produce infra).
        $stateMods = @()
        if ([double]$t.pollution -gt 0) { $stateMods += "state_pollution_generation_add = $([int]$t.pollution)" }
        if ($null -ne $t.state_infrastructure) { $stateMods += "state_infrastructure_add = $([int]$t.state_infrastructure)" }
        if ($stateMods.Count -gt 0) {
            $pm += "`tstate_modifiers = {","`t`tworkforce_scaled = {"
            foreach ($sm in $stateMods) { $pm += "`t`t`t$sm" }
            $pm += "`t`t}","`t}"
        }
        # country modifiers: shipyards grant naval capacity (country_ship_construction_add) from the SAME
        # PM that makes clippers/steamers — dropping it silently breaks building/maintaining navies.
        if ($null -ne $t.ship_construction) {
            $pm += "`tcountry_modifiers = {","`t`tworkforce_scaled = {","`t`t`tcountry_ship_construction_add = $([int]$t.ship_construction)","`t`t}","`t}"
        }
        $pm += "`tbuilding_modifiers = {","`t`tworkforce_scaled = {"
        $actualI = 0.0
        foreach ($p in $t.inputs.PSObject.Properties) {
            $q = [int]$p.Value
            $actualI += $q * $prices[$p.Name]
            $pm += "`t`t`tgoods_input_$($p.Name)_add = $q"
        }
        $pm += "`t`t`tgoods_output_$($outGood)_add = $([int]$t.output_qty)","`t`t}"
        # employment (level_scaled). Some buildings carry NO base-PM employment (e.g. the art academy: jobs live
        # in its ownership PMG, kept as a secondary), so omit the block entirely when employment is empty.
        $empProps = if ($null -ne $t.employment) { @($t.employment.PSObject.Properties) } else { @() }
        if ($empProps.Count -gt 0) {
            $pm += "`t`tlevel_scaled = {"
            foreach ($e in $empProps) { $pm += "`t`t`tbuilding_employment_$($e.Name)_add = $([int]$e.Value)" }
            $pm += "`t`t}"
        }
        $pm += "`t}"
        if ($null -ne $t.required_input_goods) { $pm += "`trequired_input_goods = $($t.required_input_goods)" }
        $pm += "}",""
        $pmOut += $pm
        $actualBe = if ($Oval -gt 0) { $actualI / (1 - $wage) / $Oval * 100 } else { 0 }   # actual FULL break-even (total cost = goods/(1-wage)), for the building name + summary

        # ---- PMG (single main PM) ----
        $pmgOut += "$($t.pmg_key) = {","`ttexture = `"gfx/interface/icons/generic_icons/mixed_icon_base.dds`"","`tproduction_methods = { $($t.pm_key) }","}",""

        # ---- Building ----
        if ($ind.clone_from_vanilla) {
            # copy the vanilla block, swap only key/tech/PMGs/(construction); keep all special engine fields.
            $baseKey = $ind.tiers[0].key
            if (-not $vanBld.ContainsKey($baseKey)) { throw "clone_from_vanilla: vanilla building '$baseKey' not found in owned files for industry '$($ind.id)'" }
            $pmgTokens = @($t.pmg_key) + @($ind.secondary_pmgs)
            $reqCon = if ($null -ne $t.building_cost) { [int]$t.building_cost } else { $null }   # $null => keep vanilla required_construction
            $indBld += (New-ClonedBuilding $vanBld[$baseKey] $t.key $baseKey $t.tech $pmgTokens $reqCon)
            $indBld += ""
        } else {
            $b = $ind.building
            $bl = @("$($t.key) = {")
            # aliases (vanilla plural keys) belong ONLY to the tier-1 base building, which reuses
            # the vanilla key; putting them on higher tiers would be a duplicate-alias conflict.
            if ($null -ne $b.aliases -and $tierNo -eq 1) { $bl += "`taliases = { $($b.aliases -join ' ') }" }
            $bl += "`tbuilding_group = $($b.building_group)","`ticon = `"$($b.icon)`"","`tcity_type = $($b.city_type)","`tlevels_per_mesh = $([int]$b.levels_per_mesh)"
            if ($null -ne $b.ai_nationalization_desire) { $bl += "`tai_nationalization_desire = $(Fmt $b.ai_nationalization_desire)" }
            $bl += "`tunlocking_technologies = { $($t.tech) }","`tproduction_method_groups = {","`t`t$($t.pmg_key)"
            foreach ($s in $ind.secondary_pmgs) { $bl += "`t`t$s" }
            # required_construction: per-tier building_cost (construction points) if set, else the
            # building-level fallback (a raw number or a vanilla script-value name like construction_cost_high).
            $reqCon = if ($null -ne $t.building_cost) { [int]$t.building_cost } else { $b.required_construction }
            $bl += "`t}","`trequired_construction = $reqCon"
            if ($b.heavy_industry_law) { $bl += "`tpossible = {","`t`towner = {","`t`t`tNOT = {","`t`t`t`tOR = {","`t`t`t`t`thas_law_or_variant = law_type:law_industry_banned","`t`t`t`t`thas_law_or_variant = law_type:law_extraction_economy","`t`t`t`t}","`t`t`t}","`t`t}","`t}" }
            if ($b.coastal_only) { $bl += "`tpotential = {","`t`tis_coastal = yes","`t}" }
            # ai_value: per-tier override (editable in the UI) wins, else the building-level fallback.
            $aiv = if ($null -ne $t.ai_value) { $t.ai_value } elseif ($null -ne $b.ai_value) { $b.ai_value } else { $null }
            if ($null -ne $aiv) { $bl += "`tai_value = $([int]$aiv)" }
            $bl += "`townership_type = $($b.ownership_type)","`tbackground = `"$($b.background)`"","}",""
            $indBld += $bl
        }

        # ---- localization (shared body) ----
        # follows_be:false industries (ports, railways) stay on vanilla economics, so their name omits
        # the BE target (BE is not the design handle for them).
        $beLabel = if ($ind.follows_be -eq $false) { "" } else { ". BE target $([math]::Round($actualBe))%" }
        $locBody += " $($t.key):0 `"Tier $tierNo. $($t.name)$beLabel`""
        $locBody += " $($t.key)_lens_option:0 `"Expand $D$($t.key)$D`""
        $locBody += " $($t.pmg_key):0 `"$($t.pm_name)`""
        $locBody += " $($t.pm_key):0 `"$($t.pm_name)`""

        # ---- tier map + summary ---- (columns: pm tier target_be wage_pct; linter reads all four)
        # The hard linter ladder covers only the core manufacturing chains. New-economy industries
        # (no_mass_be: power/port/railway) are excluded: ports/railways stay on vanilla economics, and
        # power's tiny volumes (output 25) miss its BE target by a few pp on integer rounding by design.
        if ($ind.follows_be -ne $false -and -not $ind.no_mass_be) { $tierMap += "$($t.pm_key) $tierNo $($t.target_be) $(Fmt $wage)" }
        $summary += [pscustomobject]@{ Building=$t.key; Tier=$tierNo; TargetBE=$t.target_be; ActualBE=[math]::Round($actualBe) }
    }
    $genByBase[$ind.tiers[0].key] = ($indBld -join "`n")   # keyed by the vanilla base building key
    $genFileOf[$ind.tiers[0].key] = if ($ind.source_file) { $ind.source_file } else { $defaultSrc }
}

# --- write files ---
$noBom = New-Object System.Text.UTF8Encoding($false)   # tool files (ladder_tiers)
$bom   = New-Object System.Text.UTF8Encoding($true)    # game content (common/*, localization) - matches vanilla
function WriteText($rel, $text, $enc) {
    $path = Join-Path $repo $rel
    $dir = Split-Path $path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    [System.IO.File]::WriteAllText($path, $text, $enc)
}
WriteText "$modRel\common\production_methods\zzz_pm_rehaul_01_industry.txt"        (($pmOut  -join "`n") + "`n") $bom
WriteText "$modRel\common\production_method_groups\zzz_pm_rehaul_01_industry.txt"  (($pmgOut -join "`n") + "`n") $bom
# Linter tier map: canonical build writes the committed tools\ladder_tiers.txt; alternate builds
# (-DryRun/-SaveTo) write a throwaway temp copy so they never mutate the committed file.
if ($isAlt) {
    $ladderPath = Join-Path ([System.IO.Path]::GetTempPath()) "pm_ladder_$PID.txt"
    [System.IO.File]::WriteAllText($ladderPath, (($tierMap -join "`n") + "`n"), $noBom)
} else {
    WriteText 'tools\ladder_tiers.txt' (($tierMap -join "`n") + "`n") $noBom
    $ladderPath = Join-Path $repo 'tools\ladder_tiers.txt'
}

# --- buildings: REPLACE each OWNED vanilla buildings file (same filename) ---
# V3 rejects a redefined building key that comes from a different file, so the mod must OWN the whole
# file. We own 01_industry.txt (manufacturing) plus any industry's source_file (06_urban_center for
# power, 11_private_infrastructure for port/railway). For each owned file: copy vanilla, swap each of
# OUR base building blocks (that belong to that file) for our (base + tier) set, keep everything else
# verbatim; append any of our new industries that have no vanilla anchor in that file.
# ai_value overrides for PRESERVED buildings in owned files (config top-level building_ai_value map).
$aiMap = @{}
if ($cfg.building_ai_value) { foreach ($p in $cfg.building_ai_value.PSObject.Properties) { $aiMap[$p.Name] = [int]$p.Value } }
foreach ($rel in $ownedRels) {
    $relWin = $rel -replace '/','\'
    $vanLines = Get-Content -LiteralPath (Join-Path $Game $relWin)
    $bOut = New-Object System.Collections.Generic.List[string]
    $bOut.Add($genHeader.TrimEnd())
    $emitted = @{}; $i = 0
    while ($i -lt $vanLines.Count) {
        $line = $vanLines[$i]
        if ($line -match '^(building_[A-Za-z0-9_]+)\s*=\s*\{') {
            $bkey = $Matches[1]
            $blk = New-Object System.Collections.Generic.List[string]; $depth = 0
            do {
                $l = $vanLines[$i]
                $depth += ([regex]::Matches($l, '\{')).Count - ([regex]::Matches($l, '\}')).Count
                $blk.Add($l); $i++
            } while ($i -lt $vanLines.Count -and $depth -gt 0)
            if ($genByBase.ContainsKey($bkey) -and $genFileOf[$bkey] -eq $rel) { $bOut.Add($genByBase[$bkey]); $emitted[$bkey] = $true }
            elseif ($aiMap.ContainsKey($bkey)) { foreach ($bl2 in (Set-BuildingAiValue $blk $aiMap[$bkey])) { $bOut.Add($bl2) } }   # preserved building + ai_value override (trade center, …)
            else { foreach ($bl2 in $blk) { $bOut.Add($bl2) } }
        } else { $bOut.Add($line); $i++ }
    }
    foreach ($bk in $genByBase.Keys) { if ($genFileOf[$bk] -eq $rel -and -not $emitted.ContainsKey($bk)) { Write-Output "note: $bk has no vanilla base building in $rel - appending as a new industry (expected for split-out chains, e.g. the steamer shipyard)"; $bOut.Add($genByBase[$bk]) } }
    WriteText "$modRel\$relWin" (($bOut -join "`n") + "`n") $bom
}

# --- ai_strategies: REPLACE 01_admin_strategies.txt to control AI SUBSIDY POLICY ------------------
# The `subsidies` block inside an ai_strategy is the AI's subsidy DECISION RULE (must_have /
# wants_to_have / nice_to_have) - NOT a per-building flag. It is the only durable way to make the AI
# subsidize a building: the AI re-scores subsidies continuously (defines NAI SUBSIDIZE_*), so a scripted
# `set_subsidized` would simply be undone on its next pass.
# WHY THIS FILE: we own the ADMINISTRATIVE strategies (all 7 live in this one ~655-line file) rather than
# ai_strategy_default (a single ~8790-line block) - a 13x smaller patch surface. Every AI country always
# runs exactly one administrative strategy (ai_strategy_industrial_expansion has no `possible` gate, so it
# is always available), so covering all 7 covers everyone.
# TRIO RESTATEMENT: it is unclear whether a typed strategy's `subsidies` MERGES with ai_strategy_default's
# per key or REPLACES it wholesale, so we restate the default's power_plant/railway/port = must_have in
# every block we write. That is a no-op under merge and correct under replace.
# Config: top-level `building_subsidies` map, building key -> vanilla|none|nice_to_have|wants_to_have|must_have.
#   vanilla (or absent) = emit nothing for that building (its vanilla entries stand)
#   none                = suppress it (drop the key from every block we write)
$SUBSIDY_ENUM = @('nice_to_have','wants_to_have','must_have')
# depth-1 `subsidies = { … }` helpers: read its building->value entries, and strip the whole block out.
function Get-SubsidyEntries($blk) {
    $out = [ordered]@{}; $d = 0; $inb = $false
    foreach ($l in $blk) {
        if (-not $inb -and $l -match '^\s*subsidies\s*=\s*\{') { $inb = $true; $d = 0 }
        if ($inb) {
            $d += ([regex]::Matches($l,'\{')).Count - ([regex]::Matches($l,'\}')).Count
            if ($l -match '^\s*(building_[A-Za-z0-9_]+)\s*=\s*([a-z_]+)') { $out[$Matches[1]] = $Matches[2] }
            if ($d -le 0) { $inb = $false }
        }
    }
    return $out
}
function Test-HasSubsidyBlock($blk) {
    foreach ($l in $blk) { if ($l -match '^\s*subsidies\s*=\s*\{') { return $true } }
    return $false
}
function Remove-SubsidyBlock($blk) {
    $out = New-Object System.Collections.Generic.List[string]; $d = 0; $inb = $false
    foreach ($l in $blk) {
        if (-not $inb -and $l -match '^\s*subsidies\s*=\s*\{') { $inb = $true; $d = 0 }
        if ($inb) {
            $d += ([regex]::Matches($l,'\{')).Count - ([regex]::Matches($l,'\}')).Count
            if ($d -le 0) { $inb = $false }
            continue
        }
        $out.Add($l)
    }
    return $out
}
$subMap = @{}
if ($cfg.building_subsidies) {
    foreach ($p in $cfg.building_subsidies.PSObject.Properties) {
        $v = [string]$p.Value
        if ([string]::IsNullOrWhiteSpace($v) -or $v -eq 'vanilla') { continue }
        if ($v -ne 'none' -and $SUBSIDY_ENUM -notcontains $v) {
            throw "building_subsidies: '$($p.Name)' = '$v' is invalid (expected vanilla|none|nice_to_have|wants_to_have|must_have)"
        }
        $subMap[$p.Name] = $v
    }
}
# Read ai_strategy_default's OWN subsidies live from vanilla (we deliberately do NOT own that file - it is a
# single ~8790-line block covering the whole AI: wargoals, navy/army sizes, treaties, infamy, interest groups.
# Owning it to change one field would freeze all of that against every future patch). We only READ its trio so
# the restatement stays in sync automatically instead of being hardcoded here.
$SUBSIDY_TRIO = [ordered]@{}
$srcDef = Join-Path $Game 'common\ai_strategies\00_default_strategy.txt'
if (Test-Path -LiteralPath $srcDef) {
    $defLines = Get-Content -LiteralPath $srcDef
    $dBlk = New-Object System.Collections.Generic.List[string]; $dd = 0; $started = $false
    foreach ($l in $defLines) {
        if (-not $started) { if ($l -match '^ai_strategy_default\s*=\s*\{') { $started = $true } else { continue } }
        $dd += ([regex]::Matches($l,'\{')).Count - ([regex]::Matches($l,'\}')).Count
        $dBlk.Add($l)
        if ($started -and $dd -le 0) { break }
    }
    $SUBSIDY_TRIO = Get-SubsidyEntries $dBlk
}
if ($SUBSIDY_TRIO.Count -eq 0) {
    Write-Output "note: could not read ai_strategy_default's subsidies from vanilla - typed strategies will carry only their own entries + our overrides"
}
$relAI    = 'common\ai_strategies\01_admin_strategies.txt'
$srcAI    = Join-Path $Game $relAI
if (-not (Test-Path -LiteralPath $srcAI)) {
    Write-Output "note: $relAI not found in game - skipping AI subsidy emission (subsidy policy will stay vanilla)"
} else {
    $aiLines = Get-Content -LiteralPath $srcAI
    $aOut = New-Object System.Collections.Generic.List[string]
    $aOut.Add($genHeader.TrimEnd())
    $touched = 0; $i = 0
    while ($i -lt $aiLines.Count) {
        $line = $aiLines[$i]
        if ($line -match '^(ai_strategy_[A-Za-z0-9_]+)\s*=\s*\{') {
            $blk = New-Object System.Collections.Generic.List[string]; $depth = 0
            do {
                $l = $aiLines[$i]
                $depth += ([regex]::Matches($l,'\{')).Count - ([regex]::Matches($l,'\}')).Count
                $blk.Add($l); $i++
            } while ($i -lt $aiLines.Count -and $depth -gt 0)
            # only administrative strategies carry economy policy; leave any other type verbatim
            if (($blk -join "`n") -match '(?m)^\s*type\s*=\s*administrative\s*$') {
                $hadBlock = Test-HasSubsidyBlock $blk
                $ent = Get-SubsidyEntries $blk                                   # this strategy's vanilla entries
                # Seed ai_strategy_default's entries ONLY into strategies that had NO subsidies block of their
                # own. A strategy that HAS one is authoritative: under REPLACE semantics whatever it omits was
                # omitted deliberately (vanilla fine-tuning), and under MERGE semantics the default supplies the
                # rest anyway - so restating there would invent subsidies vanilla never granted. A strategy with
                # NO block only becomes replace-exposed because WE add one, so there we must restate to keep
                # vanilla behaviour intact. Correct under both readings, and never overrides a tuned value.
                if (-not $hadBlock) {
                    foreach ($k in $SUBSIDY_TRIO.Keys) { if (-not $ent.Contains($k)) { $ent[$k] = $SUBSIDY_TRIO[$k] } }
                }
                foreach ($k in $subMap.Keys) {                                   # user overrides win
                    if ($subMap[$k] -eq 'none') { if ($ent.Contains($k)) { $ent.Remove($k) } }
                    else { $ent[$k] = $subMap[$k] }
                }
                $body = Remove-SubsidyBlock $blk
                $new  = New-Object System.Collections.Generic.List[string]
                $new.Add($body[0])                                               # strategy header
                $new.Add("`tsubsidies = {")
                foreach ($k in $ent.Keys) { $new.Add("`t`t$k = $($ent[$k])") }
                $new.Add("`t}")
                for ($j = 1; $j -lt $body.Count; $j++) { $new.Add($body[$j]) }
                foreach ($nl in $new) { $aOut.Add($nl) }
                $touched++
            } else { foreach ($bl in $blk) { $aOut.Add($bl) } }
        } else { $aOut.Add($line); $i++ }
    }
    WriteText "$modRel\$relAI" (($aOut -join "`n") + "`n") $bom
    $setList  = if ($subMap.Count) { ($subMap.Keys | Sort-Object | ForEach-Object { "$_=$($subMap[$_])" }) -join ', ' } else { '(none - vanilla policy)' }
    $trioList = if ($SUBSIDY_TRIO.Count) { ($SUBSIDY_TRIO.Keys | ForEach-Object { "$_=$($SUBSIDY_TRIO[$_])" }) -join ', ' } else { '(none)' }
    Write-Output "ai subsidies: rewrote $touched administrative strategies; overrides: $setList"
    Write-Output "ai subsidies: default-strategy trio read live from vanilla: $trioList"
}

# --- own EVERY production_methods file: two surgical transforms, everything else verbatim ---
#   (1) GATE REMAP: append our tier pm_key to each `unlocking_production_methods` list that references a
#       split vanilla main PM (map vanilla_pm -> pm_key), so gated secondaries (bone china, elastics,
#       precision tools) unlock at the right tier again (they were locked by the main-PM rename).
#   (2) GOODS OVERRIDE: for any PM in the config `pm_goods` map, overwrite its goods_input/output_*_add
#       quantities from config. Modifiers/employment/effects stay verbatim (display-only). This makes
#       EVERY PM's goods editable & emittable WITHOUT owning any building file — buildings reference PMs
#       by key, so all buildings pick up the edited goods. Default (no override) = verbatim copy.
# The BE linter reads vanilla + our zzz (not these owned copies), so it's unaffected. The negative-goods
# linter (lint_negative_goods.awk) DOES read these owned copies, so it checks pm_goods overrides.
$script:pmRemap = @{}
foreach ($ind in $cfg.industries) { if ($ind.disabled) { continue }; foreach ($t in $ind.tiers) { if ($t.vanilla_pm) { $script:pmRemap[$t.vanilla_pm] = $t.pm_key } } }
$gateEval = [System.Text.RegularExpressions.MatchEvaluator]{
    param($m)
    $toks = @([regex]::Matches($m.Groups[1].Value, 'pm_[A-Za-z0-9_-]+') | ForEach-Object { $_.Value })
    $adds = @()
    foreach ($tk in $toks) { if ($script:pmRemap.ContainsKey($tk)) { $mapped = $script:pmRemap[$tk]; if (($toks -notcontains $mapped) -and ($adds -notcontains $mapped)) { $adds += $mapped } } }
    if ($adds.Count -eq 0) { return $m.Value }
    "unlocking_production_methods = {`n" + ((@($toks) + $adds | ForEach-Object { "`t`t$_" }) -join "`n") + "`n`t}"
}
# goods-override lookup: pm -> @{ in=@{good=qty}; out=@{good=qty} }
$pmGoods = @{}
if ($cfg.pm_goods) { foreach ($p in $cfg.pm_goods.PSObject.Properties) {
    $ov = @{ in = @{}; out = @{} }
    if ($p.Value.in)  { foreach ($g in $p.Value.in.PSObject.Properties)  { $ov.in[$g.Name]  = [int]$g.Value } }
    if ($p.Value.out) { foreach ($g in $p.Value.out.PSObject.Properties) { $ov.out[$g.Name] = [int]$g.Value } }
    $pmGoods[$p.Name] = $ov
} }
foreach ($pf in (Get-ChildItem (Join-Path $Game 'common\production_methods') -Filter *.txt)) {
    $txt = [regex]::Replace([System.IO.File]::ReadAllText($pf.FullName), 'unlocking_production_methods\s*=\s*\{([^{}]*)\}', $gateEval)
    if ($pmGoods.Count -gt 0) {
        $lines = $txt -split "`r?`n"; $cur = $null
        for ($k = 0; $k -lt $lines.Count; $k++) {
            # PM headers are top-level (column 0) in a production_methods file; names are NOT all pm_-prefixed
            # (plantations/farms use default_/automatic_/worker_/… , e.g. default_building_cotton_plantation).
            if ($lines[$k] -match '^([A-Za-z_][A-Za-z0-9_-]*)\s*=\s*\{') { $cur = $Matches[1]; continue }
            if ($null -ne $cur -and $pmGoods.ContainsKey($cur)) {
                if ($lines[$k] -match '^(\s*)goods_input_([a-z_]+)_add\s*=')      { $g = $Matches[2]; if ($pmGoods[$cur].in.ContainsKey($g))  { $lines[$k] = "$($Matches[1])goods_input_${g}_add = $($pmGoods[$cur].in[$g])" } }
                elseif ($lines[$k] -match '^(\s*)goods_output_([a-z_]+)_add\s*=') { $g = $Matches[2]; if ($pmGoods[$cur].out.ContainsKey($g)) { $lines[$k] = "$($Matches[1])goods_output_${g}_add = $($pmGoods[$cur].out[$g])" } }
            }
        }
        $txt = $lines -join "`n"
    }
    WriteText "$modRel\common\production_methods\$($pf.Name)" $txt $bom
}

# --- localization for every language (UTF-8 WITH BOM), in a replace/ folder so our building-name
#     overrides win over vanilla (and new keys are still defined) ---
$base = $cfg.loc_basename
foreach ($lang in $cfg.languages) {
    $content = "l_${lang}:`n" + "# AUTO-GENERATED by tools/build.ps1 - do not edit by hand. English strings are used as stubs for all languages.`n" + (($locBody -join "`n")) + "`n"
    WriteText "$modRel\localization\$lang\replace\${base}_l_${lang}.yml" $content $bom
}

# --- self-diagnostic on_action (dev convention; see MODDING_NOTES → Self-diagnostics) -------------------
# Fires at game start. We only ADD an `on_actions = { }` reference to the vanilla on_action (its effect
# block is untouched - per common/on_actions/_on_actions.md), so it can't break vanilla game-start.
# Read the results in Documents/Paradox Interactive/Victoria 3/logs/debug.log (search PM_TECH_REHAUL);
# an absent init marker => the mod failed to load (check error.log). Add invariant tripwires inside
# pm_tech_rehaul_diag whenever a risky change might trip - log "PM_TECH_REHAUL WARN: ..." on failure.
$diagTs = Get-Date -Format 'yyyy-MM-dd HH:mm'
$diag = @(
    $genHeader.TrimEnd(), "",
    "on_game_started_after_lobby = {",
    "`ton_actions = { pm_tech_rehaul_diag }",
    "}", "",
    "pm_tech_rehaul_diag = {",
    "`teffect = {",
    "`t`tdebug_log = `"PM_TECH_REHAUL: init OK - mod loaded, game started (build $diagTs) on [TimeKeeper.GetCurrentDate.GetString]`"",
    "`t`t# --- invariant tripwires: add checks for risky changes; log PM_TECH_REHAUL WARN on failure ---",
    "`t}",
    "}"
)
WriteText "$modRel\common\on_actions\zzz_pm_rehaul_diag.txt" (($diag -join "`n") + "`n") $bom

# --- emit UI data (consumed by ui/builder.html) so the editor always reflects the latest config ---
# Only the canonical build repoints the UI; alternate builds (-DryRun/-SaveTo) leave ui/data.js alone.
if (-not $isAlt) {
    $uiData = "// AUTO-GENERATED by tools/build.ps1 - the balance UI reads this.`n" +
              "window.PMDATA = {`n  config: " + ($cfg | ConvertTo-Json -Depth 20) + ",`n  prices: " + ($prices | ConvertTo-Json) + "`n};`n"
    WriteText 'ui\data.js' $uiData $noBom
    # vanilla.js: full building/PMG/PM reference so the UI ALWAYS shows every building (regardless of
    # include_all_buildings, which only gates emission). Re-derived from the live game each build.
    & (Join-Path $PSScriptRoot 'extract_vanilla.ps1') -Repo $repo -Game $Game
}

# --- report ---
Write-Output ("Generated {0} tier buildings across {1} industries; localization in {2} languages." -f $summary.Count, $cfg.industries.Count, $cfg.languages.Count)
$summary | Format-Table -AutoSize | Out-String | Write-Output

# --- refresh the 1836 start baseline (inventory + version-drift check), then convert it ---
# extract_start rewrites the repo-tracked config/start_baseline.json; skip it for alternate targets
# (-DryRun/-SaveTo) so they only ever touch their own mod_* folder, never canonical repo files.
if (-not $isAlt) { & (Join-Path $PSScriptRoot 'extract_start.ps1') -Repo $repo -Config $cfgPath }
& (Join-Path $PSScriptRoot 'convert_history.ps1') -Repo $repo -Config $cfgPath -ModDir $modRel

if (-not $NoLint) {
    $bashPath = $null
    $cmd = Get-Command bash -ErrorAction SilentlyContinue
    if ($cmd) { $bashPath = $cmd.Source }
    else {
        foreach ($p in @("$env:ProgramFiles\Git\bin\bash.exe", "${env:ProgramFiles(x86)}\Git\bin\bash.exe", "$env:LOCALAPPDATA\Programs\Git\bin\bash.exe")) {
            if (Test-Path $p) { $bashPath = $p; break }
        }
    }
    if ($bashPath) {
        Write-Output "Running linter..."
        $env:PM_MOD_DIR = $modRel      # tell lint.sh which mod folder to read (default 'mod')
        $env:PM_LADDER  = $ladderPath  # ...and which tier map to lint against (temp copy for alt builds)
        try { & $bashPath (Join-Path $repo 'tools/lint.sh') }
        finally { Remove-Item Env:\PM_MOD_DIR, Env:\PM_LADDER -ErrorAction SilentlyContinue }
    } else {
        Write-Output "bash (Git Bash) not found - run the linter separately:  bash tools/lint.sh"
    }
}
# alt builds used a throwaway ladder in TEMP; remove it now that the linter is done with it.
if ($isAlt -and $ladderPath -and (Test-Path $ladderPath)) { Remove-Item $ladderPath -Force -ErrorAction SilentlyContinue }

# --- stamp the build time into the mod NAME so it's obvious in the launcher which build is loaded ---
$metaPath = Join-Path $modAbs '.metadata\metadata.json'
$ts = Get-Date -Format 'yyyy-MM-dd HH:mm'
$meta = Get-Content $metaPath -Raw
$meta = [regex]::Replace($meta, '("name"\s*:\s*"[^"]*?)\s*\(built[^)]*\)(")', '${1}${2}')          # strip any prior "(built ...)"
$meta = [regex]::Replace($meta, '("name"\s*:\s*"[^"]*)(")', ('${1} (built ' + $ts + ')${2}'))       # append fresh timestamp
[System.IO.File]::WriteAllText($metaPath, $meta, $noBom)
Write-Output "Build timestamp: $ts (mod name)"

# --- post-build checks on the FINISHED mod (the dry-run guarantee; also guards deploy) ---
$problems = Invoke-ModChecks $modAbs $cfg
if ($problems.Count -gt 0) {
    Write-Output "MOD CHECKS FAILED for ${modRel}:"
    $problems | ForEach-Object { Write-Output "  - $_" }
    if ($DryRun) { Remove-Item $modAbs -Recurse -Force -ErrorAction SilentlyContinue; Write-Output "Dry-run folder deleted." }
    throw "Post-build mod checks failed ($($problems.Count) problem(s))."
}
Write-Output "MOD CHECKS PASSED: $modRel is a complete build."

# --- dry run: we proved a full build works; delete the throwaway folder and stop (never deploy) ---
if ($DryRun) {
    Remove-Item $modAbs -Recurse -Force
    Write-Output "DRY RUN OK: built + checked $modRel, then deleted it. Canonical mod/ untouched."
    return
}
# --- alternate save target: keep it, but never deploy (only the canonical mod/ deploys) ---
if ($SaveTo) {
    Write-Output "Saved alternate build -> $modRel (not deployed)."
    return
}

# --- deploy: mirror mod/ into the Paradox mod folder as a REAL copy ---
# The Paradox launcher does not traverse directory junctions (it reports the mod as ~48 bytes),
# so we deploy an actual copy. build.ps1 re-mirrors on every build, keeping iteration one command.
if (-not $NoDeploy) {
    $src  = Join-Path $repo 'mod'
    $dest = Join-Path $env:USERPROFILE 'Documents\Paradox Interactive\Victoria 3\mod\pm_tech_rehaul'
    if (Test-Path $dest) {
        $di = Get-Item $dest -Force
        if ($di.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
            [System.IO.Directory]::Delete($dest, $false)   # remove old junction; write real files instead
        }
    }
    & robocopy $src $dest /MIR /NFL /NDL /NJH /NJS /NP /R:1 /W:1 | Out-Null
    $rc = $LASTEXITCODE; $global:LASTEXITCODE = 0
    if ($rc -ge 8) { Write-Warning "Deploy: robocopy reported errors (exit $rc)" }
    else { Write-Output "Deployed real copy -> $dest" }
}
