<#
  PM & Tech Rehaul - mod builder.

  Reads config/mod_config.json and generates the whole mod:
    mod/common/buildings/zzz_pm_rehaul_01_industry.txt
    mod/common/production_methods/zzz_pm_rehaul_01_industry.txt
    mod/common/production_method_groups/zzz_pm_rehaul_01_industry.txt
    mod/localization/<lang>/zzz_pm_rehaul_l_<lang>.yml   (ALL configured languages)
    tools/ladder_tiers.txt                               (linter tier map, derived from config)

  Building logic: per tier you specify intent (target_be, output_qty, input composition,
  employment). The builder solves input quantities so break-even = target_be at base prices,
  writes output_qty as-is, and preserves employment/pollution.

  Usage:   powershell -ExecutionPolicy Bypass -File tools\build.ps1 [-NoLint]
#>
param([switch]$NoLint, [switch]$NoDeploy)
$ErrorActionPreference = 'Stop'
$INV = [System.Globalization.CultureInfo]::InvariantCulture
function Fmt($v) { return ([double]$v).ToString($INV) }   # locale-safe number -> string
function RoundHalfUp($x) { return [int][math]::Floor([double]$x + 0.5) }

$repo = Split-Path $PSScriptRoot -Parent
$genHeader = "# AUTO-GENERATED by tools/build.ps1 from config/mod_config.json - do not edit by hand.`n"

# --- load prices ---
$prices = @{}
foreach ($line in (Get-Content (Join-Path $repo 'tools\goods_prices.tsv'))) {
    if ($line -match '^\s*#' -or $line.Trim() -eq '') { continue }
    $c = $line -split "`t"
    if ($c.Count -ge 2) { $prices[$c[0].Trim()] = [double]$c[1].Trim() }
}

# --- load config ---
$cfg = Get-Content (Join-Path $repo 'config\mod_config.json') -Raw | ConvertFrom-Json
$Game = $(if ($env:VIC3_GAME) { $env:VIC3_GAME } else { "C:\Program Files (x86)\Steam\steamapps\common\Victoria 3\game" })

# --- clean previously generated outputs (keep .metadata + history, which the converter rewrites) ---
foreach ($d in 'mod\common\buildings', 'mod\common\production_methods', 'mod\common\production_method_groups') {
    $p = Join-Path $repo $d
    if (Test-Path $p) { Remove-Item (Join-Path $p '*') -Force -Recurse -ErrorAction SilentlyContinue }
}
$locRoot = Join-Path $repo 'mod\localization'
if (Test-Path $locRoot) { Remove-Item $locRoot -Recurse -Force -ErrorAction SilentlyContinue }

$pmOut = @($genHeader); $pmgOut = @($genHeader)
$genByBase = @{}        # base building key -> generated text for that whole industry (base + tiers)
$locBody = @()          # localization entries (identical across languages)
$tierMap = @('# MAIN production method -> tier (1-based). AUTO-GENERATED by build.ps1.')
$summary = @()
$D = [char]36           # literal '$' for loc interpolation

foreach ($ind in $cfg.industries) {
    if ($ind.disabled) { continue }   # leave vanilla (no split); config keeps the data for later
    $tierNo = 0
    $indBld = @()
    foreach ($t in $ind.tiers) {
        $tierNo++

        # inputs/output_qty are actual volumes; the builder emits them directly.
        $outGood = if ($t.output_good) { $t.output_good } else { $ind.output_good }
        $Oval = [double]$t.output_qty * $prices[$outGood]

        # ---- PM ----
        $pm = @("$($t.pm_key) = {", "`ttexture = `"$($t.texture)`"")
        if ([double]$t.pollution -gt 0) {
            $pm += "`tstate_modifiers = {","`t`tworkforce_scaled = {","`t`t`tstate_pollution_generation_add = $([int]$t.pollution)","`t`t}","`t}"
        }
        $pm += "`tbuilding_modifiers = {","`t`tworkforce_scaled = {"
        $actualI = 0.0
        foreach ($p in $t.inputs.PSObject.Properties) {
            $q = [int]$p.Value
            $actualI += $q * $prices[$p.Name]
            $pm += "`t`t`tgoods_input_$($p.Name)_add = $q"
        }
        $pm += "`t`t`tgoods_output_$($outGood)_add = $([int]$t.output_qty)","`t`t}","`t`tlevel_scaled = {"
        foreach ($e in $t.employment.PSObject.Properties) { $pm += "`t`t`tbuilding_employment_$($e.Name)_add = $([int]$e.Value)" }
        $pm += "`t`t}","`t}"
        if ($null -ne $t.required_input_goods) { $pm += "`trequired_input_goods = $($t.required_input_goods)" }
        $pm += "}",""
        $pmOut += $pm

        # ---- PMG (single main PM) ----
        $pmgOut += "$($t.pmg_key) = {","`ttexture = `"gfx/interface/icons/generic_icons/mixed_icon_base.dds`"","`tproduction_methods = { $($t.pm_key) }","}",""

        # ---- Building ----
        $b = $ind.building
        $bl = @("$($t.key) = {")
        # aliases (vanilla plural keys) belong ONLY to the tier-1 base building, which reuses
        # the vanilla key; putting them on higher tiers would be a duplicate-alias conflict.
        if ($null -ne $b.aliases -and $tierNo -eq 1) { $bl += "`taliases = { $($b.aliases -join ' ') }" }
        $bl += "`tbuilding_group = $($b.building_group)","`ticon = `"$($b.icon)`"","`tcity_type = $($b.city_type)","`tlevels_per_mesh = $([int]$b.levels_per_mesh)"
        if ($null -ne $b.ai_nationalization_desire) { $bl += "`tai_nationalization_desire = $(Fmt $b.ai_nationalization_desire)" }
        $bl += "`tunlocking_technologies = { $($t.tech) }","`tproduction_method_groups = {","`t`t$($t.pmg_key)"
        foreach ($s in $ind.secondary_pmgs) { $bl += "`t`t$s" }
        $bl += "`t}","`trequired_construction = $($b.required_construction)"
        if ($b.heavy_industry_law) { $bl += "`tpossible = {","`t`towner = {","`t`t`tNOT = {","`t`t`t`tOR = {","`t`t`t`t`thas_law_or_variant = law_type:law_industry_banned","`t`t`t`t`thas_law_or_variant = law_type:law_extraction_economy","`t`t`t`t}","`t`t`t}","`t`t}","`t}" }
        if ($b.coastal_only) { $bl += "`tpotential = {","`t`tis_coastal = yes","`t}" }
        if ($null -ne $b.ai_value) { $bl += "`tai_value = $([int]$b.ai_value)" }
        $bl += "`townership_type = $($b.ownership_type)","`tbackground = `"$($b.background)`"","}",""
        $indBld += $bl

        # ---- localization (shared body) ----
        $locBody += " $($t.key):0 `"$($t.name)`""
        $locBody += " $($t.key)_lens_option:0 `"Expand $D$($t.key)$D`""
        $locBody += " $($t.pmg_key):0 `"$($t.pm_name)`""
        $locBody += " $($t.pm_key):0 `"$($t.pm_name)`""

        # ---- tier map + summary ----
        $tierMap += "$($t.pm_key) $tierNo $($t.target_be)"
        $actualBe = if ($Oval -gt 0) { $actualI / $Oval * 100 } else { 0 }
        $summary += [pscustomobject]@{ Building=$t.key; Tier=$tierNo; TargetBE=$t.target_be; ActualBE=[math]::Round($actualBe) }
    }
    $genByBase[$ind.tiers[0].key] = ($indBld -join "`n")   # keyed by the vanilla base building key
}

# --- write files ---
$noBom = New-Object System.Text.UTF8Encoding($false)   # tool files (ladder_tiers)
$bom   = New-Object System.Text.UTF8Encoding($true)    # game content (common/*, localization) - matches vanilla
function WriteText($rel, $text, $enc) {
    $path = Join-Path $repo $rel
    $dir = Split-Path $path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    [System.IO.File]::WriteAllText($path, $text, $enc)
}
WriteText 'mod\common\production_methods\zzz_pm_rehaul_01_industry.txt'        (($pmOut  -join "`n") + "`n") $bom
WriteText 'mod\common\production_method_groups\zzz_pm_rehaul_01_industry.txt'  (($pmgOut -join "`n") + "`n") $bom
WriteText 'tools\ladder_tiers.txt'                                            (($tierMap -join "`n") + "`n") $noBom

# --- buildings: REPLACE vanilla common/buildings/01_industry.txt (same filename) ---
# V3 rejects a redefined building key that comes from a different file, so the mod must OWN the
# whole file: copy vanilla's 01_industry.txt, swap each split-industry base building block for our
# (base + tier) set, and keep the other (heavy/military) buildings verbatim.
$vanLines = Get-Content -LiteralPath (Join-Path $Game 'common\buildings\01_industry.txt')
$bOut = New-Object System.Collections.Generic.List[string]
$bOut.Add($genHeader.TrimEnd())
$emitted = @{}; $i = 0
while ($i -lt $vanLines.Count) {
    $line = $vanLines[$i]
    if ($line -match '^(building_[A-Za-z0-9_]+)\s*=\s*\{') {
        $bkey = $Matches[1]
        $blk = New-Object System.Collections.Generic.List[string]; $depth = 0
        do {
            $l = $vanLines[$i]
            $depth += ([regex]::Matches($l, '\{')).Count - ([regex]::Matches($l, '\}')).Count
            $blk.Add($l); $i++
        } while ($i -lt $vanLines.Count -and $depth -gt 0)
        if ($genByBase.ContainsKey($bkey)) { $bOut.Add($genByBase[$bkey]); $emitted[$bkey] = $true }
        else { foreach ($bl2 in $blk) { $bOut.Add($bl2) } }
    } else { $bOut.Add($line); $i++ }
}
foreach ($bk in $genByBase.Keys) { if (-not $emitted.ContainsKey($bk)) { Write-Warning "base building $bk not in vanilla 01_industry.txt; appending"; $bOut.Add($genByBase[$bk]) } }
WriteText 'mod\common\buildings\01_industry.txt' (($bOut -join "`n") + "`n") $bom

# --- localization for every language (UTF-8 WITH BOM), in a replace/ folder so our building-name
#     overrides win over vanilla (and new keys are still defined) ---
$base = $cfg.loc_basename
foreach ($lang in $cfg.languages) {
    $content = "l_${lang}:`n" + "# AUTO-GENERATED by tools/build.ps1 - do not edit by hand. English strings are used as stubs for all languages.`n" + (($locBody -join "`n")) + "`n"
    WriteText "mod\localization\$lang\replace\${base}_l_${lang}.yml" $content $bom
}

# --- emit UI data (consumed by ui/builder.html) so the editor always reflects the latest config ---
$uiData = "// AUTO-GENERATED by tools/build.ps1 - the balance UI reads this.`n" +
          "window.PMDATA = {`n  config: " + ($cfg | ConvertTo-Json -Depth 20) + ",`n  prices: " + ($prices | ConvertTo-Json) + "`n};`n"
WriteText 'ui\data.js' $uiData $noBom

# --- report ---
Write-Output ("Generated {0} tier buildings across {1} industries; localization in {2} languages." -f $summary.Count, $cfg.industries.Count, $cfg.languages.Count)
$summary | Format-Table -AutoSize | Out-String | Write-Output

# --- refresh the 1836 start baseline (inventory + version-drift check), then convert it ---
& (Join-Path $PSScriptRoot 'extract_start.ps1') -Repo $repo
& (Join-Path $PSScriptRoot 'convert_history.ps1') -Repo $repo

if (-not $NoLint) {
    $bashPath = $null
    $cmd = Get-Command bash -ErrorAction SilentlyContinue
    if ($cmd) { $bashPath = $cmd.Source }
    else {
        foreach ($p in @("$env:ProgramFiles\Git\bin\bash.exe", "${env:ProgramFiles(x86)}\Git\bin\bash.exe", "$env:LOCALAPPDATA\Programs\Git\bin\bash.exe")) {
            if (Test-Path $p) { $bashPath = $p; break }
        }
    }
    if ($bashPath) {
        Write-Output "Running linter..."
        & $bashPath (Join-Path $repo 'tools/lint.sh')
    } else {
        Write-Output "bash (Git Bash) not found - run the linter separately:  bash tools/lint.sh"
    }
}

# --- deploy: mirror mod/ into the Paradox mod folder as a REAL copy ---
# The Paradox launcher does not traverse directory junctions (it reports the mod as ~48 bytes),
# so we deploy an actual copy. build.ps1 re-mirrors on every build, keeping iteration one command.
if (-not $NoDeploy) {
    $src  = Join-Path $repo 'mod'
    $dest = Join-Path $env:USERPROFILE 'Documents\Paradox Interactive\Victoria 3\mod\pm_tech_rehaul'
    if (Test-Path $dest) {
        $di = Get-Item $dest -Force
        if ($di.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
            [System.IO.Directory]::Delete($dest, $false)   # remove old junction; write real files instead
        }
    }
    & robocopy $src $dest /MIR /NFL /NDL /NJH /NJS /NP /R:1 /W:1 | Out-Null
    $rc = $LASTEXITCODE; $global:LASTEXITCODE = 0
    if ($rc -ge 8) { Write-Warning "Deploy: robocopy reported errors (exit $rc)" }
    else { Write-Output "Deployed real copy -> $dest" }
}
