// THE 1836 WORKFORCE OF THE CRAFT RUNGS, IN THE RIGHT PROFESSIONS (BALANCE_FRAMEWORK §10.91.1 item 6, user-ruled 2026-09-30:
// "We also need to remember to convert the converted factories' workforce into correct professions as well, that's a must" and
// "Don't forget to tune 1836 workers to recipes").
//
//   node tools/emit_craft_pops.mjs <modRoot> [configPath]        # called by tools/build.ps1, AFTER convert_history + emit_secondaries
//
// WHY. Vanilla's 1836 pops are almost all UNTYPED (`create_pop = { culture = X size = N }`; of 4,454 blocks the typed ones are slaves
// and a few elites), and the engine hands them to the jobs it finds at game start. A craft rung employs 30–50% machinists in the ruled
// staffing, and machinists can only be recruited from pops above 10% literacy — while the crafts stand mostly in China, Russia, India,
// Austria and the Ottoman lands (FINDINGS F180 §2: vanilla China has 31,831 machinists in 1837; its crafts need ~392k). So the pops
// that WORK in the converted factories are converted into their professions in the history itself.
//
// WHAT. For every state holding craft levels on the emitted 1836 map (history/buildings, after the ×10 conversion), per region_state:
//   workforce(p) = Σ over its craft buildings of levels × (base employment × workforce_mult + the active secondaries' employment)
// for every profession but laborers (the untyped remainder fills the laborer slots as it always did), and pop size = workforce ÷
// WORKING_ADULT_RATIO_BASE (0.25, read from the defines). That many people are CARVED out of the state's own untyped pops — the largest
// simple block first (same culture, same religion), never more than 90% of a block — into typed blocks. POPULATION IS UNCHANGED.
//
// HOW IT SHIPS. The vanilla pops files that contain such a state are copied WHOLE into <mod>/common/history/pops/ under their own names
// (a same-path file shadows vanilla's), with exactly those size lines changed and those typed blocks added; every other byte is
// vanilla's. Files without a craft state are not emitted. ⚠ build.ps1 never wipes common/history, so a book without crafts REMOVES any
// file this tool wrote earlier (recognised by its header), or a canon build would keep an earlier craft book's pops.
//
// THROWS on: a craft building in a state/region_state the pops history does not define; not enough untyped pops to carve; a history
// block whose levels cannot be read; a secondary method whose employment is unknown.
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const GAME = process.env.VIC3_GAME || 'C:/Program Files (x86)/Steam/steamapps/common/Victoria 3/game';
const MOD = process.argv[2];
if (!MOD) { console.error('usage: node tools/emit_craft_pops.mjs <modRoot> [configPath]'); process.exit(2); }
const CFGP = process.argv[3] || join(REPO, 'config/mod_config.json');
const CFG = JSON.parse(readFileSync(CFGP, 'utf8').replace(/^\uFEFF/, ''));
const die = m => { throw new Error('emit_craft_pops: ' + m); };
const rd = p => readFileSync(p, 'utf8').replace(/^\uFEFF/, '');
const MARK = '# GENERATED by tools/emit_craft_pops.mjs';
const POPDIR = join(MOD, 'common/history/pops');

// ---- craft rungs in this book
const CRAFT = {};
for (const ind of CFG.industries || []) { if (ind.disabled) continue; for (const t of ind.tiers || []) if (t.craft) CRAFT[t.key] = { ind, t }; }

// ---- stale output from an earlier book goes first, whatever this book does
let removed = 0;
if (existsSync(POPDIR)) for (const f of readdirSync(POPDIR)) {
  const p = join(POPDIR, f);
  try { if (rd(p).startsWith(MARK)) { unlinkSync(p); removed++; } } catch { /* not ours */ }
}
if (!Object.keys(CRAFT).length) {
  console.log(`craft pops: no craft rungs in this book - nothing emitted${removed ? `; removed ${removed} stale file(s) an earlier craft book left` : ''}`);
  process.exit(0);
}

// ---- the working-adult ratio the engine uses for a fresh pop (defines)
let WAR = 0.25;
{ const m = /WORKING_ADULT_RATIO_BASE\s*=\s*([0-9.]+)/.exec(rd(join(GAME, 'common/defines/00_defines.txt'))); if (m) WAR = +m[1]; }

// ---- employment per level of every method a craft building can name: the emitted per-rung secondaries first, vanilla second
const blocksOf = t => { const o = {}; const re = /^([A-Za-z_0-9-]+)\s*=\s*\{/gm; let m;
  while ((m = re.exec(t))) { let i = re.lastIndex, d = 1; while (i < t.length && d > 0) { if (t[i] === '{') d++; else if (t[i] === '}') d--; i++; } o[m[1]] = t.slice(re.lastIndex, i - 1); re.lastIndex = i; }
  return o; };
const PMB = {};
for (const f of readdirSync(join(GAME, 'common/production_methods'))) Object.assign(PMB, blocksOf(rd(join(GAME, 'common/production_methods', f))));
{ const own = join(MOD, 'common/production_methods'); if (existsSync(own)) for (const f of readdirSync(own)) Object.assign(PMB, blocksOf(rd(join(own, f)))); }
const empOf = pm => { const b = PMB[pm]; if (b == null) return null; const e = {};
  for (const m of b.matchAll(/building_employment_([a-z_]+)_add\s*=\s*(-?[0-9.]+)/g)) e[m[1]] = (e[m[1]] || 0) + +m[2];
  return e; };

// ---- a brace walker that reports every block with its path of named ancestors
function walk(text, onBlock) {
  const stack = []; const re = /([A-Za-z_0-9:.\-]+)\s*=\s*\{|\{|\}|#[^\n]*/g; let m;
  while ((m = re.exec(text))) {
    if (m[0][0] === '#') continue;
    if (m[0] === '}') { const b = stack.pop(); if (b && b.name) onBlock(b, stack, m.index + 1); continue; }
    stack.push({ name: m[1] || null, start: m.index, open: re.lastIndex });
  }
  if (stack.length) die('unbalanced braces');
}
const ctx = stack => {
  let st = null, tag = null;
  for (const b of stack) { if (b.name && b.name.startsWith('s:')) st = b.name.slice(2); if (b.name && b.name.startsWith('region_state:')) tag = b.name.slice(13); }
  return { st, tag };
};

// ---- 1. the craft workforce per (state, region_state), from the EMITTED 1836 map
const need = new Map();   // "STATE|TAG" -> { prof: workforce }
const perCountry = {};
let craftBlocks = 0, craftLevels = 0;
const HB = join(MOD, 'common/history/buildings');
if (!existsSync(HB)) die(`no emitted history at ${HB} — run after convert_history`);
for (const f of readdirSync(HB).filter(x => x.endsWith('.txt'))) {
  const text = rd(join(HB, f));
  walk(text, (b, stack, end) => {
    if (b.name !== 'create_building') return;
    const body = text.slice(b.open, end - 1);
    const km = /building\s*=\s*"([a-z_0-9-]+)"/.exec(body); if (!km || !CRAFT[km[1]]) return;
    const { st, tag } = ctx(stack); if (!st || !tag) die(`${f}: a ${km[1]} block outside s:/region_state:`);
    // a building's level is the sum of its ownership entries' levels (after convert_history's ×10)
    let levels = 0; for (const lm of body.matchAll(/levels\s*=\s*(\d+)/g)) levels += +lm[1];
    if (!(levels > 0)) die(`${f}: ${km[1]} in ${st}/${tag} has no readable levels`);
    const { t } = CRAFT[km[1]]; const wm = +t.workforce_mult || 1;
    const e = {}; for (const [p, n] of Object.entries(t.employment || {})) e[p] = (e[p] || 0) + n * wm;
    const act = /activate_production_methods\s*=\s*\{([^}]*)\}/.exec(body);
    for (const pm of (act ? act[1].match(/"([^"]+)"/g) || [] : []).map(s => s.slice(1, -1))) {
      if (pm === t.pm_key) continue;
      const se = empOf(pm); if (se == null) die(`${f}: ${km[1]} in ${st} activates ${pm}, whose employment is unknown`);
      for (const [p, n] of Object.entries(se)) e[p] = (e[p] || 0) + n;
    }
    const k = st + '|' + tag; const acc = need.get(k) || {}; need.set(k, acc);
    for (const [p, n] of Object.entries(e)) if (p !== 'laborers' && n > 0) acc[p] = (acc[p] || 0) + n * levels;
    craftBlocks++; craftLevels += levels;
  });
}

// ---- 2. carve typed pops out of the vanilla pops history
const VP = join(GAME, 'common/history/pops');
const done = new Set();
const typedTotal = {};
for (const f of readdirSync(VP).filter(x => x.endsWith('.txt'))) {
  const raw = readFileSync(join(VP, f), 'utf8');
  const bom = raw.charCodeAt(0) === 0xFEFF ? '\uFEFF' : ''; const text = bom ? raw.slice(1) : raw;
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const donors = new Map();   // "STATE|TAG" -> [{ start, end, sizeAt, sizeLen, size, culture, religion, indent }]
  const closeOf = new Map();  // "STATE|TAG" -> the region_state block's closing-brace offset
  walk(text, (b, stack, end) => {
    if (b.name && b.name.startsWith('region_state:')) {
      const { st } = ctx(stack); const tag = b.name.slice(13);
      if (st) closeOf.set(st + '|' + tag, end - 1);
      return;
    }
    if (b.name !== 'create_pop') return;
    const { st, tag } = ctx(stack); if (!st || !tag) return;
    const body = text.slice(b.open, end - 1);
    const code = body.replace(/#[^\n]*/g, '');
    if (/pop_type|cultures|split_religion|split_culture/.test(code)) return;   // only simple untyped blocks donate
    const cm = /culture\s*=\s*([a-z_0-9]+)/.exec(code); const sm = /size\s*=\s*(\d+)/.exec(code);
    if (!cm || !sm) return;
    const rm = /religion\s*=\s*([a-z_0-9]+)/.exec(code);
    // the size number's absolute offset (the first `size =` in the raw body, comments included, matches the code's)
    const rs = /size\s*=\s*(\d+)/.exec(body);
    const ind = (text.slice(text.lastIndexOf('\n', b.start) + 1, b.start).match(/^\s*/) || [''])[0];
    const k = st + '|' + tag; const arr = donors.get(k) || []; donors.set(k, arr);
    arr.push({ end, sizeAt: b.open + rs.index + rs[0].length - rs[1].length, sizeLen: rs[1].length, size: +sm[1], culture: cm[1], religion: rm ? rm[1] : null, indent: ind });
  });
  const edits = [];   // { at, del, ins }
  for (const [k, prof] of need) {
    if (done.has(k) || !closeOf.has(k)) continue;
    const arr = (donors.get(k) || []).slice().sort((a, b) => b.size - a.size);
    const left = new Map(arr.map(d => [d, d.size]));
    const adds = [];   // typed blocks, keyed per donor
    for (const [p, wf] of Object.entries(prof).sort()) {
      let people = Math.round(wf / WAR);
      for (const d of arr) {
        if (people <= 0) break;
        const cap = Math.floor(d.size * 0.9) - (d.size - left.get(d));
        const take = Math.min(people, Math.max(0, cap));
        if (take <= 0) continue;
        left.set(d, left.get(d) - take); people -= take;
        adds.push({ d, p, n: take });
        typedTotal[k.split('|')[1]] = typedTotal[k.split('|')[1]] || {};
        typedTotal[k.split('|')[1]][p] = (typedTotal[k.split('|')[1]][p] || 0) + take;
      }
      if (people > 0) die(`${k}: not enough untyped pops to carve ${Math.round(wf / WAR)} ${p} (short by ${people})`);
    }
    for (const d of arr) if (left.get(d) !== d.size) edits.push({ at: d.sizeAt, del: d.sizeLen, ins: String(left.get(d)) });
    for (const d of arr) {
      const mine = adds.filter(a => a.d === d); if (!mine.length) continue;
      const ins = mine.map(a => `${eol}${d.indent}create_pop = { pop_type = ${a.p} culture = ${d.culture}${d.religion ? ` religion = ${d.religion}` : ''} size = ${a.n} }   # craft rung workforce (emit_craft_pops)`).join('');
      edits.push({ at: d.end, del: 0, ins });
    }
    done.add(k);
  }
  if (!edits.length) continue;
  edits.sort((a, b) => b.at - a.at);
  let out = text;
  for (const e of edits) out = out.slice(0, e.at) + e.ins + out.slice(e.at + e.del);
  mkdirSync(POPDIR, { recursive: true });
  writeFileSync(join(POPDIR, f), bom + MARK + ` from vanilla common/history/pops/${f} (config ${CFGP.replace(/\\/g, '/').split('/').pop()}): craft-rung workforce carved into typed pops. Do not hand-edit.${eol}` + out, 'utf8');
}
const missing = [...need.keys()].filter(k => !done.has(k));
if (missing.length) die(`${missing.length} craft state(s) have no region_state block in the pops history: ${missing.slice(0, 8).join(', ')}`);

const sumP = o => Object.values(o).reduce((a, b) => a + b, 0);
const byTag = Object.entries(typedTotal).sort((a, b) => sumP(b[1]) - sumP(a[1]));
const tot = {}; for (const [, o] of byTag) for (const [p, n] of Object.entries(o)) tot[p] = (tot[p] || 0) + n;
console.log(`craft pops: ${craftBlocks} craft building(s), ${craftLevels} levels in ${need.size} state(s); typed ` +
  Object.entries(tot).map(([p, n]) => `${p} ${n.toLocaleString('en-US')}`).join(', ') + ` people (workforce ÷ ${WAR}); ` +
  `top: ${byTag.slice(0, 6).map(([t, o]) => `${t} ${Math.round(sumP(o) / 1000)}k`).join(', ')}${removed ? `; removed ${removed} stale file(s)` : ''}`);
