// EMIT THE INDUSTRY TECH TREE into a built mod (ROADMAP step 1).
//
//   node tools/emit_techs.mjs <modRoot>        # called by tools/build.ps1
//
// Reads config/tech_tree_options.json (generated by tools/tech_tree_spec.mjs) and writes the option
// marked `ships`. Nothing here decides design — that file does.
//
// ⚠⚠ EVERY VANILLA TRANSFORM BELOW **THROWS** WHEN ITS ANCHOR IS NOT FOUND. A silent no-op is the exact
// failure mode this project's landmine register exists for: the build succeeds, the mod loads, the game
// runs, and the change simply is not there. There is no "warn and continue" path on purpose.
//
// What gets written, and why each is the kind of file it is:
//   ADDITIVE (new keys, new filename — touches no vanilla file)
//     common/technology/technologies/zzz_pm_rehaul_techs.txt
//     common/defines/01_pm_rehaul_defines.txt          (defines are the one folder taking partials)
//     gfx/interface/icons/invention_icons/zzz_pm_rehaul_placeholder.dds
//     localization/<lang>/replace/zzz_pm_rehaul_tech_l_<lang>.yml
//   WHOLE-FILE, REGENERATED FROM VANILLA EACH BUILD (so a patch flows through, nothing is frozen)
//     common/technology/technologies/10_production.txt  — era moves + one prerequisite swap
//     common/technology/technologies/20_military.txt    — era moves (only when there are any)
//     common/technology/technologies/30_society.txt     — ai_weight x0.8 on every society technology
//     common/scripted_effects/00_starting_inventions.txt— new era-1 techs into the 1836 starting sets
//     common/static_modifiers/00_code_static_modifiers.txt — the production-only tech spread multiplier
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const GAME = 'C:/Program Files (x86)/Steam/steamapps/common/Victoria 3/game';
const MOD = process.argv[2];
if (!MOD) { console.error('usage: node tools/emit_techs.mjs <modRoot> [configPath]'); process.exit(2); }
// ⚠⚠ THE CONFIG PATH IS AN ARGUMENT, AND IT USED TO BE HARDCODED — see emit_research_events.mjs for the
// full story. Here the consequence is the sharper one: an alternate-config build emitted that config's
// BUILDINGS but the canonical config's TECHNOLOGIES, so a tier present only in the alternate got no
// unlocking technology (a building nobody can ever construct) and a tier present only in the canonical
// got a technology unlocking a building that does not exist (an engine error at load).
const CFGPATH = process.argv[3] || join(REPO, 'config', 'mod_config.json');

// the tree follows the config, same suffix rule as every other derived artifact
const SFX = (() => {
  const raw = process.env.MOD_CONFIG || process.argv[3] || '';
  const bn = raw.split('\\').join('/').split('/').pop();
  const m = bn.match(/^mod_config\.(.+)\.json$/);
  return m ? '.' + m[1] : '';
})();
const TREE_PATH = join(REPO, 'config', 'tech_tree_options' + SFX + '.json');
const DATA = JSON.parse(readFileSync(TREE_PATH, 'utf8'));
const OPT = DATA.options.find(o => o.ships);
if (!OPT) throw new Error('no option is marked `ships` in config/tech_tree_options.json');
const CFG = JSON.parse(readFileSync(CFGPATH, 'utf8'));

// ⚠⚠ COVERAGE GUARD. `build.ps1` calls THIS file but never `tech_tree_spec.mjs`, so the tree data is not
// regenerated by a build and can fall behind the config it was derived from. Editing a recipe in the
// balance UI is harmless — each tier's `tech` lives in the config and the builder reads it directly — but
// ADDING a tier there produces a building no technology unlocks, and nothing would say so.
// ⚠ IT USED TO COMPARE MTIMES, AND THAT WAS BOTH TOO WEAK AND TOO STRONG. Too weak because a tree
// regenerated after an unrelated edit passes while still missing a tier; too strong because ANY config
// touched later trips it — an alternate config that differs only in a threshold was blocked outright,
// which is a false positive on the exact path that config exists for. It now checks the thing it cares
// about: every tier this build will EMIT must name a technology the shipping tree actually contains.
// ⚠ AND A TIER WITH NO TECHNOLOGY AT ALL IS NOT AN ERROR — that is how a building is made available from
// the 1836 start, which is exactly right for the pre-industrial era-0 rungs and for the vanilla basic
// port. The first version of this check threw on all ten of them. Only a tier that NAMES a technology
// can be wrong about it, so that is what throws; the start-available ones are counted and reported, so
// an accidental one is visible without blocking a legitimate build.
{
  const known = new Set(OPT.techs.map(t => t.id));
  const unknown = [], startAvail = [];
  for (const ind of CFG.industries || []) {
    if (ind.disabled) continue;
    for (const t of ind.tiers || []) {
      if (t.model_only) continue;                       // not emitted, so it needs no technology
      if (!t.tech) startAvail.push(`${ind.id}/${t.key}`);
      else if (!known.has(t.tech)) unknown.push(`${ind.id}/${t.key} -> ${t.tech}`);
    }
  }
  if (unknown.length) {
    throw new Error(
      `${unknown.length} emitted tier(s) name a technology the shipping tree does not contain, so the ` +
      `mod would carry buildings nothing can unlock:\n  ${unknown.join('\n  ')}\n` +
      `  Config: ${CFGPATH}\n  Fix: node tools/tech_tree_spec.mjs --write`);
  }
  console.log(`techs: ${startAvail.length} emitted tier(s) carry no unlocking technology (available at the ` +
    `1836 start): ${startAvail.join(', ') || '(none)'}`);
}

// ---- knobs that this step ships (ROADMAP step 1/2) ------------------------------------------------
// ⚠ RESTORED TO VANILLA 2026-08-12 (user ruling). It was 0.15 — lowered because the tree is deeper —
// and that made reaching era 5 early cheaper by design. Session 20260812_010659 measured the baseline
// production leader holding 12 of 17 era-5 technologies at 1935 with NO research events at all, against
// a design expectation of roughly a quarter by 1936. This factor is one candidate cause of that
// overshoot and the first to be tested; tree depth, era costs and spread have not been separated from it.
const AHEAD_OF_TIME = 0.25;        // NTechnology.TECH_AHEAD_OF_TIME_PENALTY_FACTOR, vanilla 0.25
// ⚠ THE PER-TREE SPREAD BOOST IS GONE — RESTORED TO VANILLA 2026-08-12 (user ruling). It shipped as
// `country_production_tech_spread_mult = 0.5` in base_values, a modifier vanilla does not set at all,
// and its whole job was to compensate a laggard for the deeper production tree. The ruling: the extra
// industry technologies are compensated "aplenty" by the research journal entries (ROADMAP step 2),
// which grant half an era's base cost per stage — so the spread boost was paying twice for the same
// depth, on the one lever that works AGAINST the mod's goal (spread only ever delivers what somebody
// else already has, so it cannot create a leader; it closes the gap the deeper tree exists to open).
// ⚠ THE KNOB STAYS IN THE TECH-TREE PAGE, defaulting to 0 for all three trees. It is how the question
// gets re-asked — the share of a tree handed to a laggard by 1936 against vanilla's own share — and
// deleting the instrument along with the setting would leave nothing to re-measure with.
// ⚠ AND WITH IT WE STOP OWNING `00_code_static_modifiers.txt`. That one line was the only difference
// from vanilla in a 900-line file, and the repo's rule is that a file we would copy verbatim is not
// emitted: owning it freezes that file against the next patch and ships bytes we did not author.
const SOCIETY_AI_WEIGHT = 0.8;     // user ruling 2026-08-11 — damp society so spread does not rush it
const PLACEHOLDER = 'gfx/interface/icons/invention_icons/zzz_pm_rehaul_placeholder.dds';

const BOM = '\uFEFF';
const out = [];
function write(rel, text, bom = true) {
  const p = join(MOD, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, (bom ? BOM : '') + text, 'utf8');
  out.push(rel);
}
function writeBin(rel, buf) {
  const p = join(MOD, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, buf);
  out.push(rel);
}
const vanilla = rel => readFileSync(join(GAME, rel), 'utf8').replace(/^\uFEFF/, '');
// Replace exactly `n` occurrences or throw. The count is the point: a pattern that suddenly matches
// twice is as broken as one that stops matching.
function sub(text, re, repl, n, what) {
  const hits = text.match(re);
  const got = hits ? (re.global ? hits.length : 1) : 0;
  if (got !== n) throw new Error(`emit_techs: ${what} — expected ${n} match(es), found ${got}. ` +
    `Vanilla has changed shape; fix the transform rather than shipping a silent no-op.`);
  return text.replace(re, repl);
}

// ===================================================================================================
// 1. THE NEW TECHNOLOGIES — additive
// ===================================================================================================
const NEWT = OPT.techs.filter(t => t.origin === 'new');
{
  const L = ['# AUTO-GENERATED by tools/emit_techs.mjs — do not edit by hand.',
    `# ${NEWT.length} technologies for the PM & Tech Rehaul ladder. Design lives in tools/tech_tree_spec.mjs.`, ''];
  for (const t of NEWT.slice().sort((a, b) => a.category.localeCompare(b.category) || a.era - b.era || a.id.localeCompare(b.id))) {
    L.push(`${t.id} = {`);
    if (t.unlocks.length) L.push(`\t# Unlocks ${t.unlocks.map(u => u.name).join(', ')}`);
    L.push(`\tera = era_${t.era}`);
    L.push(`\ttexture = "${PLACEHOLDER}"`);
    L.push(`\tcategory = ${t.category}`);
    if (t.prereqs.length) {
      L.push('\tunlocking_technologies = {');
      for (const p of t.prereqs) L.push(`\t\t${p}`);
      L.push('\t}');
    }
    if (t.mod && Object.keys(t.mod).length) {
      L.push('\tmodifier = {');
      for (const [k, v] of Object.entries(t.mod)) L.push(`\t\t${k} = ${v}`);
      L.push('\t}');
    }
    L.push('\tai_weight = {');
    L.push(`\t\tvalue = ${t.category === 'society' ? SOCIETY_AI_WEIGHT : 1}`);
    L.push('\t}');
    L.push('}', '');
  }
  write('common/technology/technologies/zzz_pm_rehaul_techs.txt', L.join('\n'));
}

// ===================================================================================================
// 2. VANILLA PRODUCTION FILE — era moves and one prerequisite swap
// ===================================================================================================
{
  let txt = vanilla('common/technology/technologies/10_production.txt');
  // Re-era'd technologies, each with the reason the spec recorded.
  // ⚠ VANILLA ONES ONLY. `reEra` records that the spec moved a technology, and since the ladder-era
  // alignment (2026-08-12) most of the moved ones are technologies WE ADD — those get their era written
  // directly in section 1, and they have no block in the vanilla file to patch. Without the origin
  // filter this searched 10_production.txt for `regenerative_furnace` and, finding nothing, threw. That
  // throw is the guardrail working: a transform that matches nothing must fail rather than no-op.
  const eraMoves = OPT.techs.filter(t => t.reEra && t.category === 'production' && t.origin === 'vanilla');
  for (const t of eraMoves) {
    // anchor on the tech's own block so we cannot hit another tech's era line
    const re = new RegExp(`(^${t.id} = \\{[\\s\\S]*?\\n\\tera = era_)\\d`, 'm');
    txt = sub(txt, re, `$1${t.era}`, 1, `re-era ${t.id} -> era ${t.era}`);
  }
  // `aniline` moved to era 2 and can no longer wait on `rubber_mastication`, which is era 3.
  txt = sub(txt, /(^aniline = \{[\s\S]*?unlocking_technologies = \{)[^}]*(\})/m,
    '$1\n\t\tchemical_bleaching\n\t$2', 1, 'aniline prerequisite swap');
  write('common/technology/technologies/10_production.txt', txt);
}

// ===================================================================================================
// 2b. VANILLA MILITARY FILE — era moves
// ===================================================================================================
// ⚠ THIS FILE EXISTED AS A GAP UNTIL 2026-08-12. Section 2 patches ONLY 10_production.txt, so a re-era
// on a MILITARY technology was written into the spec, reported by the viewer, and then silently
// dropped on the way to the mod — the tree the game loaded would disagree with the tree the sheet drew,
// with nothing failing anywhere. The ladder-era alignment moves three of them (repeaters,
// breech_loading_artillery, bolt_action_rifles: arms and artillery are military-tree industries by user
// ruling), which is what surfaced it.
// ⚠ THE LOOP IS DELIBERATELY UNCONDITIONAL — it runs even when the list is empty, and `sub` throws when
// a transform matches nothing. A `if (moves.length)` guard here would make an empty list and a broken
// pattern look identical.
{
  const moves = OPT.techs.filter(t => t.reEra && t.category === 'military' && t.origin === 'vanilla');
  if (moves.length) {
    let txt = vanilla('common/technology/technologies/20_military.txt');
    for (const t of moves) {
      const re = new RegExp(`(^${t.id} = \\{[\\s\\S]*?\\n\\tera = era_)\\d`, 'm');
      txt = sub(txt, re, `$1${t.era}`, 1, `re-era ${t.id} -> era ${t.era}`);
    }
    write('common/technology/technologies/20_military.txt', txt);
  }
}

// ===================================================================================================
// 3. VANILLA SOCIETY FILE — ai_weight x0.8 on every technology
// ===================================================================================================
// Multiplied, not overwritten: vanilla authored real relative weights (2 and 3 on the techs it wants
// the AI to prioritise) and flattening them to a constant would throw that away. `multiply` is appended
// last so it applies to whatever the conditional `add`s produced.
{
  let txt = vanilla('common/technology/technologies/30_society.txt');
  const starts = [...txt.matchAll(/^([a-z_0-9-]+) = \{$/gm)].map(m => ({ id: m[1], at: m.index }));
  let done = 0;
  for (let i = starts.length - 1; i >= 0; i--) {          // backwards, so earlier offsets stay valid
    const from = starts[i].at, to = i + 1 < starts.length ? starts[i + 1].at : txt.length;
    const block = txt.slice(from, to);
    const aw = block.indexOf('\tai_weight = {');
    if (aw < 0) throw new Error(`emit_techs: society technology ${starts[i].id} has no ai_weight block`);
    // brace-match from the opening of ai_weight to its close
    let d = 0, end = -1;
    for (let k = aw; k < block.length; k++) {
      if (block[k] === '{') d++;
      else if (block[k] === '}') { d--; if (d === 0) { end = k; break; } }
    }
    if (end < 0) throw new Error(`emit_techs: unbalanced ai_weight in society technology ${starts[i].id}`);
    const patched = block.slice(0, end) + `\n\t\tmultiply = ${SOCIETY_AI_WEIGHT}\n\t` + block.slice(end);
    txt = txt.slice(0, from) + patched + txt.slice(to);
    done++;
  }
  if (done !== starts.length) throw new Error(`emit_techs: damped ${done} of ${starts.length} society technologies`);
  console.log(`  society ai_weight x${SOCIETY_AI_WEIGHT} applied to ${done} technologies`);
  write('common/technology/technologies/30_society.txt', txt);
}

// ===================================================================================================
// 4. STARTING TECHNOLOGIES — the 1836 sets
// ===================================================================================================
// Tiers 1 and 2 call `add_era_researched = era_1` and so pick up every new era-1 technology for free.
// Tiers 3-5 list technologies by name, so a country that starts with, say, a calico works would
// otherwise own a building it could not have built. Tier 6 holds `enclosure` alone and tier 7 nothing;
// both are left as they are, deliberately — those countries are meant to have no industry.
{
  let txt = vanilla('common/scripted_effects/00_starting_inventions.txt');
  const newEra1Prod = NEWT.filter(t => t.era === 1 && t.category === 'production').map(t => t.id);
  if (!newEra1Prod.length) throw new Error('emit_techs: expected at least one new era-1 production technology');
  for (const tier of [3, 4, 5]) {
    const re = new RegExp(`(effect_starting_technology_tier_${tier}_tech = \\{[\\s\\S]*?add_technology_researched = manufacturies\\n)`, 'm');
    const add = newEra1Prod.map(id => `\tadd_technology_researched = ${id}\n`).join('');
    txt = sub(txt, re, `$1${add}`, 1, `starting technologies, tier ${tier}`);
  }
  // ⭐⭐ OUR OWN NAMED GRANT — a technology the 1836 MAP depends on whose slot we date after 1836.
  // Vanilla already carries three such cases (`central_archives` 1838, `mechanical_tools` 1840,
  // `intensive_agriculture` 1842) in an explicit named grant, because its own starting map runs buildings
  // the calendar would forbid. Our re-band adds a fourth, and it must be named for the same reason.
  //
  // ⚠ WHY THIS ONE. Vanilla gates a steel tooling workshop on `mechanical_tools` — which IS in that named
  // grant — so vanilla's 1836 great powers run steel tooling, and 16 of the map's 35 tooling workshops do.
  // Our ladder replaced that gate with `steel_toolmaking` (era 3, 1865, and requiring `bessemer_process`
  // 1856), so converting those workshops faithfully produced five great powers owning a building their own
  // technologies could not unlock. The ruling is that 1836 stays close to vanilla — the industries that
  // factually existed stay, and their technologies are unlocked — so the grant follows the map.
  // ⚠ It was INVISIBLE until landmine L13 was fixed: while the converter silently failed to re-tier those
  // workshops, they stayed on the base rung and nothing was gated wrongly. `tools/verify_start_techs.mjs`
  // is what found it, one build after the conversion started working.
  // ⚠ Tiers 1 and 2 only. Tier 3 and below do not run steel tooling on the 1836 map, and granting an 1865
  // technology to a country that has no use for it would move 1836 away from vanilla, not towards it.
  for (const tier of [1, 2]) {
    const re = new RegExp(`(effect_starting_technology_tier_${tier}_tech = \\{\\n)`, 'm');
    txt = sub(txt, re, `$1\tadd_technology_researched = steel_toolmaking\n`, 1, `named grant, tier ${tier}`);
  }
  write('common/scripted_effects/00_starting_inventions.txt', txt);
}

// ===================================================================================================
// 5. STATIC MODIFIERS — NOTHING. Tech spread is left exactly as vanilla sets it.
// ===================================================================================================
// This step used to emit a whole copy of `common/static_modifiers/00_code_static_modifiers.txt` for one
// added line, `country_production_tech_spread_mult = 0.5`. Removed by user ruling 2026-08-12 — see the
// note on the knobs above. Nothing replaces it: the file is not ours, and the tech-tree page's spread
// panel now opens on the vanilla setting for all three trees.
// ⚠ A global boost had already been measured and rejected (it handed 69% of the society tree to a
// laggard against vanilla's 44%); the production-only form is what this ruling removes.

// ===================================================================================================
// 6. DEFINES — the ahead-of-time penalty (partial override; the one folder that allows it)
// ===================================================================================================
write('common/defines/01_pm_rehaul_defines.txt',
  '# AUTO-GENERATED by tools/emit_techs.mjs — do not edit by hand.\n' +
  '# Defines take a PARTIAL override: only the keys named here change, the rest of NTechnology and the\n' +
  '# rest of 00_defines.txt stay vanilla. See MODDING_NOTES -> File loading & override semantics.\n' +
  'NTechnology = {\n' +
  `\tTECH_AHEAD_OF_TIME_PENALTY_FACTOR = ${AHEAD_OF_TIME}\t# vanilla 0.25; the tree is deeper\n` +
  '}\n');

// ===================================================================================================
// 7. PLACEHOLDER ICON — a real DDS, minted here, no art and no image library
// ===================================================================================================
// Vanilla's invention icons are 256x256 32-bit A8R8G8B8 with 9 mipmaps. Mipmaps are optional and a
// single surface is a legal DDS, so this is a 128-byte header plus raw BGRA. Deliberately ONE shared
// file rather than one per technology: it makes "no art yet" obvious at a glance, and it is 256 KB
// instead of ten megabytes. Step 7 replaces it.
{
  const N = 256, hdr = Buffer.alloc(128);
  hdr.write('DDS ', 0, 'ascii');
  hdr.writeUInt32LE(124, 4);
  hdr.writeUInt32LE(0x1 | 0x2 | 0x4 | 0x8 | 0x1000, 8);
  hdr.writeUInt32LE(N, 12); hdr.writeUInt32LE(N, 16); hdr.writeUInt32LE(N * 4, 20);
  hdr.writeUInt32LE(32, 76); hdr.writeUInt32LE(0x41, 80); hdr.writeUInt32LE(32, 88);
  hdr.writeUInt32LE(0x00ff0000, 92); hdr.writeUInt32LE(0x0000ff00, 96);
  hdr.writeUInt32LE(0x000000ff, 100); hdr.writeUInt32LE(0xff000000, 104);
  hdr.writeUInt32LE(0x1000, 108);
  const px = Buffer.alloc(N * N * 4);
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const cross = Math.abs(x - y) < 14 || Math.abs(x + y - (N - 1)) < 14;
    const edge = x < 8 || y < 8 || x > N - 9 || y > N - 9;
    const [r, g, b] = cross || edge ? [200, 30, 30] : [240, 200, 40];
    const o = (y * N + x) * 4;
    px[o] = b; px[o + 1] = g; px[o + 2] = r; px[o + 3] = 255;   // BGRA
  }
  writeBin(PLACEHOLDER, Buffer.concat([hdr, px]));
}

// ===================================================================================================
// 8. LOCALIZATION — new names and descriptions, plus the renamed vanilla technologies
// ===================================================================================================
{
  const esc = s => String(s).replace(/"/g, '\\"');
  const body = [];
  for (const t of NEWT) {
    body.push(` ${t.id}:0 "${esc(t.name)}"`);
    if (t.desc) body.push(` ${t.id}_desc:0 "${esc(t.desc)}"`);
  }
  // Renamed vanilla technologies. `replace/` hard-overwrites the vanilla key.
  const renamed = OPT.techs.filter(t => t.renamed);
  for (const t of renamed) body.push(` ${t.id}:0 "${esc(t.name)}"`);
  console.log(`  localization: ${NEWT.length} new technologies + ${renamed.length} renamed vanilla ones`);
  for (const lang of CFG.languages) {
    write(`localization/${lang}/replace/zzz_pm_rehaul_tech_l_${lang}.yml`,
      `l_${lang}:\n# AUTO-GENERATED by tools/emit_techs.mjs — English strings are used as stubs for all languages.\n` +
      body.join('\n') + '\n');
  }
}

console.log(`  emit_techs: ${NEWT.length} new technologies, ${out.length} files -> ${MOD}`);
