// EMIT THE INDUSTRY TECH TREE into a built mod (ROADMAP step 1).
//
//   node tools/emit_techs.mjs <modRoot>        # called by tools/build.ps1
//
// Reads config/tech_tree_options.json (generated by tools/tech_tree_spec.mjs) and writes the option
// marked `ships`. Nothing here decides design — that file does.
//
// ⚠⚠ EVERY VANILLA TRANSFORM BELOW **THROWS** WHEN ITS ANCHOR IS NOT FOUND. A silent no-op is the exact
// failure mode this project's landmine register exists for: the build succeeds, the mod loads, the game
// runs, and the change simply is not there. There is no "warn and continue" path on purpose.
//
// What gets written, and why each is the kind of file it is:
//   ADDITIVE (new keys, new filename — touches no vanilla file)
//     common/technology/technologies/zzz_pm_rehaul_techs.txt
//     common/defines/01_pm_rehaul_defines.txt          (defines are the one folder taking partials)
//     gfx/interface/icons/invention_icons/zzz_pm_rehaul_placeholder.dds
//     localization/<lang>/replace/zzz_pm_rehaul_tech_l_<lang>.yml
//   WHOLE-FILE, REGENERATED FROM VANILLA EACH BUILD (so a patch flows through, nothing is frozen)
//     common/technology/technologies/10_production.txt  — era moves + one prerequisite swap
//     common/technology/technologies/30_society.txt     — ai_weight x0.8 on every society technology
//     common/scripted_effects/00_starting_inventions.txt— new era-1 techs into the 1836 starting sets
//     common/static_modifiers/00_code_static_modifiers.txt — the production-only tech spread multiplier
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const GAME = 'C:/Program Files (x86)/Steam/steamapps/common/Victoria 3/game';
const MOD = process.argv[2];
if (!MOD) { console.error('usage: node tools/emit_techs.mjs <modRoot>'); process.exit(2); }

const DATA = JSON.parse(readFileSync(join(REPO, 'config', 'tech_tree_options.json'), 'utf8'));
const OPT = DATA.options.find(o => o.ships);
if (!OPT) throw new Error('no option is marked `ships` in config/tech_tree_options.json');
const CFG = JSON.parse(readFileSync(join(REPO, 'config', 'mod_config.json'), 'utf8'));

// ---- knobs that this step ships (ROADMAP step 1/2) ------------------------------------------------
const AHEAD_OF_TIME = 0.15;        // NTechnology.TECH_AHEAD_OF_TIME_PENALTY_FACTOR, vanilla 0.25
const PROD_SPREAD_MULT = 0.5;      // production-only spread boost; military and society untouched
const SOCIETY_AI_WEIGHT = 0.8;     // user ruling 2026-08-11 — damp society so spread does not rush it
const PLACEHOLDER = 'gfx/interface/icons/invention_icons/zzz_pm_rehaul_placeholder.dds';

const BOM = '\uFEFF';
const out = [];
function write(rel, text, bom = true) {
  const p = join(MOD, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, (bom ? BOM : '') + text, 'utf8');
  out.push(rel);
}
function writeBin(rel, buf) {
  const p = join(MOD, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, buf);
  out.push(rel);
}
const vanilla = rel => readFileSync(join(GAME, rel), 'utf8').replace(/^\uFEFF/, '');
// Replace exactly `n` occurrences or throw. The count is the point: a pattern that suddenly matches
// twice is as broken as one that stops matching.
function sub(text, re, repl, n, what) {
  const hits = text.match(re);
  const got = hits ? (re.global ? hits.length : 1) : 0;
  if (got !== n) throw new Error(`emit_techs: ${what} — expected ${n} match(es), found ${got}. ` +
    `Vanilla has changed shape; fix the transform rather than shipping a silent no-op.`);
  return text.replace(re, repl);
}

// ===================================================================================================
// 1. THE NEW TECHNOLOGIES — additive
// ===================================================================================================
const NEWT = OPT.techs.filter(t => t.origin === 'new');
{
  const L = ['# AUTO-GENERATED by tools/emit_techs.mjs — do not edit by hand.',
    `# ${NEWT.length} technologies for the PM & Tech Rehaul ladder. Design lives in tools/tech_tree_spec.mjs.`, ''];
  for (const t of NEWT.slice().sort((a, b) => a.category.localeCompare(b.category) || a.era - b.era || a.id.localeCompare(b.id))) {
    L.push(`${t.id} = {`);
    if (t.unlocks.length) L.push(`\t# Unlocks ${t.unlocks.map(u => u.name).join(', ')}`);
    L.push(`\tera = era_${t.era}`);
    L.push(`\ttexture = "${PLACEHOLDER}"`);
    L.push(`\tcategory = ${t.category}`);
    if (t.prereqs.length) {
      L.push('\tunlocking_technologies = {');
      for (const p of t.prereqs) L.push(`\t\t${p}`);
      L.push('\t}');
    }
    if (t.mod && Object.keys(t.mod).length) {
      L.push('\tmodifier = {');
      for (const [k, v] of Object.entries(t.mod)) L.push(`\t\t${k} = ${v}`);
      L.push('\t}');
    }
    L.push('\tai_weight = {');
    L.push(`\t\tvalue = ${t.category === 'society' ? SOCIETY_AI_WEIGHT : 1}`);
    L.push('\t}');
    L.push('}', '');
  }
  write('common/technology/technologies/zzz_pm_rehaul_techs.txt', L.join('\n'));
}

// ===================================================================================================
// 2. VANILLA PRODUCTION FILE — era moves and one prerequisite swap
// ===================================================================================================
{
  let txt = vanilla('common/technology/technologies/10_production.txt');
  // Re-era'd technologies, each with the reason the spec recorded.
  const eraMoves = OPT.techs.filter(t => t.reEra && t.category === 'production');
  for (const t of eraMoves) {
    // anchor on the tech's own block so we cannot hit another tech's era line
    const re = new RegExp(`(^${t.id} = \\{[\\s\\S]*?\\n\\tera = era_)\\d`, 'm');
    txt = sub(txt, re, `$1${t.era}`, 1, `re-era ${t.id} -> era ${t.era}`);
  }
  // `aniline` moved to era 2 and can no longer wait on `rubber_mastication`, which is era 3.
  txt = sub(txt, /(^aniline = \{[\s\S]*?unlocking_technologies = \{)[^}]*(\})/m,
    '$1\n\t\tchemical_bleaching\n\t$2', 1, 'aniline prerequisite swap');
  write('common/technology/technologies/10_production.txt', txt);
}

// ===================================================================================================
// 3. VANILLA SOCIETY FILE — ai_weight x0.8 on every technology
// ===================================================================================================
// Multiplied, not overwritten: vanilla authored real relative weights (2 and 3 on the techs it wants
// the AI to prioritise) and flattening them to a constant would throw that away. `multiply` is appended
// last so it applies to whatever the conditional `add`s produced.
{
  let txt = vanilla('common/technology/technologies/30_society.txt');
  const starts = [...txt.matchAll(/^([a-z_0-9-]+) = \{$/gm)].map(m => ({ id: m[1], at: m.index }));
  let done = 0;
  for (let i = starts.length - 1; i >= 0; i--) {          // backwards, so earlier offsets stay valid
    const from = starts[i].at, to = i + 1 < starts.length ? starts[i + 1].at : txt.length;
    const block = txt.slice(from, to);
    const aw = block.indexOf('\tai_weight = {');
    if (aw < 0) throw new Error(`emit_techs: society technology ${starts[i].id} has no ai_weight block`);
    // brace-match from the opening of ai_weight to its close
    let d = 0, end = -1;
    for (let k = aw; k < block.length; k++) {
      if (block[k] === '{') d++;
      else if (block[k] === '}') { d--; if (d === 0) { end = k; break; } }
    }
    if (end < 0) throw new Error(`emit_techs: unbalanced ai_weight in society technology ${starts[i].id}`);
    const patched = block.slice(0, end) + `\n\t\tmultiply = ${SOCIETY_AI_WEIGHT}\n\t` + block.slice(end);
    txt = txt.slice(0, from) + patched + txt.slice(to);
    done++;
  }
  if (done !== starts.length) throw new Error(`emit_techs: damped ${done} of ${starts.length} society technologies`);
  console.log(`  society ai_weight x${SOCIETY_AI_WEIGHT} applied to ${done} technologies`);
  write('common/technology/technologies/30_society.txt', txt);
}

// ===================================================================================================
// 4. STARTING TECHNOLOGIES — the 1836 sets
// ===================================================================================================
// Tiers 1 and 2 call `add_era_researched = era_1` and so pick up every new era-1 technology for free.
// Tiers 3-5 list technologies by name, so a country that starts with, say, a calico works would
// otherwise own a building it could not have built. Tier 6 holds `enclosure` alone and tier 7 nothing;
// both are left as they are, deliberately — those countries are meant to have no industry.
{
  let txt = vanilla('common/scripted_effects/00_starting_inventions.txt');
  const newEra1Prod = NEWT.filter(t => t.era === 1 && t.category === 'production').map(t => t.id);
  if (!newEra1Prod.length) throw new Error('emit_techs: expected at least one new era-1 production technology');
  for (const tier of [3, 4, 5]) {
    const re = new RegExp(`(effect_starting_technology_tier_${tier}_tech = \\{[\\s\\S]*?add_technology_researched = manufacturies\\n)`, 'm');
    const add = newEra1Prod.map(id => `\tadd_technology_researched = ${id}\n`).join('');
    txt = sub(txt, re, `$1${add}`, 1, `starting technologies, tier ${tier}`);
  }
  write('common/scripted_effects/00_starting_inventions.txt', txt);
}

// ===================================================================================================
// 5. STATIC MODIFIERS — the production-only spread boost
// ===================================================================================================
// ⚠ Production ONLY. A global boost was measured and rejected: with military and society near vanilla
// depth it hands those two trees away (69% of society against vanilla's 44%). See ROADMAP step 2.
{
  let txt = vanilla('common/static_modifiers/00_code_static_modifiers.txt');
  txt = sub(txt, /(base_values = \{\n\tcountry_weekly_innovation_add = 50\n)/,
    `$1\tcountry_production_tech_spread_mult = ${PROD_SPREAD_MULT}\n`, 1, 'production tech spread multiplier');
  write('common/static_modifiers/00_code_static_modifiers.txt', txt);
}

// ===================================================================================================
// 6. DEFINES — the ahead-of-time penalty (partial override; the one folder that allows it)
// ===================================================================================================
write('common/defines/01_pm_rehaul_defines.txt',
  '# AUTO-GENERATED by tools/emit_techs.mjs — do not edit by hand.\n' +
  '# Defines take a PARTIAL override: only the keys named here change, the rest of NTechnology and the\n' +
  '# rest of 00_defines.txt stay vanilla. See MODDING_NOTES -> File loading & override semantics.\n' +
  'NTechnology = {\n' +
  `\tTECH_AHEAD_OF_TIME_PENALTY_FACTOR = ${AHEAD_OF_TIME}\t# vanilla 0.25; the tree is deeper\n` +
  '}\n');

// ===================================================================================================
// 7. PLACEHOLDER ICON — a real DDS, minted here, no art and no image library
// ===================================================================================================
// Vanilla's invention icons are 256x256 32-bit A8R8G8B8 with 9 mipmaps. Mipmaps are optional and a
// single surface is a legal DDS, so this is a 128-byte header plus raw BGRA. Deliberately ONE shared
// file rather than one per technology: it makes "no art yet" obvious at a glance, and it is 256 KB
// instead of ten megabytes. Step 7 replaces it.
{
  const N = 256, hdr = Buffer.alloc(128);
  hdr.write('DDS ', 0, 'ascii');
  hdr.writeUInt32LE(124, 4);
  hdr.writeUInt32LE(0x1 | 0x2 | 0x4 | 0x8 | 0x1000, 8);
  hdr.writeUInt32LE(N, 12); hdr.writeUInt32LE(N, 16); hdr.writeUInt32LE(N * 4, 20);
  hdr.writeUInt32LE(32, 76); hdr.writeUInt32LE(0x41, 80); hdr.writeUInt32LE(32, 88);
  hdr.writeUInt32LE(0x00ff0000, 92); hdr.writeUInt32LE(0x0000ff00, 96);
  hdr.writeUInt32LE(0x000000ff, 100); hdr.writeUInt32LE(0xff000000, 104);
  hdr.writeUInt32LE(0x1000, 108);
  const px = Buffer.alloc(N * N * 4);
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const cross = Math.abs(x - y) < 14 || Math.abs(x + y - (N - 1)) < 14;
    const edge = x < 8 || y < 8 || x > N - 9 || y > N - 9;
    const [r, g, b] = cross || edge ? [200, 30, 30] : [240, 200, 40];
    const o = (y * N + x) * 4;
    px[o] = b; px[o + 1] = g; px[o + 2] = r; px[o + 3] = 255;   // BGRA
  }
  writeBin(PLACEHOLDER, Buffer.concat([hdr, px]));
}

// ===================================================================================================
// 8. LOCALIZATION — new names and descriptions, plus the renamed vanilla technologies
// ===================================================================================================
{
  const esc = s => String(s).replace(/"/g, '\\"');
  const body = [];
  for (const t of NEWT) {
    body.push(` ${t.id}:0 "${esc(t.name)}"`);
    if (t.desc) body.push(` ${t.id}_desc:0 "${esc(t.desc)}"`);
  }
  // Renamed vanilla technologies. `replace/` hard-overwrites the vanilla key.
  const renamed = OPT.techs.filter(t => t.renamed);
  for (const t of renamed) body.push(` ${t.id}:0 "${esc(t.name)}"`);
  console.log(`  localization: ${NEWT.length} new technologies + ${renamed.length} renamed vanilla ones`);
  for (const lang of CFG.languages) {
    write(`localization/${lang}/replace/zzz_pm_rehaul_tech_l_${lang}.yml`,
      `l_${lang}:\n# AUTO-GENERATED by tools/emit_techs.mjs — English strings are used as stubs for all languages.\n` +
      body.join('\n') + '\n');
  }
}

console.log(`  emit_techs: ${NEWT.length} new technologies, ${out.length} files -> ${MOD}`);
