// THE HYDRO-DAM MEGAPROJECTS, EMITTED (ROADMAP step 6, BALANCE_FRAMEWORK §10.89, user-ruled 2026-09-26).
//
//   node tools/emit_dams.mjs <modRoot> [configPath]        # called by tools/build.ps1
//
// Config `dams` absent or `enabled: false` → emits nothing. Enabled → per project (config/dam_projects.json,
// one per state; the numbers are tools/lib_dams.mjs's — ONE derivation):
//   • a SURVEY decision, shown to the country that owns the project's ANCHOR PROVINCE and to every country
//     above it in its overlord chain (never to a great power as such, never to an investor), once the
//     project's class technology is researched; it adds a bureaucracy-cost modifier and a counter journal
//     entry (the vanilla canal pattern, common/decisions/canal_decisions.txt). One survey at a time per
//     project, world-wide (global variable). A STOP decision cancels it.
//   • on completion a GLOBAL variable marks the site surveyed. There is NO exclusive right for the
//     surveyor: a building's `possible`/`ai_value` are evaluated in the STATE's scope and cannot see who is
//     constructing (common/buildings/buildings.md), so the right to build is the anchor owner's chain as a
//     whole. The user's "two idle years ⇒ free for all" rule is therefore satisfied from day one.
//   • STAGES: unique single-level buildings building_dam_<id>_<k>, stage k shown once stage k-1 exists
//     (the Kaiserforum pattern, common/buildings/08_monuments.txt). `unique` = one level in the world and
//     never built by private investors; the group is government-funded, so it is never privatised.
//     Every stage's `possible` requires the building state to be the split part holding the anchor
//     province (`owner ?= p:<prov>.state.owner`, the Victoria Terminus pattern): only the side of a split
//     state that owns the site can build.
//   • the non-power effects (config/dam_projects.json `effects`): arable land and state-trait swaps, fired
//     from on_building_built when a named stage completes; `start_traits` swapped in at the campaign start.
//   • the electricity lines of the vanilla hydro-narrative state traits (config `dams.strip_trait_modifiers`)
//     removed by WHOLE-FILE copies of their vanilla trait files — every other line vanilla's, asserted.
//   • telemetry: debug.log lines `PMR_DAM|<event>|<project>|<tag>|<date>` for survey start / stop / fail /
//     complete and every stage built.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { REPO, deriveAll } from './lib_dams.mjs';

const GAME = process.env.VIC3_GAME || 'C:/Program Files (x86)/Steam/steamapps/common/Victoria 3/game';
const MOD = process.argv[2];
if (!MOD) { console.error('usage: node tools/emit_dams.mjs <modRoot> [configPath]'); process.exit(2); }
const CFGPATH = process.argv[3] || join(REPO, 'config/mod_config.json');
const CFG = JSON.parse(readFileSync(CFGPATH, 'utf8'));
if (!CFG.dams?.enabled) { console.log('dams: disabled - nothing emitted'); process.exit(0); }

const die = m => { throw new Error('emit_dams: ' + m); };
const W = (rel, s) => { const f = join(MOD, rel); mkdirSync(dirname(f), { recursive: true }); writeFileSync(f, '\uFEFF' + s, 'utf8'); };
const T = '\t';
const stripBom = s => s.replace(/^\uFEFF/, '');
const { P, projects } = deriveAll(CFG);
const HDR = `# AUTO-GENERATED by tools/emit_dams.mjs from ${CFGPATH.replace(/\\/g, '/').split('/').slice(-2).join('/')} + ${P.projects_file} - do not edit by hand.\n\n`;
const DATE = '[TimeKeeper.GetCurrentDate.GetString]';
// the country's bureaucracy at the moment of a log line: produced / used (script values emitted below)
const BUR = "bur [THIS.GetCountry.MakeScope.ScriptValue('pmr_dam_bur_produced')|0]/[THIS.GetCountry.MakeScope.ScriptValue('pmr_dam_bur_used')|0]";
// ⚠ there is NO country-tag data function (TESTBED_METRICS §3: GetTag voids the line) - logs carry the NAME
const TAG = '[THIS.GetCountry.GetNameNoFormatting]';
const ACTIVE = 'pmr_dam_active_surveys';   // per country: dam surveys under way (the AI runs one at a time)

// ---------------------------------------------------------------- validation against the game
const stateProv = {};
for (const f of readdirSync(join(GAME, 'map_data/state_regions'))) {
  const txt = stripBom(readFileSync(join(GAME, 'map_data/state_regions', f), 'utf8'));
  for (const m of txt.matchAll(/^(STATE_[A-Z0-9_]+)\s*=\s*\{([\s\S]*?)^\}/gm)) {
    const pm = /provinces\s*=\s*\{([^}]*)\}/.exec(m[2]);
    stateProv[m[1]] = new Set((pm ? pm[1] : '').match(/x[0-9A-Fa-f]{6}/g)?.map(s => 'x' + s.slice(1).toUpperCase()) || []);
  }
}
const techFiles = readdirSync(join(GAME, 'common/technology/technologies')).map(f => readFileSync(join(GAME, 'common/technology/technologies', f), 'utf8')).join('\n');
for (const t of new Set(Object.values(P.tech_by_class))) if (!new RegExp(`^${t}\\s*=\\s*\\{`, 'm').test(techFiles)) die(`technology ${t} not in the game`);
for (const p of projects) {
  if (!stateProv[p.state]) die(`${p.id}: ${p.state} is not a state region`);
  if (!stateProv[p.state].has(p.anchor_province)) die(`${p.id}: anchor ${p.anchor_province} is not a province of ${p.state}`);
}

// ---------------------------------------------------------------- shared triggers
// the country in scope (ROOT) owns the anchor province, or sits above its owner in the overlord chain
const chainOf = p => `p:${p.anchor_province} ?= {\n${T}${T}${T}state ?= {\n${T}${T}${T}${T}owner ?= {\n${T}${T}${T}${T}${T}OR = {\n${T}${T}${T}${T}${T}${T}this = ROOT\n${T}${T}${T}${T}${T}${T}any_overlord_or_above = { this = ROOT }\n${T}${T}${T}${T}${T}}\n${T}${T}${T}${T}}\n${T}${T}${T}}\n${T}${T}}`;
const isOwnerOf = p => `p:${p.anchor_province} ?= { state ?= { owner ?= ROOT } }`;
const V = p => `pmr_dam_${p.id}`;     // variable / key stem

// ---------------------------------------------------------------- building group
W('common/building_groups/zzz_pm_rehaul_dams.txt', HDR +
`bg_pmr_hydro_dams = {
${T}parent_group = bg_infrastructure
${T}lens = special
${T}is_government_funded = yes
${T}inheritable_construction = yes
${T}economy_of_scale = no
${T}urbanization = 10
}
`);

// ---------------------------------------------------------------- buildings, methods, groups
const bld = [], pms = [], pmgs = [], mods = [], decs = [], jes = [], loc = [], seff = [];
const surveyOpen = new Map();
for (const p of projects) {
  const v = V(p);
  pmgs.push(`pmg_dam_${p.id} = {\n${T}texture = "gfx/interface/icons/generic_icons/mixed_icon_base.dds"\n${T}ai_selection = most_productive\n${T}production_methods = {\n${T}${T}pm_dam_${p.id}\n${T}}\n}`);
  pms.push(`pm_dam_${p.id} = {\n${T}texture = "gfx/interface/icons/production_method_icons/hydroelectric_plant.dds"\n\n` +
    `${T}building_modifiers = {\n${T}${T}workforce_scaled = {\n` +
    Object.entries(p.inputs).map(([g, q]) => `${T}${T}${T}goods_input_${g}_add = ${q}\n`).join('') +
    `${T}${T}${T}goods_output_electricity_add = ${p.stage_units}\n${T}${T}}\n\n${T}${T}level_scaled = {\n` +
    Object.entries(p.staff).map(([prof, q]) => `${T}${T}${T}building_employment_${prof}_add = ${q}\n`).join('') +
    `${T}${T}}\n${T}}\n}`);
  loc.push([`pmg_dam_${p.id}`, 'Hydroelectric Station'], [`pm_dam_${p.id}`, `${p.name} Hydroelectric Station`]);
  for (let k = 1; k <= p.stages; k++) {
    const key = `building_dam_${p.id}_${k}`;
    bld.push(`${key} = {\n` +
      `${T}building_group = bg_pmr_hydro_dams\n` +
      `${T}icon = "gfx/interface/icons/building_icons/power_plant.dds"\n` +
      `${T}city_type = city\n${T}levels_per_mesh = 50\n` +
      `${T}expandable = no\n${T}downsizeable = no\n${T}unique = yes\n` +
      `${T}required_construction = ${p.stage_points}\n\n` +
      `${T}unlocking_technologies = {\n${T}${T}${p.stage_techs[k - 1]}\n${T}}\n\n` +
      `${T}potential = {\n${T}${T}state_region = s:${p.state}\n` +
      `${T}}\n\n` +
      `${T}possible = {\n` +
      `${T}${T}custom_tooltip = {\n${T}${T}${T}text = ${v}_anchor_tt\n${T}${T}${T}owner ?= p:${p.anchor_province}.state.owner\n${T}${T}}\n` +
      `${T}${T}custom_tooltip = {\n${T}${T}${T}text = ${v}_surveyed_tt\n${T}${T}${T}has_global_variable = ${v}_surveyed\n${T}${T}}\n` +
      `${T}}\n\n` +
      `${T}ai_value = {\n${T}${T}value = ${P.ai.stage_ai_value}\n` +
      `${T}${T}if = {\n${T}${T}${T}limit = {\n${T}${T}${T}${T}owner ?= {\n${T}${T}${T}${T}${T}OR = {\n${T}${T}${T}${T}${T}${T}in_default = yes\n${T}${T}${T}${T}${T}${T}is_at_war = yes\n${T}${T}${T}${T}${T}}\n${T}${T}${T}${T}}\n${T}${T}${T}}\n${T}${T}${T}multiply = 0.1\n${T}${T}}\n${T}}\n\n` +
      `${T}production_method_groups = {\n${T}${T}pmg_dam_${p.id}\n${T}}\n\n` +
      `${T}background = "gfx/interface/icons/building_icons/backgrounds/building_panel_bg_monuments.dds"\n}`);
    loc.push([key, p.stages > 1 ? `${p.name} (stage ${k} of ${p.stages})` : p.name]);
    loc.push([`${key}_lens_option`, `Construct $${key}$`]);
  }
  loc.push([`${v}_anchor_tt`, `The dam site (the province of ${p.name}) lies in this part of the state`],
    [`${v}_surveyed_tt`, `The survey of ${p.name} has been completed`]);

  // survey modifier, decisions, journal entry
  mods.push(`${v}_surveying = {\n${T}icon = gfx/interface/icons/timed_modifier_icons/modifier_documents_negative.dds\n${T}country_bureaucracy_cost_add = ${p.survey_bureaucracy}\n}`);
  loc.push([`${v}_surveying`, `Surveying: ${p.name}`]);
  // the survey's start, shared by the player's decision and the AI driver (on_actions below)
  seff.push(`${v}_begin_survey = {\n${T}set_variable = { name = ${v}_months value = 0 }\n${T}set_global_variable = ${v}_surveying\n` +
    `${T}add_modifier = { name = ${v}_surveying }\n${T}add_journal_entry = { type = je_${v}_survey }\n` +
    `${T}if = {\n${T}${T}limit = { NOT = { has_variable = ${ACTIVE} } }\n${T}${T}set_variable = { name = ${ACTIVE} value = 0 }\n${T}}\n${T}change_variable = { name = ${ACTIVE} add = 1 }\n` +
    `${T}debug_log = "PMR_DAM|survey_start|${p.id}|${TAG}|${DATE}|${BUR}"\n}`);
  // the survey is open (technology, not surveyed, nobody surveying, ROOT in the anchor owner's overlord chain)
  surveyOpen.set(p.id, `has_technology_researched = ${p.tech}\n${T}${T}NOT = { has_global_variable = ${v}_surveyed }\n${T}${T}NOT = { has_global_variable = ${v}_surveying }\n${T}${T}${chainOf(p)}`);
  // ⚠ the AI does NOT take this decision (ai_chance 0): it scores every visible decision in one pass, so no weight
  // or counter can stop it taking several surveys the same day (probes p1-p3). The AI surveys through the driver.
  decs.push(`${v}_survey_decision = {\n` +
    `${T}is_shown = {\n${T}${T}${surveyOpen.get(p.id)}\n${T}}\n\n` +
    `${T}possible = {\n${T}${T}produced_bureaucracy > ${p.survey_bureaucracy}\n${T}}\n\n` +
    `${T}when_taken = {\n${T}${T}${v}_begin_survey = yes\n${T}}\n\n` +
    `${T}ai_chance = {\n${T}${T}value = 0\n${T}}\n}`);
  decs.push(`${v}_stop_survey_decision = {\n${T}is_shown = { has_variable = ${v}_months }\n${T}possible = { has_variable = ${v}_months }\n` +
    // the journal entry's on_invalid does the cleanup (one place, so nothing is undone twice)
    `${T}when_taken = {\n${T}${T}remove_variable = ${v}_months\n` +
    `${T}${T}debug_log = "PMR_DAM|survey_stop|${p.id}|${TAG}|${DATE}|${BUR}"\n${T}}\n` +
    // like vanilla's canal survey the AI does not cancel for a bureaucracy deficit (probe p2: it cancelled 72
    // surveys that way); only a default stops it
    `${T}ai_chance = {\n${T}${T}value = 0\n${T}${T}if = {\n${T}${T}${T}limit = { in_default = yes }\n${T}${T}${T}add = 50\n${T}${T}}\n${T}}\n}`);
  loc.push([`${v}_survey_decision`, `Survey the ${p.name}`],
    [`${v}_survey_decision_desc`, `Commission a ${p.survey_months}-month hydrographic and geological survey of the ${p.name} (${p.stages} stage${p.stages > 1 ? 's' : ''}, about ${p.stage_points} construction points and ${p.stage_units} electricity a week each). Once it is complete, this country and the countries above or below it in the overlord chain may build the dams.`],
    [`${v}_stop_survey_decision`, `Cancel the ${p.name} survey`],
    [`${v}_stop_survey_decision_desc`, `Abandon the survey of the ${p.name}. Its cost stops; a later attempt starts from scratch.`]);
  jes.push(`je_${v}_survey = {\n${T}icon = "gfx/interface/icons/event_icons/event_map.dds"\n${T}group = je_group_technology\n\n` +
    `${T}on_monthly_pulse = {\n${T}${T}effect = {\n${T}${T}${T}if = {\n${T}${T}${T}${T}limit = { has_variable = ${v}_months }\n${T}${T}${T}${T}change_variable = { name = ${v}_months add = 1 }\n${T}${T}${T}${T}debug_log = "PMR_DAM|survey_month|${p.id}|${TAG}|${DATE}|${BUR}"\n${T}${T}${T}}\n${T}${T}}\n${T}}\n\n` +
    `${T}complete = {\n${T}${T}scope:journal_entry = { is_goal_complete = yes }\n${T}}\n\n` +
    `${T}on_complete = {\n${T}${T}remove_modifier = ${v}_surveying\n${T}${T}remove_variable = ${v}_months\n${T}${T}remove_global_variable = ${v}_surveying\n${T}${T}set_global_variable = ${v}_surveyed\n${T}${T}change_variable = { name = ${ACTIVE} add = -1 }\n` +
    // PROBE BUILDS ONLY: is stage 1 constructible at the anchor, and (every n-th project) start it by force
    (P.probe ? `${T}${T}p:${p.anchor_province} = {\n${T}${T}${T}state = {\n` +
      `${T}${T}${T}${T}if = {\n${T}${T}${T}${T}${T}limit = { can_construct_building = building_dam_${p.id}_1 }\n${T}${T}${T}${T}${T}debug_log = "PMR_DAM|probe_can_build|${p.id}|yes|${DATE}"\n${T}${T}${T}${T}}\n` +
      `${T}${T}${T}${T}else = {\n${T}${T}${T}${T}${T}debug_log = "PMR_DAM|probe_can_build|${p.id}|no|${DATE}"\n${T}${T}${T}${T}}\n` +
      (P.probe.force_build_every && projects.indexOf(p) % P.probe.force_build_every === 0
        ? `${T}${T}${T}${T}start_building_construction = building_dam_${p.id}_1\n${T}${T}${T}${T}debug_log = "PMR_DAM|probe_forced|${p.id}|-|${DATE}"\n` : '') +
      `${T}${T}${T}}\n${T}${T}}\n` : '') +
    `${T}${T}debug_log = "PMR_DAM|survey_complete|${p.id}|${TAG}|${DATE}|${BUR}"\n${T}}\n\n` +
    `${T}current_value = {\n${T}${T}value = 0\n${T}${T}if = {\n${T}${T}${T}limit = { has_variable = ${v}_months }\n${T}${T}${T}value = root.var:${v}_months\n${T}${T}}\n${T}}\n\n${T}goal_add_value = {\n${T}${T}value = ${p.survey_months}\n${T}}\n\n` +
    `${T}invalid = {\n${T}${T}OR = {\n${T}${T}${T}NOT = { has_variable = ${v}_months }\n${T}${T}${T}NOT = {\n${T}${T}${T}${T}${chainOf(p).replace(/\n/g, `\n${T}${T}`)}\n${T}${T}${T}}\n${T}${T}}\n${T}}\n\n` +
    `${T}on_invalid = {\n${T}${T}if = {\n${T}${T}${T}limit = { has_variable = ${v}_months }\n${T}${T}${T}remove_variable = ${v}_months\n${T}${T}}\n` +
    `${T}${T}remove_global_variable = ${v}_surveying\n${T}${T}remove_modifier = ${v}_surveying\n${T}${T}change_variable = { name = ${ACTIVE} add = -1 }\n` +
    `${T}${T}debug_log = "PMR_DAM|survey_ended|${p.id}|${TAG}|${DATE}|${BUR}"\n${T}}\n\n` +
    `${T}progressbar = yes\n${T}weight = 10\n${T}transferable = no\n${T}should_be_pinned_by_default_uninvolved_or_context = no\n}`);
  loc.push([`je_${v}_survey`, `Surveying the ${p.name}`],
    [`je_${v}_survey_reason`, `Our engineers are surveying the ${p.name} in ${p.state_name}: river gauging, foundation borings and the reservoir line. When they finish, the site can be built by us or by any country in our overlord chain.`],
    [`je_${v}_survey_goal`, `Await the completion of the #bold ${p.survey_months} month#! survey`]);
}
W('common/buildings/zzz_pm_rehaul_dams.txt', HDR + bld.join('\n\n') + '\n');
W('common/production_methods/zzz_pm_rehaul_dams.txt', HDR + pms.join('\n\n') + '\n');
W('common/production_method_groups/zzz_pm_rehaul_dams.txt', HDR + pmgs.join('\n\n') + '\n');
W('common/static_modifiers/zzz_pm_rehaul_dams.txt', HDR + mods.join('\n\n') + '\n');
W('common/decisions/zzz_pm_rehaul_dams.txt', HDR + decs.join('\n\n') + '\n');
W('common/journal_entries/zzz_pm_rehaul_dams.txt', HDR + jes.join('\n\n') + '\n');
W('common/scripted_effects/zzz_pm_rehaul_dams.txt', HDR + seff.join('\n\n') + '\n');

// ---------------------------------------------------------------- traits and effects
const E = CFG.dams.effects || {};
const newTraits = E.traits || {};
const traitTxt = Object.entries(newTraits).map(([k, t]) =>
  `${k} = {\n${T}icon = "${t.icon || 'gfx/interface/icons/state_trait_icons/river.dds'}"\n\n${T}modifier = {\n` +
  Object.entries(t.modifier).map(([m, q]) => `${T}${T}${m} = ${q}\n`).join('') + `${T}}\n}`);
for (const [k, t] of Object.entries(newTraits)) loc.push([k, t.name], [`${k}_desc`, t.desc || '']);
if (traitTxt.length) W('common/state_traits/zzz_pm_rehaul_dam_traits.txt', HDR + traitTxt.join('\n\n') + '\n');

const regionEffect = (e) => {
  const lines = [];
  if (e.remove_trait) lines.push(`remove_state_trait = ${e.remove_trait}`);
  if (e.add_trait) lines.push(`add_state_trait = ${e.add_trait}`);
  if (e.arable) lines.push(`add_arable_land = ${e.arable}`);
  if (!stateProv[e.state]) die(`effect on unknown state ${e.state}`);
  return `s:${e.state} = {\n${T}${T}${T}${T}${lines.join(`\n${T}${T}${T}${T}`)}\n${T}${T}${T}}`;
};
const start = (E.start || []).map(e => `${T}${T}${regionEffect(e).replace(/\n\t/g, '\n')}`);
// PROBE BUILDS ONLY: grant the class technologies to named countries at the start, so an 1836 probe exercises
// the whole chain (config `dams.probe` = { grant_tags: [..], survey_months, cost_mult }).
if (P.probe?.grant_tags?.length) for (const tag of P.probe.grant_tags) {
  if (!/^[A-Z]{3}$/.test(tag)) die(`probe tag ${tag}`);
  start.push(`${T}${T}if = {\n${T}${T}${T}limit = { exists = c:${tag} }\n${T}${T}${T}c:${tag} = {\n` + [...new Set(Object.values(P.tech_by_class))].map(t => `${T}${T}${T}${T}add_technology_researched = ${t}\n`).join('') +
    `${T}${T}${T}${T}debug_log = "PMR_DAM|probe_grant|-|${TAG}|${DATE}"\n${T}${T}${T}}\n${T}${T}}`);
}
const onBuilt = [];
for (const p of projects) {
  for (let k = 1; k <= p.stages; k++) {
    const key = `building_dam_${p.id}_${k}`;
    // stages are built in parallel, so 'last' means "every stage of the project stands", fired once
    const fx = (p.effects || []).filter(e => e.stage !== 'last' && (e.stage || 1) === k);
    const fxAll = (p.effects || []).filter(e => e.stage === 'last');
    const allStages = Array.from({ length: p.stages }, (_, i) => `has_building = building_dam_${p.id}_${i + 1}`).join(' ');
    onBuilt.push(`${T}${T}${T}if = {\n${T}${T}${T}${T}limit = { is_building_type = ${key} }\n` +
      `${T}${T}${T}${T}owner ?= { debug_log = "PMR_DAM|built|${p.id}|${TAG}|${DATE}|stage ${k}/${p.stages}" }\n` +
      fx.map(e => `${T}${T}${T}${T}${regionEffect(e)}\n`).join('') +
      `${T}${T}${T}${T}if = {\n${T}${T}${T}${T}${T}limit = {\n${T}${T}${T}${T}${T}${T}NOT = { has_global_variable = ${V(p)}_complete }\n${T}${T}${T}${T}${T}${T}state = { ${allStages} }\n${T}${T}${T}${T}${T}}\n` +
      `${T}${T}${T}${T}${T}set_global_variable = ${V(p)}_complete\n${T}${T}${T}${T}${T}owner ?= { debug_log = "PMR_DAM|complete|${p.id}|${TAG}|${DATE}" }\n` +
      fxAll.map(e => `${T}${T}${T}${T}${T}${regionEffect(e)}\n`).join('') + `${T}${T}${T}${T}}\n${T}${T}${T}}`);
  }
}
W('common/on_actions/zzz_pm_rehaul_dams.txt', HDR +
  `on_game_started_after_lobby = {\n${T}on_actions = { pmr_dam_campaign_start }\n}\n\n` +
  `on_building_built = {\n${T}on_actions = { pmr_dam_built }\n}\n\n` +
  `pmr_dam_campaign_start = {\n${T}effect = {\n${T}${T}debug_log = "PMR_DAM|start|${projects.length} projects|-|${DATE}"\n${start.join('\n')}\n${T}}\n}\n\n` +
  `pmr_dam_built = {\n${T}effect = {\n${T}${T}if = {\n${T}${T}${T}limit = { is_building_group = bg_pmr_hydro_dams }\n${onBuilt.join('\n')}\n${T}${T}}\n${T}}\n}\n\n` +
  // the bureaucracy baseline around the survey events (user, 2026-09-26): once a year, every country that
  // holds the earliest dam technology, with how many dam surveys and dam stages it is running
  `on_yearly_pulse_country = {\n${T}on_actions = { pmr_dam_yearly }\n}\n\n` +
  `pmr_dam_yearly = {\n${T}effect = {\n${T}${T}if = {\n${T}${T}${T}limit = { has_technology_researched = ${P.tech_by_class.A} }\n` +
  `${T}${T}${T}debug_log = "PMR_DAM|bur_year|-|${TAG}|${DATE}|${BUR}|surveys [THIS.GetCountry.MakeScope.ScriptValue('pmr_dam_active')|0] building [THIS.GetCountry.MakeScope.ScriptValue('pmr_dam_building_now')|0]"\n${T}${T}}\n${T}}\n}\n\n` +
  // THE AI DRIVER (probes p1-p3). The government AI never queued a stage on its own, and it takes every visible decision
  // in one pass, so AI countries survey and build through this instead: every three months (a country cooldown), an AI
  // country that is not burdened starts at most ONE survey (while its surveys under way < pmr_dam_survey_slots) and at
  // most ONE stage (while its dam stages under construction < pmr_dam_build_slots, 1-6 by GDP), taking the first open
  // project in the table's order (largest first) in its own states or its subjects'. A stage is queued for the state's
  // OWNER (start_building_construction reaches no other queue). A subject additionally needs debt under 0.1 and a
  // positive income - "subjects step in if economically feasible"; an overlord only needs to be unburdened.
  `on_monthly_pulse_country = {\n${T}on_actions = { pmr_dam_driver }\n}\n\n` +
  `pmr_dam_driver = {\n${T}effect = {\n${T}${T}if = {\n${T}${T}${T}limit = {\n` +
  `${T}${T}${T}${T}is_player = no\n${T}${T}${T}${T}has_technology_researched = ${P.tech_by_class.A}\n${T}${T}${T}${T}NOT = { has_variable = pmr_dam_driver_cd }\n` +
  `${T}${T}${T}${T}is_at_war = no\n${T}${T}${T}${T}in_default = no\n${T}${T}${T}${T}scaled_debt < 0.5\n` +
  `${T}${T}${T}${T}OR = {\n${T}${T}${T}${T}${T}is_subject = no\n${T}${T}${T}${T}${T}AND = { scaled_debt < 0.1  net_fixed_income > 0 }\n${T}${T}${T}${T}}\n${T}${T}${T}}\n` +
  `${T}${T}${T}set_variable = { name = pmr_dam_driver_cd days = 90 }\n` +
  // surveys
  `${T}${T}${T}if = {\n${T}${T}${T}${T}limit = { pmr_dam_survey_headroom > 0 }\n` +
  projects.map((p, i) => `${T}${T}${T}${T}${i ? 'else_if' : 'if'} = {\n${T}${T}${T}${T}${T}limit = {\n${T}${T}${T}${T}${T}${T}${surveyOpen.get(p.id).replace(/\n/g, `\n${T}${T}${T}${T}`)}\n` +
    `${T}${T}${T}${T}${T}${T}produced_bureaucracy > ${p.survey_bureaucracy}\n${T}${T}${T}${T}${T}}\n${T}${T}${T}${T}${T}${V(p)}_begin_survey = yes\n${T}${T}${T}${T}}\n`).join('') +
  `${T}${T}${T}}\n` +
  // construction
  `${T}${T}${T}if = {\n${T}${T}${T}${T}limit = { pmr_dam_build_headroom > 0 }\n` +
  projects.map((p, i) => {
    // a stage is open when it is neither built nor already under construction, and constructible (probe p4: without the
    // second test the driver re-queued the same stage every quarter where the owner's queue never moved)
    const stageOk = k => `AND = { NOT = { has_building = building_dam_${p.id}_${k} } NOT = { any_scope_building = { is_building_type = building_dam_${p.id}_${k}  is_under_construction = yes } } can_construct_building = building_dam_${p.id}_${k} }`;
    const ks = Array.from({ length: p.stages }, (_, j) => j + 1);
    return `${T}${T}${T}${T}${i ? 'else_if' : 'if'} = {\n${T}${T}${T}${T}${T}limit = {\n${T}${T}${T}${T}${T}${T}has_global_variable = ${V(p)}_surveyed\n` +
      // a project just started is passed over for a year, so one stuck project cannot hold a country's queue
      `${T}${T}${T}${T}${T}${T}NOT = { has_global_variable = ${V(p)}_started_recently }\n` +
      `${T}${T}${T}${T}${T}${T}${chainOf(p).replace(/\n/g, `\n${T}${T}${T}${T}`)}\n` +
      `${T}${T}${T}${T}${T}${T}p:${p.anchor_province} = { state = { OR = { ${ks.map(stageOk).join(' ')} } } }\n${T}${T}${T}${T}${T}}\n` +
      `${T}${T}${T}${T}${T}debug_log = "PMR_DAM|stage_start|${p.id}|${TAG}|${DATE}|${BUR}"\n` +
      `${T}${T}${T}${T}${T}set_global_variable = { name = ${V(p)}_started_recently days = 365 }\n` +
      `${T}${T}${T}${T}${T}p:${p.anchor_province} = {\n${T}${T}${T}${T}${T}${T}state = {\n` +
      ks.map((k, j) => `${T}${T}${T}${T}${T}${T}${T}${j ? 'else_if' : 'if'} = {\n${T}${T}${T}${T}${T}${T}${T}${T}limit = { ${stageOk(k)} }\n` +
        `${T}${T}${T}${T}${T}${T}${T}${T}start_building_construction = building_dam_${p.id}_${k}\n${T}${T}${T}${T}${T}${T}${T}}\n`).join('') +
      `${T}${T}${T}${T}${T}${T}}\n${T}${T}${T}${T}${T}}\n${T}${T}${T}${T}}\n`;
  }).join('') +
  `${T}${T}${T}}\n${T}${T}}\n${T}}\n}\n`);
const gdpSlots = (tiers) => tiers.map(g => `${T}if = {\n${T}${T}limit = { gdp >= ${g} }\n${T}${T}add = 1\n${T}}\n`).join('');
W('common/script_values/zzz_pm_rehaul_dams.txt', HDR +
  `pmr_dam_bur_produced = {\n${T}value = produced_bureaucracy\n}\n\npmr_dam_bur_used = {\n${T}value = bureaucracy_usage\n}\n\n` +
  `pmr_dam_active = {\n${T}value = 0\n${T}if = {\n${T}${T}limit = { has_variable = ${ACTIVE} }\n${T}${T}value = var:${ACTIVE}\n${T}}\n}\n\n` +
  // dam stages under construction in the country's states
  `pmr_dam_building_now = {\n${T}value = 0\n${T}every_scope_state = {\n${T}${T}every_scope_building = {\n${T}${T}${T}limit = {\n${T}${T}${T}${T}is_building_group = bg_pmr_hydro_dams\n${T}${T}${T}${T}is_under_construction = yes\n${T}${T}${T}}\n${T}${T}${T}add = 1\n${T}${T}}\n${T}}\n}\n\n` +
  `pmr_dam_build_slots = {\n${T}value = 1\n${gdpSlots(P.ai.build_slot_gdp)}}\n\n` +
  `pmr_dam_survey_slots = {\n${T}value = 1\n${gdpSlots(P.ai.survey_slot_gdp)}}\n\n` +
  `pmr_dam_build_headroom = {\n${T}value = pmr_dam_build_slots\n${T}subtract = pmr_dam_building_now\n}\n\n` +
  `pmr_dam_survey_headroom = {\n${T}value = pmr_dam_survey_slots\n${T}subtract = pmr_dam_active\n}\n`);

// strip the vanilla hydro-narrative electricity lines (whole-file copies, every other line vanilla's)
const strip = CFG.dams.strip_trait_modifiers || {};
if (Object.keys(strip).length) {
  const dir = join(GAME, 'common/state_traits');
  const want = new Map(Object.entries(strip));
  const done = new Set();
  for (const f of readdirSync(dir)) {
    const raw = readFileSync(join(dir, f), 'utf8');
    const lines = stripBom(raw).split(/\r?\n/);
    let cur = null, depth = 0, changed = 0;
    const out = [];
    for (const l of lines) {
      const c = l.replace(/#.*$/, '');
      const m = depth === 0 && /^([a-z_0-9]+)\s*=\s*\{/.exec(c);
      if (m) cur = m[1];
      let drop = false;
      if (cur && want.has(cur) && depth >= 1) {
        for (const mod of want.get(cur)) if (new RegExp(`^\\s*${mod}\\s*=`).test(c)) { drop = true; done.add(cur + ':' + mod); }
      }
      if (drop) { out.push(l.replace(/^(\s*)/, '$1# pm_tech_rehaul (dams replace it): ')); changed++; }
      else out.push(l);
      for (const ch of c) { if (ch === '{') depth++; else if (ch === '}') depth--; }
      if (depth === 0) cur = null;
    }
    if (changed) W(`common/state_traits/${f}`, out.join('\n'));
  }
  for (const [t, ms] of want) for (const m of ms) if (!done.has(t + ':' + m)) die(`strip: ${t} has no ${m} line in vanilla`);
}

// ---------------------------------------------------------------- localization (English text in every language)
loc.push(['bg_pmr_hydro_dams', 'Hydroelectric Dams']);
const LANGS = CFG.languages || ['english'];
const esc = s => String(s).replace(/"/g, '\\"');
for (const lang of LANGS)
  W(`localization/${lang}/replace/zzz_pm_rehaul_dams_l_${lang}.yml`, `l_${lang}:\n` + loc.map(([k, s]) => ` ${k}:0 "${esc(s)}"`).join('\n') + '\n');

const stages = projects.reduce((s, p) => s + p.stages, 0);
const mw = projects.reduce((s, p) => s + p.mw, 0);
console.log(`dams: ${projects.length} projects, ${stages} stages, ${Math.round(mw)} MW -> ${projects.reduce((s, p) => s + p.stage_units * p.stages, 0)} electricity/week; ` +
  `power plant ${P.power_plant_points} pts (${P.coal_points_per_unit}/unit); ${loc.length} loc keys x ${LANGS.length} languages` +
  (P.probe ? `  ⚠ PROBE: ${JSON.stringify(P.probe)}` : ''));
