// EMIT THE INDUSTRY TECH TREE into a built mod (ROADMAP step 1).
//
//   node tools/emit_techs.mjs <modRoot>        # called by tools/build.ps1
//
// Reads config/tech_tree_options.json (generated by tools/tech_tree_spec.mjs) and writes the option
// marked `ships`. Nothing here decides design — that file does.
//
// ⚠⚠ EVERY VANILLA TRANSFORM BELOW **THROWS** WHEN ITS ANCHOR IS NOT FOUND. A silent no-op is the exact
// failure mode this project's landmine register exists for: the build succeeds, the mod loads, the game
// runs, and the change simply is not there. There is no "warn and continue" path on purpose.
//
// What gets written, and why each is the kind of file it is:
//   ADDITIVE (new keys, new filename — touches no vanilla file)
//     common/technology/technologies/zzz_pm_rehaul_techs.txt
//     common/defines/01_pm_rehaul_defines.txt          (defines are the one folder taking partials)
//     gfx/interface/icons/invention_icons/zzz_pm_rehaul_placeholder.dds
//     localization/<lang>/replace/zzz_pm_rehaul_tech_l_<lang>.yml
//   WHOLE-FILE, REGENERATED FROM VANILLA EACH BUILD (so a patch flows through, nothing is frozen)
//     common/technology/technologies/10_production.txt  — era moves + one prerequisite swap (+ ai_weight
//                                                         multiplier, only when the config sets one ≠ 1)
//     common/technology/technologies/20_military.txt    — era moves / ai_weight mult (only when any)
//     common/technology/technologies/30_society.txt     — era moves / ai_weight mult (only when any —
//                                                         NOT OWNED at the default 1; the hardcoded
//                                                         society ×0.8 died 2026-08-17, see AIW below)
//     common/scripted_effects/00_starting_inventions.txt— the 1836 grant, DERIVED from the 1836 map
//   NOT WRITTEN AT ALL
//     common/static_modifiers/*  — tech spread is exactly vanilla (user ruling 2026-08-12)
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const GAME = 'C:/Program Files (x86)/Steam/steamapps/common/Victoria 3/game';
const MOD = process.argv[2];
if (!MOD) { console.error('usage: node tools/emit_techs.mjs <modRoot> [configPath]'); process.exit(2); }
// ⚠⚠ THE CONFIG PATH IS AN ARGUMENT, AND IT USED TO BE HARDCODED — see emit_research_events.mjs for the
// full story. Here the consequence is the sharper one: an alternate-config build emitted that config's
// BUILDINGS but the canonical config's TECHNOLOGIES, so a tier present only in the alternate got no
// unlocking technology (a building nobody can ever construct) and a tier present only in the canonical
// got a technology unlocking a building that does not exist (an engine error at load).
const CFGPATH = process.argv[3] || join(REPO, 'config', 'mod_config.json');

// the tree follows the config, same suffix rule as every other derived artifact
const SFX = (() => {
  const raw = process.env.MOD_CONFIG || process.argv[3] || '';
  const bn = raw.split('\\').join('/').split('/').pop();
  const m = bn.match(/^mod_config\.(.+)\.json$/);
  return m ? '.' + m[1] : '';
})();
const TREE_PATH = join(REPO, 'config', 'tech_tree_options' + SFX + '.json');
const DATA = JSON.parse(readFileSync(TREE_PATH, 'utf8'));
const OPT = DATA.options.find(o => o.ships);
if (!OPT) throw new Error('no option is marked `ships` in config/tech_tree_options.json');
const CFG = JSON.parse(readFileSync(CFGPATH, 'utf8'));

// ⚠⚠ COVERAGE GUARD. `build.ps1` calls THIS file but never `tech_tree_spec.mjs`, so the tree data is not
// regenerated by a build and can fall behind the config it was derived from. Editing a recipe in the
// balance UI is harmless — each tier's `tech` lives in the config and the builder reads it directly — but
// ADDING a tier there produces a building no technology unlocks, and nothing would say so.
// ⚠ IT USED TO COMPARE MTIMES, AND THAT WAS BOTH TOO WEAK AND TOO STRONG. Too weak because a tree
// regenerated after an unrelated edit passes while still missing a tier; too strong because ANY config
// touched later trips it — an alternate config that differs only in a threshold was blocked outright,
// which is a false positive on the exact path that config exists for. It now checks the thing it cares
// about: every tier this build will EMIT must name a technology the shipping tree actually contains.
// ⚠ AND A TIER WITH NO TECHNOLOGY AT ALL IS NOT AN ERROR — that is how a building is made available from
// the 1836 start, which is exactly right for the pre-industrial era-0 rungs and for the vanilla basic
// port. The first version of this check threw on all ten of them. Only a tier that NAMES a technology
// can be wrong about it, so that is what throws; the start-available ones are counted and reported, so
// an accidental one is visible without blocking a legitimate build.
{
  const known = new Set(OPT.techs.map(t => t.id));
  const unknown = [], startAvail = [];
  for (const ind of CFG.industries || []) {
    if (ind.disabled) continue;
    for (const t of ind.tiers || []) {
      if (t.model_only) continue;                       // not emitted, so it needs no technology
      if (!t.tech) startAvail.push(`${ind.id}/${t.key}`);
      else if (!known.has(t.tech)) unknown.push(`${ind.id}/${t.key} -> ${t.tech}`);
    }
  }
  if (unknown.length) {
    throw new Error(
      `${unknown.length} emitted tier(s) name a technology the shipping tree does not contain, so the ` +
      `mod would carry buildings nothing can unlock:\n  ${unknown.join('\n  ')}\n` +
      `  Config: ${CFGPATH}\n  Fix: node tools/tech_tree_spec.mjs --write`);
  }
  console.log(`techs: ${startAvail.length} emitted tier(s) carry no unlocking technology (available at the ` +
    `1836 start): ${startAvail.join(', ') || '(none)'}`);
}

// ---- knobs that this step ships (ROADMAP step 1/2) ------------------------------------------------
// ⚠ RESTORED TO VANILLA 2026-08-12 (user ruling). It was 0.15 — lowered because the tree is deeper —
// and that made reaching era 5 early cheaper by design. Session 20260812_010659 measured the baseline
// production leader holding 12 of 17 era-5 technologies at 1935 with NO research events at all, against
// a design expectation of roughly a quarter by 1936. This factor is one candidate cause of that
// overshoot and the first to be tested; tree depth, era costs and spread have not been separated from it.
const AHEAD_OF_TIME = 0.25;        // NTechnology.TECH_AHEAD_OF_TIME_PENALTY_FACTOR, vanilla 0.25
// ⚠ THE PER-TREE SPREAD BOOST IS GONE — RESTORED TO VANILLA 2026-08-12 (user ruling). It shipped as
// `country_production_tech_spread_mult = 0.5` in base_values, a modifier vanilla does not set at all,
// and its whole job was to compensate a laggard for the deeper production tree. The ruling: the extra
// industry technologies are compensated "aplenty" by the research journal entries (ROADMAP step 2),
// which grant half an era's base cost per stage — so the spread boost was paying twice for the same
// depth, on the one lever that works AGAINST the mod's goal (spread only ever delivers what somebody
// else already has, so it cannot create a leader; it closes the gap the deeper tree exists to open).
// ⚠ THE KNOB STAYS IN THE TECH-TREE PAGE, defaulting to 0 for all three trees. It is how the question
// gets re-asked — the share of a tree handed to a laggard by 1936 against vanilla's own share — and
// deleting the instrument along with the setting would leave nothing to re-measure with.
// ⚠ AND WITH IT WE STOP OWNING `00_code_static_modifiers.txt`. That one line was the only difference
// from vanilla in a 900-line file, and the repo's rule is that a file we would copy verbatim is not
// emitted: owning it freezes that file against the next patch and ships bytes we did not author.
// ⭐ PER-TREE AI RESEARCH-WEIGHT MULTIPLIERS — config-backed, DEFAULT 1 FOR ALL TREES (user-ruled
// 2026-08-17): the research journal entries are boost enough, so no tree is damped or favoured by
// default. A tree at 1 emits NOTHING for this knob — at the defaults we stop owning 30_society.txt
// entirely. Set `tech_ai_weight_mult` in the config ({production, military, society}) and the
// multiplier is appended inside every vanilla technology's ai_weight in that tree's file, and becomes
// the flat weight of OUR new technologies in that tree. Displayed beside the spread panel on the
// tech-tree page. Replaces the hardcoded SOCIETY_AI_WEIGHT = 0.8 (2026-08-11 ruling, superseded).
const AIW = Object.assign({ production: 1, military: 1, society: 1 }, CFG.tech_ai_weight_mult || {});
delete AIW._comment;
for (const [k, v] of Object.entries(AIW)) {
  if (!['production', 'military', 'society'].includes(k)) throw new Error(`tech_ai_weight_mult: unknown tree '${k}'`);
  if (!(typeof v === 'number' && v > 0)) throw new Error(`tech_ai_weight_mult.${k} = ${v} — must be a positive number`);
}
// ⭐ WHERE VANILLA MANDATES A TECHNOLOGY ONE BY ONE, WE REPEAT IT AND ADD NOTHING (user ruling
// 2026-08-12). Read LIVE from vanilla's own starting-inventions file rather than listed here, so a patch
// that adds or drops a named grant flows straight through — and so we can never re-grant something
// vanilla already grants. ⚠ It also means we notice: `sub()` throws if the file's shape moves.
const VAN_STARTING_NAMED = new Set(
  [...readFileSync(join(GAME, 'common/scripted_effects/00_starting_inventions.txt'), 'utf8')
    .matchAll(/add_technology_researched\s*=\s*([a-z_0-9-]+)/g)].map(m => m[1]));
if (VAN_STARTING_NAMED.size < 30)
  throw new Error(`emit_techs: only ${VAN_STARTING_NAMED.size} named starting technologies parsed from vanilla — the file shape moved`);
const PLACEHOLDER = 'gfx/interface/icons/invention_icons/zzz_pm_rehaul_placeholder.dds';

const BOM = '\uFEFF';
const out = [];
function write(rel, text, bom = true) {
  const p = join(MOD, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, (bom ? BOM : '') + text, 'utf8');
  out.push(rel);
}
function writeBin(rel, buf) {
  const p = join(MOD, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, buf);
  out.push(rel);
}
const vanilla = rel => readFileSync(join(GAME, rel), 'utf8').replace(/^\uFEFF/, '');
// Replace exactly `n` occurrences or throw. The count is the point: a pattern that suddenly matches
// twice is as broken as one that stops matching.
function sub(text, re, repl, n, what) {
  const hits = text.match(re);
  const got = hits ? (re.global ? hits.length : 1) : 0;
  if (got !== n) throw new Error(`emit_techs: ${what} — expected ${n} match(es), found ${got}. ` +
    `Vanilla has changed shape; fix the transform rather than shipping a silent no-op.`);
  return text.replace(re, repl);
}

// ===================================================================================================
// 1. THE NEW TECHNOLOGIES — additive
// ===================================================================================================
const NEWT = OPT.techs.filter(t => t.origin === 'new');
{
  const L = ['# AUTO-GENERATED by tools/emit_techs.mjs — do not edit by hand.',
    `# ${NEWT.length} technologies for the PM & Tech Rehaul ladder. Design lives in tools/tech_tree_spec.mjs.`, ''];
  for (const t of NEWT.slice().sort((a, b) => a.category.localeCompare(b.category) || a.era - b.era || a.id.localeCompare(b.id))) {
    L.push(`${t.id} = {`);
    if (t.unlocks.length) L.push(`\t# Unlocks ${t.unlocks.map(u => u.name).join(', ')}`);
    L.push(`\tera = era_${t.era}`);
    L.push(`\ttexture = "${PLACEHOLDER}"`);
    L.push(`\tcategory = ${t.category}`);
    if (t.prereqs.length) {
      L.push('\tunlocking_technologies = {');
      for (const p of t.prereqs) L.push(`\t\t${p}`);
      L.push('\t}');
    }
    if (t.mod && Object.keys(t.mod).length) {
      L.push('\tmodifier = {');
      for (const [k, v] of Object.entries(t.mod)) L.push(`\t\t${k} = ${v}`);
      L.push('\t}');
    }
    L.push('\tai_weight = {');
    L.push(`\t\tvalue = ${AIW[t.category] ?? 1}`);
    L.push('\t}');
    L.push('}', '');
  }
  write('common/technology/technologies/zzz_pm_rehaul_techs.txt', L.join('\n'));
}

// Append `multiply = <mult>` inside every technology's ai_weight in a vanilla tree file — multiplied,
// not overwritten: vanilla authored real relative weights (2 and 3 on the techs it wants the AI to
// rush) and flattening them to a constant would throw that away. `multiply` lands LAST, after the
// conditional `add`s. A technology with NO ai_weight block at all gets `ai_weight = { value = <mult> }`
// (the engine default weight is 1, so value = mult is the same damping) — society techs happen to
// always carry one, but production and military do not, and this serves all three trees.
function applyAiWeightMult(txt, mult, label) {
  const starts = [...txt.matchAll(/^([a-z_0-9-]+) = \{$/gm)].map(m => ({ id: m[1], at: m.index }));
  let done = 0;
  for (let i = starts.length - 1; i >= 0; i--) {          // backwards, so earlier offsets stay valid
    const from = starts[i].at, to = i + 1 < starts.length ? starts[i + 1].at : txt.length;
    let block = txt.slice(from, to);
    const aw = block.indexOf('\tai_weight = {');
    if (aw < 0) {
      const close = block.lastIndexOf('\n}');             // column-0 close = the technology's own brace
      if (close < 0) throw new Error(`emit_techs: cannot find the closing brace of ${label} technology ${starts[i].id}`);
      block = block.slice(0, close) + `\n\tai_weight = {\n\t\tvalue = ${mult}\n\t}` + block.slice(close);
    } else {
      // brace-match from the opening of ai_weight to its close
      let d = 0, end = -1;
      for (let k = aw; k < block.length; k++) {
        if (block[k] === '{') d++;
        else if (block[k] === '}') { d--; if (d === 0) { end = k; break; } }
      }
      if (end < 0) throw new Error(`emit_techs: unbalanced ai_weight in ${label} technology ${starts[i].id}`);
      block = block.slice(0, end) + `\n\t\tmultiply = ${mult}\n\t` + block.slice(end);
    }
    txt = txt.slice(0, from) + block + txt.slice(to);
    done++;
  }
  if (done !== starts.length) throw new Error(`emit_techs: multiplied ${done} of ${starts.length} ${label} technologies`);
  console.log(`  ${label} ai_weight ×${mult} applied to ${done} technologies`);
  return txt;
}

// ===================================================================================================
// 2. VANILLA PRODUCTION FILE — era moves, one prerequisite swap, ai_weight mult when set
// ===================================================================================================
{
  let txt = vanilla('common/technology/technologies/10_production.txt');
  // Re-era'd technologies, each with the reason the spec recorded.
  // ⚠ VANILLA ONES ONLY. `reEra` records that the spec moved a technology, and since the ladder-era
  // alignment (2026-08-12) most of the moved ones are technologies WE ADD — those get their era written
  // directly in section 1, and they have no block in the vanilla file to patch. Without the origin
  // filter this searched 10_production.txt for `regenerative_furnace` and, finding nothing, threw. That
  // throw is the guardrail working: a transform that matches nothing must fail rather than no-op.
  const eraMoves = OPT.techs.filter(t => t.reEra && t.category === 'production' && t.origin === 'vanilla');
  for (const t of eraMoves) {
    // anchor on the tech's own block so we cannot hit another tech's era line
    const re = new RegExp(`(^${t.id} = \\{[\\s\\S]*?\\n\\tera = era_)\\d`, 'm');
    txt = sub(txt, re, `$1${t.era}`, 1, `re-era ${t.id} -> era ${t.era}`);
  }
  // `aniline` moved to era 2 and can no longer wait on `rubber_mastication`, which is era 3.
  txt = sub(txt, /(^aniline = \{[\s\S]*?unlocking_technologies = \{)[^}]*(\})/m,
    '$1\n\t\tchemical_bleaching\n\t$2', 1, 'aniline prerequisite swap');
  if (AIW.production !== 1) txt = applyAiWeightMult(txt, AIW.production, 'production');
  write('common/technology/technologies/10_production.txt', txt);
}

// ===================================================================================================
// 2b. VANILLA MILITARY FILE — era moves
// ===================================================================================================
// ⚠ THIS FILE EXISTED AS A GAP UNTIL 2026-08-12. Section 2 patches ONLY 10_production.txt, so a re-era
// on a MILITARY technology was written into the spec, reported by the viewer, and then silently
// dropped on the way to the mod — the tree the game loaded would disagree with the tree the sheet drew,
// with nothing failing anywhere. The ladder-era alignment moves three of them (repeaters,
// breech_loading_artillery, bolt_action_rifles: arms and artillery are military-tree industries by user
// ruling), which is what surfaced it.
// ⚠ THE LOOP IS DELIBERATELY UNCONDITIONAL — it runs even when the list is empty, and `sub` throws when
// a transform matches nothing. A `if (moves.length)` guard here would make an empty list and a broken
// pattern look identical.
{
  const moves = OPT.techs.filter(t => t.reEra && t.category === 'military' && t.origin === 'vanilla');
  if (moves.length || AIW.military !== 1) {
    let txt = vanilla('common/technology/technologies/20_military.txt');
    for (const t of moves) {
      const re = new RegExp(`(^${t.id} = \\{[\\s\\S]*?\\n\\tera = era_)\\d`, 'm');
      txt = sub(txt, re, `$1${t.era}`, 1, `re-era ${t.id} -> era ${t.era}`);
    }
    if (AIW.military !== 1) txt = applyAiWeightMult(txt, AIW.military, 'military');
    write('common/technology/technologies/20_military.txt', txt);
  }
}

// ===================================================================================================
// 3. VANILLA SOCIETY FILE — era moves / ai_weight mult (only when there are any)
// ===================================================================================================
// Mirrors 2b, for the same reason 2b exists: a change routed at a tree with no emission path would be
// written into the spec, drawn by the viewer, and silently dropped on the way to the mod. At the
// default tech_ai_weight_mult.society = 1 with no society era moves this file is NOT OWNED at all —
// the hardcoded ×0.8 damping (2026-08-11) was superseded 2026-08-17: no tree is damped by default,
// the research journal entries being boost enough.
{
  const moves = OPT.techs.filter(t => t.reEra && t.category === 'society' && t.origin === 'vanilla');
  if (moves.length || AIW.society !== 1) {
    let txt = vanilla('common/technology/technologies/30_society.txt');
    for (const t of moves) {
      const re = new RegExp(`(^${t.id} = \\{[\\s\\S]*?\\n\\tera = era_)\\d`, 'm');
      txt = sub(txt, re, `$1${t.era}`, 1, `re-era ${t.id} -> era ${t.era}`);
    }
    if (AIW.society !== 1) txt = applyAiWeightMult(txt, AIW.society, 'society');
    write('common/technology/technologies/30_society.txt', txt);
  } else {
    console.log('  society file not owned — no era moves and tech_ai_weight_mult.society = 1 (vanilla)');
  }
}

// ===================================================================================================
// 4. STARTING TECHNOLOGIES — the 1836 sets
// ===================================================================================================
// Tiers 1 and 2 call `add_era_researched = era_1` and so pick up every new era-1 technology for free.
// Tiers 3-5 list technologies by name, so a country that starts with, say, a calico works would
// otherwise own a building it could not have built. Tier 6 holds `enclosure` alone and tier 7 nothing;
// both are left as they are, deliberately — those countries are meant to have no industry.
// ⭐⭐ THE GRANT IS DERIVED FROM THE 1836 MAP, ONE TECHNOLOGY AT A TIME (user ruling 2026-08-12).
// THE RULE: *every production method vanilla runs in 1836 stays, and the country running it holds the
// technology that unlocks it.* Nothing else. So for each of OUR tier buildings that actually stands on
// the 1836 map, we take the starting tiers of the countries that own one, and grant that tier building's
// technology to exactly those tiers — minus whatever vanilla's own `add_era_researched` already covers.
// ⚠ THE BLANKET IS THE THING THIS REPLACES. It used to hand every NEW era-1 production technology to
// tiers 3, 4 and 5 by name, on the reasoning that a country starting with a calico works must be able to
// build one. True — but only two of those 213 countries start with anything of the kind. Tier 4 and
// tier 5 (166 countries) needed NONE of the four, and tier 3 needed one of them. Handing Leblanc soda
// and Fourdrinier paper machines to every backward state in the world is not "close to vanilla", it is
// a blanket wearing a justification.
// ⚠ TIERS 1 AND 2 KEEP VANILLA'S OWN `add_era_researched = era_1`, so anything of ours at era 1 reaches
// them regardless — that line is vanilla's and removing it would strip vanilla technologies, which the
// rule above forbids. The consequence is a small, deliberate over-grant: tier 2 gets `fourdrinier_machine`
// and `leblanc_process` without a tier-2 country owning either. Closing that would mean either dropping
// vanilla's blanket or dating two genuinely pre-1836 technologies into era 2; both are worse.
// ⚠ TIER GRANULARITY, not per country — vanilla's own structure. Spain and Mexico need beet sugar, so
// all 47 tier-3 countries get it. Per-country precision is possible (a `limit` block inside the tier
// effect) and is deliberately not done yet.
// ⚠ THE SOURCE IS `config/start_baseline.json`, the inventory extract_start.ps1 makes from the vanilla
// 1836 start — which is why build.ps1 runs that BEFORE this. Reading a baseline from the previous build
// would derive this build's grant from the last one's map.
// ⚠ AND IT IS GUARDED: landmine L14 (`verify_start_techs.mjs --vs-vanilla`, inside preflight) fails the
// build if any country ends up owning a building its own technologies cannot unlock. An under-grant here
// cannot ship silently.
{
  let txt = vanilla('common/scripted_effects/00_starting_inventions.txt');

  // which starting tier does each country belong to?
  const cTier = {};
  for (const f of readdirSync(join(GAME, 'common/history/countries'))) {
    if (!f.endsWith('.txt')) continue;
    const t = readFileSync(join(GAME, 'common/history/countries', f), 'utf8').replace(/^﻿/, '');
    for (const m of t.matchAll(/c:([A-Z_0-9]{2,4})\s*\??=\s*\{/g)) {
      let i = t.indexOf('{', m.index) + 1, d = 1;
      while (i < t.length && d > 0) { if (t[i] === '{') d++; else if (t[i] === '}') d--; i++; }
      const e = t.slice(m.index, i).match(/effect_starting_technology_tier_(\d)_tech/);
      if (e) cTier[m[1]] = +e[1];
    }
  }
  if (Object.keys(cTier).length < 100)
    throw new Error(`emit_techs: only ${Object.keys(cTier).length} countries have a starting tier — the history parse is wrong`);

  // what does the 1836 map need, per starting tier?
  const basePath = join(REPO, 'config', 'start_baseline.json');
  const baseline = JSON.parse(readFileSync(basePath, 'utf8').replace(/^﻿/, ''));
  if (!baseline.factories?.length) throw new Error(`emit_techs: ${basePath} carries no factories`);
  const eraOf = Object.fromEntries(OPT.techs.map(t => [t.id, t.era]));
  const ERA_GRANTED = { 1: 1, 2: 1 };            // tiers 1 and 2 call add_era_researched = era_1
  const needByTier = {};                          // tier -> Set(tech)
  const whoNeeds = {};                            // tech -> tier -> Set(tag), for the report
  for (const f of baseline.factories) {
    const ind = CFG.industries.find(i => i.id === f.industry);
    const tier = ind?.tiers[f.tier - 1];
    if (!tier?.tech) continue;
    const st = cTier[f.country];
    if (st == null) continue;
    ((whoNeeds[tier.tech] ||= {})[st] ||= new Set()).add(f.country);
    if (eraOf[tier.tech] != null && eraOf[tier.tech] <= (ERA_GRANTED[st] ?? 0)) continue;   // already covered
    if (VAN_STARTING_NAMED.has(tier.tech)) continue;                                        // vanilla names it itself
    (needByTier[st] ||= new Set()).add(tier.tech);
  }

  // ⭐⭐ AND THE WIDER PREDICATE (user ruling 2026-08-12): match vanilla on what a country COULD BUILD,
  // not only on what it already owns — "even if it's e2 in our era". A tier that vanilla let a country
  // construct on day one stays constructible on day one. Same rule, wider test, still derived.
  // vanilla's own gates: the BUILDING's as well as the METHOD's. Most of these vanilla PMs carry no
  // unlocking_technologies at all and the building is what is gated, so reading the PM alone concludes
  // vanilla let everyone build everything.
  // ⚠ THE ID CLASS MUST ADMIT A HYPHEN. `pm_ammonia-soda_process`, `pm_coal-fired_plant` and
  // `pm_oil-fired_plant` are all `vanilla_pm` values of our tiers, and an [a-z_0-9]+ class does not open
  // their blocks at all — so their gate reads as EMPTY, i.e. "vanilla let anyone run this", and the rule
  // grants a technology nobody needs. That mis-read once produced a confident claim that tier 1 lost the
  // ammonia-soda explosives rung; vanilla gates it on `nitroglycerin`, which tier 1 never has.
  {
    const ID = '[A-Za-z_0-9-]+';
    const blk = txt2 => { const o = {}; const re = new RegExp('^(' + ID + ')\\s*=\\s*\\{', 'gm'); let m;
      while ((m = re.exec(txt2))) { let i = re.lastIndex, d = 1;
        while (i < txt2.length && d > 0) { if (txt2[i] === '{') d++; else if (txt2[i] === '}') d--; i++; }
        o[m[1]] = txt2.slice(re.lastIndex, i - 1); } return o; };
    const gt = b => { const u = b.match(/unlocking_technologies\s*=\s*\{([^}]*)\}/); return u ? u[1].trim().split(/\s+/).filter(Boolean) : []; };
    const dirTxts = d => readdirSync(join(GAME, d)).filter(f => f.endsWith('.txt')).map(f => readFileSync(join(GAME, d, f), 'utf8').replace(/^﻿/, ''));
    const vpm = {}, vb = {}, vEra = {};
    for (const t of dirTxts('common/production_methods')) for (const [k, v] of Object.entries(blk(t))) vpm[k] = gt(v);
    for (const t of dirTxts('common/buildings')) for (const [k, v] of Object.entries(blk(t))) vb[k] = gt(v);
    for (const t of dirTxts('common/technology/technologies')) for (const [k, v] of Object.entries(blk(t))) {
      const e = v.match(/\bera\s*=\s*era_(\d)/); if (e) vEra[k] = +e[1];
    }
    if (Object.keys(vpm).length < 400) throw new Error(`emit_techs: only ${Object.keys(vpm).length} vanilla PMs parsed`);
    // vanilla's own starting sets, era shorthand expanded against VANILLA's eras
    const vTier = {};
    for (const [k, v] of Object.entries(blk(readFileSync(join(GAME, 'common/scripted_effects/00_starting_inventions.txt'), 'utf8').replace(/^﻿/, '')))) {
      const m = k.match(/^effect_starting_technology_tier_(\d)_tech$/); if (!m) continue;
      const s = new Set([...v.matchAll(/add_technology_researched\s*=\s*([a-z_0-9-]+)/g)].map(x => x[1]));
      for (const e of v.matchAll(/add_era_researched\s*=\s*era_(\d)/g))
        for (const [t, er] of Object.entries(vEra)) if (er <= +e[1]) s.add(t);
      vTier[+m[1]] = s;
    }
    for (const ind of CFG.industries || []) {
      const bg = vb[ind.tiers?.[0]?.key] || [];
      for (const t of ind.tiers || []) {
        if (t.model_only || !t.vanilla_pm || !t.tech) continue;
        const vanillaNeeds = [...new Set([...bg, ...(vpm[t.vanilla_pm] || [])])];
        for (const st of Object.keys(vTier).map(Number)) {
          if (!vanillaNeeds.every(x => vTier[st].has(x))) continue;      // vanilla did not allow it either
          if (eraOf[t.tech] != null && eraOf[t.tech] <= (ERA_GRANTED[st] ?? 0)) continue;
          if (VAN_STARTING_NAMED.has(t.tech)) continue;
          (needByTier[st] ||= new Set()).add(t.tech);
        }
      }
    }
  }

  for (const st of Object.keys(needByTier).map(Number).sort()) {
    const add = [...needByTier[st]].sort().map(id => `\tadd_technology_researched = ${id}\n`).join('');
    const re = new RegExp(`(effect_starting_technology_tier_${st}_tech = \\{\\n)`, 'm');
    txt = sub(txt, re, `$1${add}`, 1, `1836 map grant, tier ${st}`);
    out.push(`  tier ${st}: ${[...needByTier[st]].sort().join(', ')}`);
  }
  // A rule that grants nothing is a rule that silently stopped working — the 1836 map contains steel
  // tooling workshops and beet-sugar refineries, and it always will.
  if (!Object.keys(needByTier).length)
    throw new Error('emit_techs: the 1836 map needed no technology grant at all — that cannot be right');

  // ⭐⭐ PER-COUNTRY GRANTS (config `start_tech_grants`) — the one thing the derived rule above CANNOT see.
  // That derivation reads the VANILLA map (`start_baseline.json`), so a building placed by
  // `config/start_exceptions.json` is invisible to it: seeding the Netherlands a steam port makes NET own
  // a building gated on a technology it does not hold, and the only thing that would notice is landmine
  // L14 — failing the build rather than fixing it. This is where a SEED declares the technology it needs.
  // ⚠ IT IS EMITTED AS A GUARD INSIDE THE COUNTRY'S OWN STARTING-TIER EFFECT, because that effect is what
  // vanilla's country history actually calls, with `this` bound to the country. A free-standing block
  // would be dead code — nothing in vanilla would ever call it.
  // ⚠⚠ `verify_start_techs.mjs` parses THIS EXACT SHAPE and attributes the grant to the named tag only.
  // A blanket `add_technology_researched` regex over the tier body would credit EVERY country of that
  // tier with it — an over-reporting detector, which is precisely the hole L14 exists to close. Emitter
  // and detector are coupled on this format; change one and the other must follow.
  const grants = CFG.start_tech_grants || {};
  const knownTech = new Set(OPT.techs.map(t => t.id));
  for (const [tag, techs] of Object.entries(grants)) {
    const st = cTier[tag];
    if (st == null) throw new Error(`start_tech_grants: ${tag} has no starting technology tier in vanilla history`);
    for (const id of techs) if (!knownTech.has(id))
      throw new Error(`start_tech_grants: ${tag} asks for '${id}', which is not a technology in the shipping tree`);
    const lines = techs.map(id => `\t\tadd_technology_researched = ${id}\n`).join('');
    const body = `\tif = {\n\t\tlimit = { this = c:${tag} }\n${lines}\t}\n`;
    const re = new RegExp(`(effect_starting_technology_tier_${st}_tech = \\{\\n)`, 'm');
    txt = sub(txt, re, `$1${body}`, 1, `per-country grant ${tag}`);
    out.push(`  ${tag} (starting tier ${st}, per-country): ${techs.join(', ')}`);
  }

  // ⚠ THE STEEL-TOOLING CASE, which is why this rule exists at all. Vanilla gates a steel tooling
  // workshop on `mechanical_tools` — a technology vanilla itself NAMES in the tier-1/2 grant, because its
  // own 1836 map runs buildings the calendar would forbid — so vanilla's great powers run steel tooling and
  // 16 of the map's 35 tooling workshops do. Our ladder replaced that gate with `steel_toolmaking` (1865,
  // requiring `bessemer_process`), so converting those workshops faithfully produced five great powers
  // owning a building their own technologies could not unlock. The derived grant above now finds this by
  // itself, from the map, instead of naming it by hand — and finds nothing for tier 2, which the hand
  // version granted anyway.
  // ⚠ It was INVISIBLE until landmine L13 was fixed: while the converter silently failed to re-tier those
  // workshops they stayed on the base rung and nothing was gated wrongly. verify_start_techs.mjs found it
  // one build after the conversion started working.
  write('common/scripted_effects/00_starting_inventions.txt', txt);
}

// ===================================================================================================
// 5. STATIC MODIFIERS — NOTHING. Tech spread is left exactly as vanilla sets it.
// ===================================================================================================
// This step used to emit a whole copy of `common/static_modifiers/00_code_static_modifiers.txt` for one
// added line, `country_production_tech_spread_mult = 0.5`. Removed by user ruling 2026-08-12 — see the
// note on the knobs above. Nothing replaces it: the file is not ours, and the tech-tree page's spread
// panel now opens on the vanilla setting for all three trees.
// ⚠ A global boost had already been measured and rejected (it handed 69% of the society tree to a
// laggard against vanilla's 44%); the production-only form is what this ruling removes.

// ===================================================================================================
// 6. DEFINES — the ahead-of-time penalty (partial override; the one folder that allows it)
// ===================================================================================================
write('common/defines/01_pm_rehaul_defines.txt',
  '# AUTO-GENERATED by tools/emit_techs.mjs — do not edit by hand.\n' +
  '# Defines take a PARTIAL override: only the keys named here change, the rest of NTechnology and the\n' +
  '# rest of 00_defines.txt stay vanilla. See MODDING_NOTES -> File loading & override semantics.\n' +
  'NTechnology = {\n' +
  `\tTECH_AHEAD_OF_TIME_PENALTY_FACTOR = ${AHEAD_OF_TIME}\t# vanilla 0.25; the tree is deeper\n` +
  '}\n');

// ===================================================================================================
// 7. PLACEHOLDER ICON — a real DDS, minted here, no art and no image library
// ===================================================================================================
// Vanilla's invention icons are 256x256 32-bit A8R8G8B8 with 9 mipmaps. Mipmaps are optional and a
// single surface is a legal DDS, so this is a 128-byte header plus raw BGRA. Deliberately ONE shared
// file rather than one per technology: it makes "no art yet" obvious at a glance, and it is 256 KB
// instead of ten megabytes. Step 7 replaces it.
{
  const N = 256, hdr = Buffer.alloc(128);
  hdr.write('DDS ', 0, 'ascii');
  hdr.writeUInt32LE(124, 4);
  hdr.writeUInt32LE(0x1 | 0x2 | 0x4 | 0x8 | 0x1000, 8);
  hdr.writeUInt32LE(N, 12); hdr.writeUInt32LE(N, 16); hdr.writeUInt32LE(N * 4, 20);
  hdr.writeUInt32LE(32, 76); hdr.writeUInt32LE(0x41, 80); hdr.writeUInt32LE(32, 88);
  hdr.writeUInt32LE(0x00ff0000, 92); hdr.writeUInt32LE(0x0000ff00, 96);
  hdr.writeUInt32LE(0x000000ff, 100); hdr.writeUInt32LE(0xff000000, 104);
  hdr.writeUInt32LE(0x1000, 108);
  const px = Buffer.alloc(N * N * 4);
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const cross = Math.abs(x - y) < 14 || Math.abs(x + y - (N - 1)) < 14;
    const edge = x < 8 || y < 8 || x > N - 9 || y > N - 9;
    const [r, g, b] = cross || edge ? [200, 30, 30] : [240, 200, 40];
    const o = (y * N + x) * 4;
    px[o] = b; px[o + 1] = g; px[o + 2] = r; px[o + 3] = 255;   // BGRA
  }
  writeBin(PLACEHOLDER, Buffer.concat([hdr, px]));
}

// ===================================================================================================
// 8. LOCALIZATION — new names and descriptions, plus the renamed vanilla technologies
// ===================================================================================================
{
  const esc = s => String(s).replace(/"/g, '\\"');
  const body = [];
  for (const t of NEWT) {
    body.push(` ${t.id}:0 "${esc(t.name)}"`);
    if (t.desc) body.push(` ${t.id}_desc:0 "${esc(t.desc)}"`);
  }
  // Renamed vanilla technologies. `replace/` hard-overwrites the vanilla key.
  const renamed = OPT.techs.filter(t => t.renamed);
  for (const t of renamed) body.push(` ${t.id}:0 "${esc(t.name)}"`);
  console.log(`  localization: ${NEWT.length} new technologies + ${renamed.length} renamed vanilla ones`);
  for (const lang of CFG.languages) {
    write(`localization/${lang}/replace/zzz_pm_rehaul_tech_l_${lang}.yml`,
      `l_${lang}:\n# AUTO-GENERATED by tools/emit_techs.mjs — English strings are used as stubs for all languages.\n` +
      body.join('\n') + '\n');
  }
}

console.log(`  emit_techs: ${NEWT.length} new technologies, ${out.length} files -> ${MOD}`);
