<#
  PM & Tech Rehaul - vanilla building/PMG/PM extractor.

  Dumps the WHOLE vanilla building economy (every building, production_method_group and
  production_method) into ui/vanilla.js as `window.PMVANILLA`, so the balance UI can show every
  building as a PM-selection explorer (see the `include_all_buildings` toggle in mod_config.json).

  This is READ-ONLY reference data: it re-reads the live game each run, so a patch is a one-command
  refresh. It does NOT touch config or the mod. build.ps1 runs it when include_all_buildings is set.

  Output shape (all keys are the vanilla ids):
    window.PMVANILLA = {
      buildings: { building_x: { group, unique(bool), tech, city, pmgs:[...] }, ... },
      pmgs:      { pmg_x: { pms:[...] }, ... },
      pms:       { pm_x: { in:{good:qty}, out:{good:qty}, emp:{pop:qty}, mods:{name:val}, gated?:true }, ... }
                 (gated = power-bloc-gated: has unlocking_principles; the UI never defaults to it)
    }

  Usage:  powershell -ExecutionPolicy Bypass -File tools\extract_vanilla.ps1 [-Game "<...\Victoria 3\game>"]
#>
param(
    [string]$Repo = (Split-Path $PSScriptRoot -Parent),
    [string]$Game = $(if ($env:VIC3_GAME) { $env:VIC3_GAME } else { "C:\Program Files (x86)\Steam\steamapps\common\Victoria 3\game" })
)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'history_lib.ps1')   # Get-TopBlocks / Get-ListTokens

# --- buildings ---
$bBlocks = Get-TopBlocks (Join-Path $Game 'common\buildings') 'building_'
$buildings = [ordered]@{}
foreach ($name in $bBlocks.Keys) {
    $blk = $bBlocks[$name]; $joined = ($blk -join " ")
    $group  = if ($joined -match 'building_group\s*=\s*(bg_[A-Za-z0-9_]+)') { $Matches[1] } else { $null }
    $unique = [bool]($joined -match 'unique\s*=\s*yes')
    $tech   = if ($joined -match 'unlocking_technologies\s*=\s*\{\s*([A-Za-z0-9_]+)') { $Matches[1] }
              elseif ($joined -match 'unlocking_technologies\s*=\s*\{[^}]*\b([A-Za-z0-9_]+)\b') { $Matches[1] } else { $null }
    $city   = if ($joined -match 'city_type\s*=\s*([A-Za-z0-9_]+)') { $Matches[1] } else { $null }
    # base ai_value: a scalar `ai_value = N`, or the `value = N` at the head of an `ai_value = { … }` block.
    # $null when unscripted (engine default 1000). Used only for the UI's ai_value default display.
    $aiv = if ($joined -match 'ai_value\s*=\s*(-?\d+)') { [int]$Matches[1] }
           elseif ($joined -match 'ai_value\s*=\s*\{\s*value\s*=\s*(-?\d+)') { [int]$Matches[1] } else { $null }
    $pmgs   = @(Get-ListTokens $blk 'production_method_groups' 'pmg_')
    $buildings[$name] = [ordered]@{ group = $group; unique = $unique; tech = $tech; city = $city; ai_value = $aiv; pmgs = $pmgs }
}

# --- pmgs ---
$gBlocks = Get-TopBlocks (Join-Path $Game 'common\production_method_groups') 'pmg_'
$pmgs = [ordered]@{}
foreach ($name in $gBlocks.Keys) {
    # PM names are NOT all pm_-prefixed (plantations/farms use default_/automatic_/worker_/slave_/… ,
    # e.g. default_building_cotton_plantation), so capture every token in the production_methods list.
    $pmgs[$name] = [ordered]@{ pms = @(Get-ListTokens $gBlocks[$name] 'production_methods' '') }
}

# --- pms (goods in/out, employment, and other *_add modifiers) ---
# Every top-level block in a production_methods file IS a PM, whatever its name prefix (see above).
$pBlocks = Get-TopBlocks (Join-Path $Game 'common\production_methods') ''
$pms = [ordered]@{}
foreach ($name in $pBlocks.Keys) {
    $in = [ordered]@{}; $out = [ordered]@{}; $emp = [ordered]@{}; $mods = [ordered]@{}; $gated = $false
    # Goods values are NOT always integers: subsistence / urban-centre / agro PMs use fractions
    # (grain 1.0, fabric 0.5, meat 0.33, ...). Matching only \d+ silently truncated those to 0.
    foreach ($l in $pBlocks[$name]) {
        if     ($l -match 'goods_input_([a-z_]+)_add\s*=\s*(-?\d+(?:\.\d+)?)')  { $in[$Matches[1]]  = Get-Num $Matches[2] }
        elseif ($l -match 'goods_output_([a-z_]+)_add\s*=\s*(-?\d+(?:\.\d+)?)') { $out[$Matches[1]] = Get-Num $Matches[2] }
        elseif ($l -match 'building_employment_([a-z_]+)_add\s*=\s*(-?\d+)')  { $emp[$Matches[1]] = [int]$Matches[2] }
        elseif ($l -match '^\s*([a-z][a-z0-9_]*)_add\s*=\s*(-?\d+)\s*$')      { $mods[$Matches[1]] = [int]$Matches[2] }
        elseif ($l -match 'unlocking_principles\s*=')                        { $gated = $true }  # power-bloc-gated (only active with a bloc principle) — UI must not default to it
    }
    $rec = [ordered]@{ in = $in; out = $out; emp = $emp; mods = $mods }
    if ($gated) { $rec.gated = $true }
    $pms[$name] = $rec
}

# --- write ui/vanilla.js ---
$payload = [ordered]@{ buildings = $buildings; pmgs = $pmgs; pms = $pms }
$json = $payload | ConvertTo-Json -Depth 12 -Compress
$body = "// AUTO-GENERATED by tools/extract_vanilla.ps1 - vanilla building/PMG/PM reference for the balance UI.`n" +
        "// Read-only; regenerated from the live game. See the include_all_buildings toggle.`n" +
        "window.PMVANILLA = $json;`n"
$outPath = Join-Path $Repo 'ui\vanilla.js'
[System.IO.File]::WriteAllText($outPath, $body, (New-Object System.Text.UTF8Encoding($false)))
Write-Output ("Extracted {0} buildings, {1} pmgs, {2} pms -> ui\vanilla.js ({3:N0} KB)" -f `
    $buildings.Count, $pmgs.Count, $pms.Count, ((Get-Item $outPath).Length / 1KB))
