<#
  PM & Tech Rehaul - goods icon extractor (balance UI only).

  Converts the vanilla goods icons (.dds) into ui/icons.js as
      window.PMICONS = { <good>: "data:image/png;base64,..." }
  so the balance UI's scenario panel can show the same pictograms the game does.

  WHY THIS IS SAFE TO DECODE CHEAPLY: V3's goods icons are UNCOMPRESSED 32-bit BGRA
  (DDS pixel-format flags 0x41 = RGB|ALPHAPIXELS, fourCC 0, 32bpp, pitch = width*4), so
  there is no DXT/BC block decompression to do - the pixel data after the 128-byte header
  is already in the exact byte order System.Drawing's Format32bppArgb expects on
  little-endian. We copy the first (largest) mip surface and downscale it.

  The good -> texture mapping is read from common/goods/00_goods.txt, NOT assumed from the
  filename: several goods use a differently-named icon (engines -> locomotives.dds,
  manowars -> man_o_wars.dds).

  ART IS NOT REDISTRIBUTED: ui/icons.js is generated locally and .gitignore'd, so no
  Paradox art lands in the repo. Missing icons.js just means the UI shows no pictograms.

  Usage:  powershell -ExecutionPolicy Bypass -File tools\extract_icons.ps1 [-Game "<...\Victoria 3\game>"] [-Size 40]
#>
param(
    [string]$Repo = (Split-Path $PSScriptRoot -Parent),
    [string]$Game = $(if ($env:VIC3_GAME) { $env:VIC3_GAME } else { "C:\Program Files (x86)\Steam\steamapps\common\Victoria 3\game" }),
    [int]$Size = 40
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

# --- good -> texture path, straight from the goods definitions (authoritative) ---
$goodsFile = Join-Path $Game 'common\goods\00_goods.txt'
if (-not (Test-Path -LiteralPath $goodsFile)) { Write-Output "note: $goodsFile not found - skipping icon extraction"; return }
$map = [ordered]@{}
$cur = $null
foreach ($line in (Get-Content -LiteralPath $goodsFile)) {
    if ($line -match '^\s*([a-z][a-z0-9_]*)\s*=\s*\{') { $cur = $Matches[1] }
    elseif ($cur -and $line -match 'texture\s*=\s*"([^"]+)"') { $map[$cur] = $Matches[1]; $cur = $null }
}

# --- decode one uncompressed BGRA .dds into a Bitmap, scaled to $Size ---
function Convert-Dds([string]$path, [int]$size) {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    if ($bytes.Length -lt 128) { return $null }
    if ([System.Text.Encoding]::ASCII.GetString($bytes, 0, 4) -ne 'DDS ') { return $null }
    $h = [BitConverter]::ToInt32($bytes, 12)      # height
    $w = [BitConverter]::ToInt32($bytes, 16)      # width
    $pfFlags = [BitConverter]::ToInt32($bytes, 80)
    $fourCC  = [BitConverter]::ToInt32($bytes, 84)
    $bpp     = [BitConverter]::ToInt32($bytes, 88)
    if ($fourCC -ne 0 -or $bpp -ne 32) { Write-Output ("note: {0} is compressed/unsupported (fourCC={1} bpp={2}) - skipped" -f (Split-Path $path -Leaf), $fourCC, $bpp); return $null }
    $need = 128 + $w * $h * 4
    if ($bytes.Length -lt $need) { return $null }
    $src = New-Object System.Drawing.Bitmap($w, $h, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $rect = New-Object System.Drawing.Rectangle(0, 0, $w, $h)
    $data = $src.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::WriteOnly, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    try {
        # DDS rows are top-down and BGRA - identical layout to Format32bppArgb, so copy row by row
        for ($y = 0; $y -lt $h; $y++) {
            [System.Runtime.InteropServices.Marshal]::Copy($bytes, 128 + $y * $w * 4,
                [IntPtr]::Add($data.Scan0, $y * $data.Stride), $w * 4)
        }
    } finally { $src.UnlockBits($data) }
    $dst = New-Object System.Drawing.Bitmap($size, $size, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($dst)
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.PixelOffsetMode   = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    $g.DrawImage($src, (New-Object System.Drawing.Rectangle(0, 0, $size, $size)))
    $g.Dispose(); $src.Dispose()
    return $dst
}

$out = [ordered]@{}
$missing = @()
foreach ($good in $map.Keys) {
    $rel = $map[$good] -replace '/', '\'
    $p = Join-Path $Game $rel
    if (-not (Test-Path -LiteralPath $p)) { $missing += $good; continue }
    $bmp = Convert-Dds $p $Size
    if (-not $bmp) { $missing += $good; continue }
    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
    $bmp.Dispose()
    $out[$good] = 'data:image/png;base64,' + [Convert]::ToBase64String($ms.ToArray())
    $ms.Dispose()
}

$json = $out | ConvertTo-Json -Depth 3 -Compress
$body = "// AUTO-GENERATED by tools/extract_icons.ps1 - vanilla goods pictograms for the balance UI.`n" +
        "// UI-ONLY and .gitignore'd: game art is never committed or shipped in mod/. Regenerated each build.`n" +
        "window.PMICONS = $json;`n"
$outPath = Join-Path $Repo 'ui\icons.js'
[System.IO.File]::WriteAllText($outPath, $body, (New-Object System.Text.UTF8Encoding($false)))
Write-Output ("Extracted {0} goods icons at {1}px -> ui\icons.js ({2:N0} KB){3}" -f `
    $out.Count, $Size, ((Get-Item $outPath).Length / 1KB), $(if ($missing.Count) { "; no icon for: $($missing -join ', ')" } else { '' }))
