// config/dam_projects.json — THE DAM PROJECT TABLE (ROADMAP step 6, BALANCE_FRAMEWORK §10.89).
//
//   node tools/make_dam_projects.mjs <sites.json>        # writes config/dam_projects.json
//
// <sites.json> is the placement research's output (one object per Victoria 3 state: the research rows merged
// or split onto it, a depersonalised name, the anchor province; 2026-09-26, user-reviewed case by case).
// This script copies the fields the emitter needs and attaches the NON-POWER EFFECTS below — the irrigation
// research of 2026-09-26, kept conservative by ruling ("bonuses should be justified by more than building
// desirability"; "no bonus is about as effective per unit of input and labour as elsewhere in the world").
// An effect names its TARGET state explicitly, because three dams irrigate a different state from the one
// they stand in (Aswan → Middle Egypt, Hoover → California, Mingachevir → Azerbaijan). `stage` is the stage
// whose completion fires it (default 1; 'last' = the project's final stage).
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = process.argv[2];
if (!src) { console.error('usage: node tools/make_dam_projects.mjs <sites.json>'); process.exit(2); }
const sites = JSON.parse(readFileSync(src, 'utf8'));

// host state -> effects (the dam_agri_effects research; the optional low-confidence ones are left out)
const EFFECTS = {
  // Aswan Low (1902): 320,000 feddans between Cairo and Assiut from basin to perennial by 1907 (~+16% cropping)
  STATE_EGYPTIAN_DESERT: [{ state: 'STATE_MIDDLE_EGYPT', remove_trait: 'state_trait_pmr_basin_irrigation', arable: 8 }],
  // Sennar (1925): the Gezira scheme on rain-fed plain, 240,000 feddans at opening, ~1M feddans on Sennar
  STATE_BLUE_NILE: [{ state: 'STATE_BLUE_NILE', remove_trait: 'state_trait_pmr_rainfed_plain', arable: 12 }],
  // Grand Coulee: the Columbia Basin Project on shrub-steppe (272,000 ha, ~+9% of cropland)
  STATE_WASHINGTON: [{ state: 'STATE_WASHINGTON', arable: 15 }],
  // Sevan–Hrazdan: 80,000 ha of new irrigation on the Ararat plain (~+16%)
  STATE_ARMENIA: [{ state: 'STATE_ARMENIA', arable: 8 }],
  // Mingachevir: the Upper Karabakh and Upper Shirvan canals on semi-desert steppe
  STATE_ELIZAVETPOL: [{ state: 'STATE_ELIZAVETPOL', arable: 5 }, { state: 'STATE_AZERBAIJAN', arable: 4 }],
  // Kakhovka (the last Dnieper stage): irrigation of already-ploughed dry steppe — land a little, drought resilience
  STATE_TAURIDA: [{ state: 'STATE_TAURIDA', add_trait: 'state_trait_pmr_steppe_irrigation', arable: 5, stage: 'last' }],
  // TVA / Cumberland: flood control was the first statutory purpose; the reservoirs drowned bottomland
  STATE_TENNESSEE: [{ state: 'STATE_TENNESSEE', add_trait: 'state_trait_pmr_flood_control' }],
  STATE_ALABAMA: [{ state: 'STATE_ALABAMA', add_trait: 'state_trait_pmr_flood_control_minor' }],
  STATE_KENTUCKY: [{ state: 'STATE_KENTUCKY', add_trait: 'state_trait_pmr_flood_control_minor' }],
  // Hoover (All-American / Coachella canals) + Shasta: Coachella's 78,530 new acres; Imperial was already irrigated
  STATE_CALIFORNIA: [{ state: 'STATE_CALIFORNIA', arable: 5 }],
  // marginal: Warsak (>=119,000 acres), the Vakhsh headworks, the Snowy's Coleambally area
  STATE_PASHTUNISTAN: [{ state: 'STATE_PASHTUNISTAN', arable: 3 }],
  STATE_TAJIKISTAN: [{ state: 'STATE_TAJIKISTAN', arable: 3 }],
  STATE_NEW_SOUTH_WALES: [{ state: 'STATE_NEW_SOUTH_WALES', arable: 1 }],
};

const byState = new Map(sites.map(s => [s.state, s]));
for (const host of Object.keys(EFFECTS)) if (!byState.has(host)) throw new Error(`make_dam_projects: effects keyed on ${host}, which has no project`);
const out = sites.map(s => ({
  id: s.id, state: s.state, state_name: s.state_name, name: s.name, anchor_province: s.anchor_province,
  owner_1836: s.owner_1836,
  rows: s.rows.map(r => ({ research_id: r.research_id, project: r.project, parts_taken: r.parts_taken, mw_per_part: r.mw_per_part,
    cost_multiplier: r.cost_multiplier, resource_type: r.resource_type, status: r.status })),
  ...(EFFECTS[s.state] ? { effects: EFFECTS[s.state] } : {}),
}));
const dst = join(REPO, 'config/dam_projects.json');
writeFileSync(dst, JSON.stringify({ _comment: 'GENERATED by tools/make_dam_projects.mjs from the 2026-09-26 placement research - the hydro-dam projects, one per state (ROADMAP step 6, BALANCE_FRAMEWORK §10.89). Numbers derived from these rows live in tools/lib_dams.mjs.', projects: out }, null, 1) + '\n');
console.log(`dam_projects: ${out.length} projects, ${out.filter(p => p.effects).length} with non-power effects -> config/dam_projects.json`);
