<#
  telemetry_lib.ps1 - the ONE place that generates testbed telemetry script.

  Dot-sourced by build.ps1. Every arm of an experiment - the vanilla control and any modded
  build - gets its instrumentation from here, which is what makes a control valid: if the arms
  could differ in what they log, the comparison would not be like-for-like.

  Everything emitted below uses data functions VERIFIED in-game against 1.13.9. Before adding a
  metric, read TESTBED_METRICS.md: one bad data function voids the WHOLE debug_log line it sits
  in (it is not printed at all), and several plausible-looking paths silently return an empty
  value rather than erroring.

  The telemetry SPEC is a small JSON object, so a future UI can author it:
    {
      "dump_dates": ["1840.1.1", "1860.1.1"],     # each must be the 1st of a month
      "tags":       ["GBR", "FRA"],               # markets to dump
      "metrics":    ["market_goods"]              # which metric blocks to emit
    }
#>

# NOTE: deliberately no Set-StrictMode here. This file is DOT-SOURCED into build.ps1, and
# Set-StrictMode applies to the CALLER's scope - switching it on broke the builder's own
# `-not $_.disabled` property tests. A library must not change its caller's strictness.

# ---------------------------------------------------------------- SCHEMA VERSION ----
# CONSECUTIVE, MONOTONIC. Bump by ONE whenever the emitted telemetry changes in a way that makes
# an older session non-comparable - a new metric, a changed line format, a dropped field. Never
# reuse or renumber: a finding cites the version it was measured under, and that citation has to
# keep meaning the same thing forever. Record every bump in the table in TESTBED_METRICS.md and
# tag the affected findings in FINDINGS.md.
#
#   v1  market goods (buy/sell/price only), generated by the HARNESS. No events, no
#       imports/exports/production. -> FINDINGS F1, F2 (sessions deleted).
#   v2  builder-owned generator; market goods gain imports/exports/production; one-off events
#       (DEFAULT, DIPPLAY, PEACE, CAPIT).
#   v3  + country_state: per-country GDP / foreign-owned GDP / GDP abroad / market; building
#       counts + levels by category; world GDP. Market line gains owner + member. Events gain
#       WARSTART and true BANKRUPTCY (modifier poll).  -> FINDINGS F3, F4, F5.
#       ⚠ v3 has NO war/civil-war state, so a country-level snapshot can be distorted without
#       any way to tell from the data.
#   v4  + STATE line per country per dump: at_war / civil_war / revolutionary / in_default.
#   v5  + TREASURY, per TRACKED country: TCASH (gold, principal, credit, balance, investment pool,
#       unrealized taxes, weekly expenses), TREV (8 revenue lines), TEXP (17 expense lines) - the
#       in-game budget panel - and TRADE (country trade capacity + trade-centre count/levels).
#   v6  + POP line per country per dump (metric `population`): total workforce, peasant workforce,
#       slave workforce, dependents, mean state unemployment rate, total population. Rides inside
#       the existing every_country pass. UNVALIDATED until probed in-game.
#   v7  PHASED dumps (one logical dump emitted over 3 consecutive months, cutting the per-tick
#       log burst to ~1/3) + tag-scoping removed: treasury per EVERY country, market goods per
#       EVERY market. Country sets can differ slightly between phases - join on name.
$script:TELEMETRY_VERSION = 7

function Get-TelemetryVersion { return $script:TELEMETRY_VERSION }

function Get-TelemetryDefaults {
    return [ordered]@{
        dump_dates = @("1840.1.1")
        tags       = @("GBR", "FRA")
        metrics    = @("market_goods")
    }
}

function Read-TelemetrySpec {
    param([string]$Path)
    $spec = Get-TelemetryDefaults
    if ($Path) {
        if (-not (Test-Path $Path)) { throw "telemetry spec not found: $Path" }
        $j = Get-Content $Path -Raw -Encoding UTF8 | ConvertFrom-Json
        foreach ($k in @("dump_dates", "tags", "metrics")) {
            if ($j.PSObject.Properties.Name -contains $k -and $j.$k) { $spec[$k] = @($j.$k) }
        }
    }
    foreach ($d in $spec.dump_dates) {
        if ($d -notmatch '^\d{3,4}\.\d{1,2}\.1$') {
            throw "telemetry dump date '$d' must be the 1st of a month - on_monthly_pulse only fires then"
        }
    }
    return $spec
}

function New-TelemetryScriptValues {
    <#
      Returns the text of common/script_values/zzz_v3tb_values.txt - the iterating script values
      the telemetry reads with .MakeScope.ScriptValue('name'). Mechanism 2 in TESTBED_METRICS.md:
      this is the ONLY way to get an aggregate (a per-category building count) into one log line.

      Building categories follow the vanilla building_group HIERARCHY (common/building_groups):
      is_building_group matches PARENT groups, so bg_manufacturing covers light/heavy/military
      industry and ship construction in one test. Categories are the user's four, with the
      auto-scaling groups split out so they can be included or ignored at analysis time:
        mfg     = bg_manufacturing
        extract = bg_mining + bg_logging + bg_rubber + bg_oil_extraction   (gold fields separate)
        agri    = bg_agriculture + bg_ranching + bg_plantations + bg_fishing + bg_whaling
                  (bg_subsistence_* are children of agriculture/ranching -> counted separately
                   and subtracted at analysis time)
        subsist = bg_subsistence_agriculture + bg_subsistence_ranching
        gold    = bg_gold_fields
      "non-economic" is DERIVED in analysis as total - (mfg + extract + agri), so a group we
      forgot cannot silently vanish from the accounting.
    #>
    $cats = [ordered]@{
        mfg     = @('bg_manufacturing')
        extract = @('bg_mining','bg_logging','bg_rubber','bg_oil_extraction')
        agri    = @('bg_agriculture','bg_ranching','bg_plantations','bg_fishing','bg_whaling')
        subsist = @('bg_subsistence_agriculture','bg_subsistence_ranching')
        gold    = @('bg_gold_fields')
    }
    $sv = @"
# AUTO-GENERATED by tools/telemetry_lib.ps1 via build.ps1 - do not edit by hand.
# Iterating script values for testbed building counts (TESTBED_METRICS.md mechanism 2).

v3tb_bld_total = { value = 0
	every_scope_state = { every_scope_building = { add = 1 } } }
v3tb_lvl_total = { value = 0
	every_scope_state = { every_scope_building = { add = level } } }
"@
    foreach ($c in $cats.Keys) {
        $lim = if ($cats[$c].Count -eq 1) {
            "is_building_group = $($cats[$c][0])"
        } else {
            "OR = { " + (($cats[$c] | ForEach-Object { "is_building_group = $_" }) -join ' ') + " }"
        }
        $sv += @"


v3tb_bld_$c = { value = 0
	every_scope_state = { every_scope_building = {
		limit = { $lim }
		add = 1 } } }
v3tb_lvl_$c = { value = 0
	every_scope_state = { every_scope_building = {
		limit = { $lim }
		add = level } } }
"@
    }
    $sv += @"


# World GDP - summed over every country, read from any country scope.
v3tb_world_gdp = { value = 0
	every_country = { add = gdp } }

# Country STATE flags (0/1). A country at war - and above all one in a civil war - can have its
# economy distorted by orders of magnitude, so a snapshot is not interpretable without knowing
# which state the country was in when it was taken. Civil war is reported separately from and in
# addition to regular war (a civil war also sets is_at_war).
v3tb_at_war = { value = 0
	if = { limit = { is_at_war = yes } value = 1 } }
v3tb_civil_war = { value = 0
	if = { limit = { is_in_civil_war = yes } value = 1 } }
v3tb_revolutionary = { value = 0
	if = { limit = { is_revolutionary = yes } value = 1 } }
v3tb_in_default = { value = 0
	if = { limit = { in_default = yes } value = 1 } }

# ---- POPULATION / WORKFORCE ----
# The capital-scarcity measure: how much of a country's workforce is in subsistence (peasants) or
# idle, versus gainfully employed. Vanilla late-game advanced economies run peasants and unemployed
# to ~0, which the mod is meant to prevent by making modernisation cost capital.
#
# `workforce` and `dependents` are pop-scope numeric triggers (common/trigger_localization), so they
# work as script-value keywords under every_scope_pop. `is_pop_type` is the vanilla filter idiom.
v3tb_wf_total = { value = 0
	every_scope_state = { every_scope_pop = { add = workforce } } }
v3tb_wf_peasants = { value = 0
	every_scope_state = { every_scope_pop = {
		limit = { is_pop_type = peasants }
		add = workforce } } }
v3tb_wf_slaves = { value = 0
	every_scope_state = { every_scope_pop = {
		limit = { is_pop_type = slaves }
		add = workforce } } }
v3tb_dependents = { value = 0
	every_scope_state = { every_scope_pop = { add = dependents } } }

# Unemployment. There is NO unemployed-count keyword; `state_unemployment_rate` (state scope) is
# the only handle, so this reproduces VANILLA'S OWN estimate from common/script_values/je_values.txt
# (mon_unemployment_estimate): the unweighted mean rate across states. Vanilla's comment there says
# the trigger "is way off actual unemployment rate" and doubles it - we do NOT double, and report
# the raw mean. Treat it as directional, not a count. An actual count would need
# State.GetNumUnemployedWorkingAdults, which is a data function and cannot be summed in a script value.
v3tb_unemp_rate = { value = 0
	every_scope_state = { add = state_unemployment_rate }
	if = { limit = { num_states > 0 } divide = num_states } }

# Trade centres. `level` is the only building-scope numeric keyword confirmed working, so levels
# and count are the reliable measures; staffing is probed separately (see New-TelemetryProbeValues).
v3tb_bld_tradecenter = { value = 0
	every_scope_state = { every_scope_building = {
		limit = { is_building_type = building_trade_center }
		add = 1 } } }
v3tb_lvl_tradecenter = { value = 0
	every_scope_state = { every_scope_building = {
		limit = { is_building_type = building_trade_center }
		add = level } } }
"@
    return $sv
}

function New-TelemetryProbeValues {
    <#
      RISKY script values, emitted to their OWN file (zzz_v3tb_probe_values.txt) and only when a
      probe metric asks for them. Both use keywords that are NOT verified to exist at their scope:
      if a Paradox script-values file fails to parse, everything in it is lost - so these must not
      share a file with the working values, or a bad guess here would silently zero the building
      counts that F3 depends on.
    #>
    return @"
# AUTO-GENERATED by tools/telemetry_lib.ps1 - PROBE VALUES, unverified keywords. See TESTBED_METRICS.

# Is `trade_capacity` a state-scope script-value keyword? GetTradeCapacity is a State DATA function
# (gui/budget_panel.gui), which does not imply a script-value keyword of the same name.
v3tb_trade_capacity = { value = 0
	every_scope_state = { add = trade_capacity } }

# Is there a building-scope employment keyword? GetEmploymentPercentage / GetEmployeeCap exist as
# Building DATA functions; `employment` as a script-value keyword is a guess.
v3tb_tc_employed = { value = 0
	every_scope_state = { every_scope_building = {
		limit = { is_building_type = building_trade_center }
		add = employment } } }

# An actual UNEMPLOYED COUNT would beat the rate estimate. Both of these are guesses at a pop-scope
# employment trigger; neither appears in vanilla script. If one works, the workforce split becomes
# exact instead of "total minus peasants, with a separate rate".
v3tb_unemp_count_a = { value = 0
	every_scope_state = { every_scope_pop = {
		limit = { is_unemployed = yes }
		add = workforce } } }
v3tb_unemp_count_b = { value = 0
	every_scope_state = { every_scope_pop = { add = unemployed_workforce } } }
"@
}

function New-TelemetryScript {
    <#
      Returns the text of common/on_actions/zzz_v3tb_telemetry.txt.
      $Token stamps every line so a run can reject lines belonging to another run - consecutive
      runs share one logs\ folder and the game rotates debug.log at launch, which otherwise lets
      an earlier run's output be read as this one's.
    #>
    param($Spec, [string]$Token, [string]$BuildStamp)

    $dates   = @($Spec.dump_dates)
    $tags    = @($Spec.tags)
    $metrics = @($Spec.metrics)

    $dumpNames = @()
    $dumpBody  = ""
    $n = 0
    foreach ($date in $dates) {
        $n++
        $name = "v3tb_dump_$n"
        # (phase names are appended below, one per emitted phase)

        # one-month trigger window: on_monthly_pulse fires on the 1st, so this is hit exactly once
        $p = $date.Split('.')
        $y = [int]$p[0]; $m = [int]$p[1]
        $nm = $m + 1; $ny = $y
        if ($nm -gt 12) { $nm = 1; $ny = $y + 1 }
        $next = "{0}.{1}.1" -f $ny, $nm

        # PHASES. A dump used to emit everything in ONE tick: ~1.96 MB, which is 78% of the game's
        # whole 5x512KB log ring, so several segments rotated away before the harness could read
        # them (measured 2026-08-01: 6015 telemetry lines lost). No poll rate fixes that - you
        # cannot read a ring faster than it is destroyed. So each metric block now fires in a
        # DIFFERENT MONTH, cutting the peak burst to roughly a third.
        #
        # The log line keeps the ORIGINAL dump date, so a "1836.2.1 snapshot" is still one logical
        # snapshot even though its parts are emitted across 1836.2.1 / .3.1 / .4.1. on_monthly_pulse
        # is the only verified pulse, so months are the finest slicing available.
        $phaseBlocks = @{ 0 = ""; 1 = ""; 2 = "" }
        $blocks = ""

        # ---- per-country state: GDP, ownership, and building counts by category ----
        # ONE every_country pass carries both, because a second pass would double the cost of the
        # iterating script values. Country identity is the NAME: GetTag and GetDefinition.GetKey
        # both fail (probed 1836.2.1) - there is no tag data function.
        if ($metrics -contains "country_state") {
            $blocks += @"

			every_country = {
				debug_log = "V3TB|$Token|GDP|$date|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.GetGDP|2]|[THIS.GetCountry.GetForeignOwnedGDPFraction|4]|[THIS.GetCountry.GetForeignOwnedGDP|2]|[THIS.GetCountry.GetGDPOwnedInForeignCountries|2]|[THIS.GetCountry.GetMarket.GetNameNoFormatting]"
				debug_log = "V3TB|$Token|BLD|$date|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_total')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_mfg')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_extract')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_agri')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_subsist')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_gold')]"
				debug_log = "V3TB|$Token|LVL|$date|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_total')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_mfg')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_extract')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_agri')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_subsist')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_gold')]"
				# Own line: war/civil-war state can distort a country's economy by orders of
				# magnitude, so a snapshot is uninterpretable without it. Kept OUT of the GDP line
				# so that if one of these voids, the GDP row still survives.
				debug_log = "V3TB|$Token|STATE|$date|[THIS.GetCountry.GetNameNoFormatting]|war=[THIS.GetCountry.MakeScope.ScriptValue('v3tb_at_war')]|civil=[THIS.GetCountry.MakeScope.ScriptValue('v3tb_civil_war')]|revol=[THIS.GetCountry.MakeScope.ScriptValue('v3tb_revolutionary')]|default=[THIS.GetCountry.MakeScope.ScriptValue('v3tb_in_default')]"$(if ($metrics -contains "population") {
				# Rides inside the SAME every_country pass as GDP/BLD/LVL - a second sweep would
				# double the per-country cost for nothing. pop = total_population (verified country
				# keyword); wf_* are workforce sums; unemp_rate is vanilla's own state-mean estimate.
				"`r`n`t`t`t`tdebug_log = `"V3TB|$Token|POP|$date|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_wf_total')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_wf_peasants')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_wf_slaves')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_dependents')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_unemp_rate')]|[THIS.GetCountry.GetTotalPopulation]`""
			})
			}
			# World GDP once per dump (the script value itself iterates every country, so calling it
			# inside every_country would be O(n^2)). Analysis can also just sum the GDP lines.
			if = {
				limit = { exists = c:GBR }
				c:GBR = { debug_log = "V3TB|$Token|WORLD|$date|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_world_gdp')]" }
			}
			else = { debug_log = "V3TB|$Token|WORLD|$date|NO_GBR" }
"@
            $phaseBlocks[1] += $blocks; $blocks = ""   # country/pop data -> its own month
        }

        if ($metrics -contains "market_goods") {
            # EVERY market, not one per tracked tag. A market is identified by its own name plus its
            # owner, so nothing is lost by dropping the tag list - and shared markets (EIC in the
            # British market) are no longer logged once per member, which was pure duplication.
            $blocks += @"

			every_market = {
				debug_log = "V3TB|$Token|MARKET|$date|[THIS.GetMarket.GetNameNoFormatting]|owner=[THIS.GetMarket.GetOwner.GetNameNoFormatting]"
				every_market_goods = {
					debug_log = "V3TB|$Token|G|$date|[PREV.GetMarket.GetNameNoFormatting]|[THIS.GetMarketGoods.GetGoods.GetKey]|[THIS.GetMarketGoods.GetGoods.GetMarketBuyOrders|2]|[THIS.GetMarketGoods.GetGoods.GetMarketSellOrders|2]|[THIS.GetMarketGoods.GetGoods.GetMarketPrice|2]|[THIS.GetMarketGoods.GetGoods.GetMarketImports|2]|[THIS.GetMarketGoods.GetGoods.GetMarketExports|2]|[THIS.GetMarketGoods.GetGoods.GetMarketProduction|2]"
				}
			}
"@
            $phaseBlocks[0] += $blocks; $blocks = ""   # market goods -> its own month (the big one)
        }

        # ---- TREASURY (production): the in-game budget panel, per country.
        # Every function below was verified in-game 2026-07-31 (probe sessions 20260731_232310 and
        # _232749): all 9 cash + 8 revenue + 17 expense functions returned values, zero data errors.
        # Bundled into four lines rather than one-per-line because they are proven; the field order
        # here IS the parsing contract, so append new fields at the END of a line, never insert.
        # Tracked tags only - this is per-country detail, not an every_country sweep.
        if ($metrics -contains "treasury") {
            $cashF = @('GetGoldReserves','GetPrincipal','GetMaxCredit','GetRemainingCredit',
                       'GetWeeklyBalance','GetInvestmentPool','GetInvestmentPoolChange',
                       'GetUnrealizedTaxes','GetWeeklyExpenses')
            $revF  = @('GetIncomeTaxIncome','GetPollTaxIncome','PredictConsumptionTaxes',
                       'PredictTariffs','PredictMinting','PredictDiplomaticPactsIncome',
                       'PredictTreatyIncome','GetInvestmentIncome')
            $expF  = @('GetGovernmentGoodsExpenses','PredictGovernmentWagesExpenses',
                       'GetMilitaryGoodsExpenses','PredictMilitaryWagesExpenses',
                       'GetSupplyShipMaintenanceExpenses','GetSupplyShipConstructionGoodsExpenses',
                       'GetMilitaryShipMaintenanceExpenses','GetPortConnectionExpenses',
                       'GetWelfarePaymentsExpenses','GetSubsidiesExpenses','GetSubventionsExpenses',
                       'GetInterestPayment','GetConstructionGoodsExpenses',
                       'GetGovernmentSlavesExpenses','GetMilitarySlavesExpenses',
                       'PredictTreatyExpenses','PredictDiplomaticPactsExpenses')
            # EVERY country, not a tracked-tag list. Tags were always a volume workaround; with the
            # mirror fixed there is no reason to pre-select who is interesting, and pre-selecting
            # decides the analysis before the data exists. Country identity is the NAME (there is no
            # tag data function - TESTBED_METRICS section 3).
            $cashL = ($cashF | ForEach-Object { "[THIS.GetCountry.$_|2]" }) -join '|'
            $revL  = ($revF  | ForEach-Object { "[THIS.GetCountry.$_|2]" }) -join '|'
            $expL  = ($expF  | ForEach-Object { "[THIS.GetCountry.$_|2]" }) -join '|'
            $blocks += @"

			every_country = {
				debug_log = "V3TB|$Token|TCASH|$date|[THIS.GetCountry.GetNameNoFormatting]|$cashL"
				debug_log = "V3TB|$Token|TREV|$date|[THIS.GetCountry.GetNameNoFormatting]|$revL"
				debug_log = "V3TB|$Token|TEXP|$date|[THIS.GetCountry.GetNameNoFormatting]|$expL"
				# Trade capacity comes off the MARKET, so no state/building iteration is needed.
				# Trade-centre levels DO need it - that is the only sub-country scope here.
				debug_log = "V3TB|$Token|TRADE|$date|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.GetMarket.GetCountryTradeCapacity(THIS.GetCountry.Self)]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_tradecenter')]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_tradecenter')]"
			}
"@
            $phaseBlocks[2] += $blocks; $blocks = ""   # treasury -> its own month
        }

        # ---- TREASURY PROBE: one data function per line, so a failure voids only its own line
        # and we learn exactly which of ~30 budget functions work. The production version bundles
        # the survivors into a few lines. Tracked tags only - this is per-country detail, not an
        # every_country sweep, so volume stays low.
        if ($metrics -contains "treasury_probe") {
            # label -> data function, taken from gui/budget_panel.gui (the in-game budget panel)
            $cash = [ordered]@{
                gold = 'GetGoldReserves'; principal = 'GetPrincipal'
                maxcredit = 'GetMaxCredit'; remcredit = 'GetRemainingCredit'
                balance = 'GetWeeklyBalance'; pool = 'GetInvestmentPool'
                poolchange = 'GetInvestmentPoolChange'; unrealized = 'GetUnrealizedTaxes'
                weeklyexp = 'GetWeeklyExpenses'
            }
            $rev = [ordered]@{
                inctax = 'GetIncomeTaxIncome'; polltax = 'GetPollTaxIncome'
                constax = 'PredictConsumptionTaxes'; tariffs = 'PredictTariffs'
                minting = 'PredictMinting'; pactsin = 'PredictDiplomaticPactsIncome'
                treatyin = 'PredictTreatyIncome'; investinc = 'GetInvestmentIncome'
            }
            $exp = [ordered]@{
                govgoods = 'GetGovernmentGoodsExpenses'; govwages = 'PredictGovernmentWagesExpenses'
                milgoods = 'GetMilitaryGoodsExpenses'; milwages = 'PredictMilitaryWagesExpenses'
                supshipmaint = 'GetSupplyShipMaintenanceExpenses'
                supshipcon = 'GetSupplyShipConstructionGoodsExpenses'
                milshipmaint = 'GetMilitaryShipMaintenanceExpenses'
                portconn = 'GetPortConnectionExpenses'; welfare = 'GetWelfarePaymentsExpenses'
                subsidies = 'GetSubsidiesExpenses'; subventions = 'GetSubventionsExpenses'
                interest = 'GetInterestPayment'; congoods = 'GetConstructionGoodsExpenses'
                govslaves = 'GetGovernmentSlavesExpenses'; milslaves = 'GetMilitarySlavesExpenses'
                treatyexp = 'PredictTreatyExpenses'; pactsexp = 'PredictDiplomaticPactsExpenses'
            }
            foreach ($tag in $tags) {
                $lines = ""
                foreach ($grp in @(@{n='CASH';m=$cash}, @{n='REV';m=$rev}, @{n='EXP';m=$exp})) {
                    foreach ($k in $grp.m.Keys) {
                        $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|$($grp.n)|$k|[THIS.GetCountry.$($grp.m[$k])|2]`""
                    }
                }
                # trade-centre proxies: levels via script value (known-good mechanism), plus the
                # two shapes that might reach State/Building scope from a country.
                $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|TC|levels|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_tradecenter')]`""
                $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|TC|count|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_tradecenter')]`""
                $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|TC|capacity_sv|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_trade_capacity')]`""
                $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|TC|employed_sv|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_tc_employed')]`""
                # Country-level trade capacity via the MARKET - no sub-country iteration at all.
                # Form copied from gui/market_panel.gui: Market.GetCountryTradeCapacity(Country.Self)
                $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|TC|capacity_mkt|[THIS.GetCountry.GetMarket.GetCountryTradeCapacity(THIS.GetCountry.Self)]`""
                # v6 population: the solid workforce sums plus the two speculative unemployed-count
                # keywords, each on its own line so a bad guess only voids itself.
                foreach ($pv in @('v3tb_wf_total','v3tb_wf_peasants','v3tb_wf_slaves','v3tb_dependents','v3tb_unemp_rate','v3tb_unemp_count_a','v3tb_unemp_count_b')) {
                    $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|POP|$pv|[THIS.GetCountry.MakeScope.ScriptValue('$pv')]`""
                }
                $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|POP|total_pop_fn|[THIS.GetCountry.GetTotalPopulation]`""
                $lines += "`r`n`t`t`t`t`tdebug_log = `"V3TB|$Token|TP|$date|$tag|POP|inactive_fn|[THIS.GetCountry.GetInactivePopulation]`""
                $blocks += @"

			if = {
				limit = { exists = c:$tag }
				c:$tag = {$lines
				}
			}
			else = { debug_log = "V3TB|$Token|TP|$date|$tag|ABSENT|-|-" }
"@
            }
        }

        # ---- TRADE-ROUTE PROBE: what does a trade-route scope expose for LOGGING?
        # every_trade_route is a MARKET-scope iterator over routes that EXIST, so it is sparse by
        # construction - the right shape for import origins, versus ~305x305xgoods for the cross
        # product. Vanilla uses it (events/test_events.txt, commented out) with goods / importer /
        # owner as TRIGGERS; whether the scope offers printable fields is unknown, and there is no
        # trade-route GUI panel to copy a call from. One candidate per line.
        if ($metrics -contains "route_probe") {
            $blocks += @"

			c:GBR = {
				# CONSTANT MARKERS FIRST. A line with no data function in it CANNOT void, so if a
				# marker is missing the enclosing block did not run - whereas a missing data line
				# means that call failed. Without these two cases are indistinguishable, which is
				# what made the 2026-08-01 probe ambiguous.
				debug_log = "V3TB|$Token|RP|$date|m_country|reached-GBR"
				market_capital.market = {
					debug_log = "V3TB|$Token|RP|$date|m_market|reached-market"
					debug_log = "V3TB|$Token|RP|$date|mkt|[THIS.GetMarket.GetNameNoFormatting]"
					every_trade_route = {
						debug_log = "V3TB|$Token|RP|$date|m_route|reached-route"
						debug_log = "V3TB|$Token|RP|$date|r_this_key|[THIS.GetKey]"
						debug_log = "V3TB|$Token|RP|$date|r_this_name|[THIS.GetName]"
						debug_log = "V3TB|$Token|RP|$date|r_goods|[THIS.GetTradeRoute.GetGoods.GetKey]"
						debug_log = "V3TB|$Token|RP|$date|r_qty|[THIS.GetTradeRoute.GetQuantity|2]"
						debug_log = "V3TB|$Token|RP|$date|r_imp|[THIS.GetTradeRoute.GetImporter.GetNameNoFormatting]"
						debug_log = "V3TB|$Token|RP|$date|r_exp|[THIS.GetTradeRoute.GetExporter.GetNameNoFormatting]"
						debug_log = "V3TB|$Token|RP|$date|r_owner|[THIS.GetTradeRoute.GetOwner.GetNameNoFormatting]"
						debug_log = "V3TB|$Token|RP|$date|r_this|[THIS.GetNameNoFormatting]"
					}
					# NET-vs-GROSS, the open question in TESTBED_METRICS 2.5: for one good, the
					# market's own totals beside the per-source breakdown. If gross - exports equals
					# the total, GetMarketImports is net and every import share we have quoted is too.
					every_market_goods = {
						debug_log = "V3TB|$Token|RP|$date|ng_all|[THIS.GetMarketGoods.GetGoods.GetKey]|imports=[THIS.GetMarketGoods.GetGoods.GetMarketImports|2]|exports=[THIS.GetMarketGoods.GetGoods.GetMarketExports|2]|buy=[THIS.GetMarketGoods.GetGoods.GetMarketBuyOrders|2]"
					}
					every_market = {
						debug_log = "V3TB|$Token|RP|$date|ng_src|silk|[THIS.GetMarket.GetNameNoFormatting]|[PREV.GetMarket.GetImportedAmountFromMarket(THIS.GetMarket.Self, GetGoods('silk').Self)|2]"
					}
				}
			}
"@
        }

        # ---- PROBE: one uncertain data function per line, so a failure voids only its own line.
        # Every probe prints something whose value we already KNOW (a name) next to the number,
        # because a silent empty value is the dangerous failure mode (TESTBED_METRICS.md).
        if ($metrics -contains "probe") {
            $blocks += @"

			# ---- P1: every_country iteration + country identity ----
			every_country = {
				limit = { OR = { this = c:GBR this = c:FRA this = c:CHI } }
				debug_log = "V3TB|$Token|P|P1name|[THIS.GetCountry.GetNameNoFormatting]"
				debug_log = "V3TB|$Token|P|P1gdp|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.GetGDP|2]"
				debug_log = "V3TB|$Token|P|P1tag|[THIS.GetCountry.GetTag]"
				debug_log = "V3TB|$Token|P|P1defkey|[THIS.GetCountry.GetDefinition.GetKey]"
				debug_log = "V3TB|$Token|P|P1fogdpfrac|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.GetForeignOwnedGDPFraction|2]"
				debug_log = "V3TB|$Token|P|P1fogdpabs|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.GetForeignOwnedGDP|2]"
				debug_log = "V3TB|$Token|P|P1gdpabroad|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.GetGDPOwnedInForeignCountries|2]"
				debug_log = "V3TB|$Token|P|P1market|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.GetMarket.GetNameNoFormatting]"
			}

			# ---- P2: per-category building counts via MakeScope.ScriptValue inside every_country ----
			every_country = {
				limit = { OR = { this = c:GBR this = c:FRA } }
				debug_log = "V3TB|$Token|P|P2total|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_total')]"
				debug_log = "V3TB|$Token|P|P2mfg|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_mfg')]"
				debug_log = "V3TB|$Token|P|P2extract|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_extract')]"
				debug_log = "V3TB|$Token|P|P2agri|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_agri')]"
				debug_log = "V3TB|$Token|P|P2subsist|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_subsist')]"
				debug_log = "V3TB|$Token|P|P2gold|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_bld_gold')]"
				debug_log = "V3TB|$Token|P|P2lvlmfg|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_lvl_mfg')]"
				debug_log = "V3TB|$Token|P|P2worldgdp|[THIS.GetCountry.MakeScope.ScriptValue('v3tb_world_gdp')]"
			}

			# ---- P3: market channel decomposition (the 3-way split) ----
			c:GBR = {
				market_capital.market = {
					debug_log = "V3TB|$Token|P|P3mktname|[THIS.GetMarket.GetNameNoFormatting]"
					debug_log = "V3TB|$Token|P|P3owner|[THIS.GetMarket.GetOwner.GetNameNoFormatting]"
					debug_log = "V3TB|$Token|P|P3buy|[THIS.GetMarket.GetMarketGoods(GetGoods('tools').Self).GetMarketBuyOrders|2]"
					debug_log = "V3TB|$Token|P|P3addimp|[THIS.GetMarket.GetWorldMarketAdditionalImportsToMarket|2]"
					debug_log = "V3TB|$Token|P|P3addexp|[THIS.GetMarket.GetWorldMarketAdditionalExportsFromMarket|2]"
					every_market_goods = {
						limit = { is_goods = GetGoods('tools') }
						debug_log = "V3TB|$Token|P|P3g_addimp|[THIS.GetMarketGoods.GetGoods.GetKey]|[THIS.GetMarketGoods.GetGoods.GetWorldMarketAdditionalImportsToMarket|2]"
						debug_log = "V3TB|$Token|P|P3g_addexp|[THIS.GetMarketGoods.GetGoods.GetKey]|[THIS.GetMarketGoods.GetGoods.GetWorldMarketAdditionalExportsFromMarket|2]"
						debug_log = "V3TB|$Token|P|P3g_balance|[THIS.GetMarketGoods.GetGoods.GetKey]|[THIS.GetMarketGoods.GetGoods.GetMarketBuyAndSellOrdersBalance|2]"
					}
				}
			}

			# ---- P4: tag survival - a country that does NOT exist must log, not vanish ----
			if = { limit = { exists = c:GER } c:GER = { debug_log = "V3TB|$Token|P|P4ger|exists|[THIS.GetCountry.GetNameNoFormatting]" } }
			else = { debug_log = "V3TB|$Token|P|P4ger|absent" }
			if = { limit = { exists = c:BIC } c:BIC = { debug_log = "V3TB|$Token|P|P4bic|exists|[THIS.GetCountry.GetNameNoFormatting]|[THIS.GetCountry.GetMarket.GetNameNoFormatting]" } }
			else = { debug_log = "V3TB|$Token|P|P4bic|absent" }
"@
        }

        # Anything not explicitly phased (probes, one-offs) rides in phase 0 with market goods.
        $phaseBlocks[0] = $blocks + $phaseBlocks[0]

        for ($ph = 0; $ph -lt 3; $ph++) {
            if (-not $phaseBlocks[$ph].Trim()) { continue }
            # shift the TRIGGER by $ph months; the logged date stays $date
            $sm = $m + $ph; $sy = $y
            while ($sm -gt 12) { $sm -= 12; $sy++ }
            $start = "{0}.{1}.1" -f $sy, $sm
            $em = $sm + 1; $ey = $sy
            if ($em -gt 12) { $em = 1; $ey++ }
            $end = "{0}.{1}.1" -f $ey, $em
            $pname = "${name}_p$ph"
            $dumpNames += $pname
            $dumpBody += @"

$pname = {
	trigger = {
		game_date >= "$start"
		NOT = { game_date >= "$end" }
	}
	effect = {
		debug_log = "V3TB|$Token|BEGIN|$date|p$ph|[TimeKeeper.GetCurrentDate.GetString]"
$($phaseBlocks[$ph])
		debug_log = "V3TB|$Token|END|$date|p$ph|[TimeKeeper.GetCurrentDate.GetString]"
	}
}
"@
        }
    }

    # one-off events. on_country_default is ENTERING DEFAULT, not bankruptcy - see TESTBED_METRICS.
    $events = ""
    if ($metrics -contains "events") {
        $events = @"

on_country_default = { on_actions = { v3tb_ev_default } }
on_diplomatic_play_started = { on_actions = { v3tb_ev_dipplay } }
on_diplo_play_war_start = { on_actions = { v3tb_ev_warstart } }
on_revolution_start = { on_actions = { v3tb_ev_revolt } }
on_secession_start = { on_actions = { v3tb_ev_secession } }
on_civil_war_won = { on_actions = { v3tb_ev_civilwarwon } }
on_peace_agreement_signed_war_leader = { on_actions = { v3tb_ev_peace } }
on_capitulation = { on_actions = { v3tb_ev_capit } }

# A diplomatic play that actually became a war. Distinct from on_diplomatic_play_started, which
# fires for every play including those resolved without fighting.
v3tb_ev_warstart = {
	effect = { debug_log = "V3TB|$Token|EV|WARSTART|[SCOPE.sCountry('initiator').GetNameNoFormatting]|[SCOPE.sCountry('target').GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]" }
}

# Revolutions and civil wars as EVENTS. The v4 STATE flags sample an instant, and civil wars are
# transient: over 1836-1856 the event log held 267 distinct revolt tags while 12 snapshots caught
# 8 episodes (~3%). Flags answer "was this country distorted AT this snapshot"; these answer "how
# many revolutions happened and to whom". Both are wanted.
# ⚠ Root scope for each of these is UNPROBED - GetRootScope.GetCountry is the common pattern but
# on_diplomatic_play_started has no country root, so these may need initiator/target instead.
v3tb_ev_revolt = {
	effect = { debug_log = "V3TB|$Token|EV|REVOLT|[SCOPE.GetRootScope.GetCountry.GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]" }
}
v3tb_ev_secession = {
	effect = { debug_log = "V3TB|$Token|EV|SECESSION|[SCOPE.GetRootScope.GetCountry.GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]" }
}
v3tb_ev_civilwarwon = {
	effect = { debug_log = "V3TB|$Token|EV|CIVILWARWON|[SCOPE.GetRootScope.GetCountry.GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]" }
}

# TRUE bankruptcy, as distinct from entering default. There is NO bankruptcy on_action, so we poll
# the static modifier the act applies (declared_bankruptcy) and latch it per country with a
# variable so each declaration is logged exactly once. See TESTBED_METRICS.md.
v3tb_bankruptcy_poll = {
	effect = {
		every_country = {
			limit = {
				has_modifier = declared_bankruptcy
				NOT = { has_variable = v3tb_bk_seen }
			}
			set_variable = v3tb_bk_seen
			debug_log = "V3TB|$Token|EV|BANKRUPTCY|[THIS.GetCountry.GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]|gdp=[THIS.GetCountry.GetGDP|2]"
		}
		every_country = {
			limit = {
				has_variable = v3tb_bk_seen
				NOT = { has_modifier = declared_bankruptcy }
			}
			remove_variable = v3tb_bk_seen
		}
	}
}

v3tb_ev_default = {
	effect = { debug_log = "V3TB|$Token|EV|DEFAULT|[SCOPE.GetRootScope.GetCountry.GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]|gdp=[SCOPE.GetRootScope.GetCountry.GetGDP|2]" }
}
v3tb_ev_dipplay = {
	effect = { debug_log = "V3TB|$Token|EV|DIPPLAY|[SCOPE.sCountry('initiator').GetNameNoFormatting]|[SCOPE.sCountry('target').GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]" }
}
v3tb_ev_peace = {
	effect = { debug_log = "V3TB|$Token|EV|PEACE|[SCOPE.GetRootScope.GetCountry.GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]" }
}
v3tb_ev_capit = {
	effect = { debug_log = "V3TB|$Token|EV|CAPIT|[SCOPE.GetRootScope.GetCountry.GetNameNoFormatting]|[TimeKeeper.GetCurrentDate.GetString]" }
}
"@
    }

    return @"
# AUTO-GENERATED by tools/telemetry_lib.ps1 via build.ps1 - do not edit by hand.
# TELEMETRY SCHEMA v$script:TELEMETRY_VERSION
# build: $BuildStamp   token: $Token
# dump dates: $($dates -join ', ')   tags: $($tags -join ', ')   metrics: $($metrics -join ', ')

on_game_started_after_lobby = {
	on_actions = { v3tb_boot }
}

on_monthly_pulse = {
	on_actions = { $($dumpNames -join ' ')$(if ($metrics -contains 'events') { ' v3tb_bankruptcy_poll' }) }
}

v3tb_boot = {
	effect = {
		debug_log = "V3TB|$Token|BOOT|v$script:TELEMETRY_VERSION|[TimeKeeper.GetCurrentDate.GetString]"
		# The RNG seed this run used. GetGlobalRandomSeed is a bare GLOBAL data function - vanilla
		# renders it in the loading screen via INGAME_RNG_SEED, so it works in any loc string.
		# GetGlobalRandomSeedString is the CUSTOM seed text, empty unless the custom_rng_seed game
		# rule is set to use_custom_rng_seed. Own line: if either fails, BOOT still survives.
		debug_log = "V3TB|$Token|SEED|[GetGlobalRandomSeed]|custom=[GetGlobalRandomSeedString]"
	}
}
$dumpBody$events
"@
}
